### ISSUE TITLE
Disable Screenshots

### ISSUE THREAD

**Issue by upD8R** [jamie-mh/AuthenticatorPro#10]
Hi,

I guess you are already aware of this topic but it seems several authenticator apps a open to a screenshot based attack. So it might be good to disable screenshots (or better make it a config option).
https://www.techradar.com/nz/news/google-2fa-authentication-could-be-less-secure-than-thought

**Comment by jamie-mh** [comment]
Hi, Thanks for pointing this out.
Fixed in 8ace664.
