### ISSUE TITLE
Option to skip confirmation upon unlocking via biometrics

### ISSUE THREAD

**Issue by flz** [jamie-mh/AuthenticatorPro#100]
Right now the app requires to manually confirm when unlocking. Looking at Aegis for example, the step isn't required. I don't know whether this is by design or not but eliminating one step/tap, as opt-in, would be nice.

**Comment by jamie-mh** [comment]
Hi @flz ,

From my testing, I've not encountered this. Does it prompt you to press an extra button after scanning your fingerprint?

**Comment by flz** [comment]
Yes, there's a Confirm button I need to tap. If that makes any difference, I use Face unlock not Fingerprint.

**Comment by jamie-mh** [comment]
It's probably fixed now, we'll see in the next release.

**Comment by jamie-mh** [comment]
Hi,

Can you confirm that this is no longer an issue in the most recent releases so I can close this issue. Thanks.

**Comment by flz** [comment]
Can confirm. Thanks!
