### ISSUE TITLE
Nextcloud Backups

### ISSUE THREAD

**Issue by Uneccessary** [jamie-mh/AuthenticatorPro#1000]
**Is your feature request related to a problem? Please describe.**
Backups can only be made locally and you have to manually move the file to another place to safe it rly securely if smth happens to the device.

**Describe the solution you'd like**
Encrypted or non encrypted Backups to Nextcloud option.

**Comment by Kvasenok** [comment]
You can actually make automatic backups to Nextcloud if you have their app installed. It allows you to choose Nextcloud next to you phone's local storage.
![Screenshot_20231019_082503_Files.png](https://github.com/jamie-mh/AuthenticatorPro/assets/44749170/6beff77f-2a16-45ef-b054-8dfe757da125)

**Comment by Kvasenok** [comment]
You can actually make automatic backups to Nextcloud if you have their app installed. It allows you to choose Nextcloud next to you phone's local storage.
![Screenshot_20231019_082503_Files.png](https://github.com/jamie-mh/AuthenticatorPro/assets/44749170/6beff77f-2a16-45ef-b054-8dfe757da125)
