### ISSUE TITLE
Google Authenticator now allows screenshot

### ISSUE THREAD

**Issue by fallsdevil** [jamie-mh/AuthenticatorPro#1004]
I would like to request an update to the Import Accounts Google Authenticator Wiki.

Two days ago I imported my accounts from this app to Authenticator Pro and by is on the latest version of Google Authenticator, it allowed without any problem the screenshot of the export QR Code and I was able to import normally without problems to the Authenticator Pro.

The app version of Google is in 6.0, I updated recently. Therefore, I think it is valid to inform this to update the Wiki.

**Comment by jamie-mh** [comment]
Indeed. Thanks for pointing this out!
