### ISSUE TITLE
Request for an Ultra Compact view

### ISSUE THREAD

**Issue by flz** [jamie-mh/AuthenticatorPro#101]
Have you thought about putting the codes between the account name and the 3 dots? I have a bunch of accounts and a list view that is more compact than the Compact view would be great.

**Comment by jamie-mh** [comment]
It might not be that simple. A more compact view might not have enough space for the HOTP refresh button, and the code might not fit next to the username depending on the width of the screen.

**Comment by jamie-mh** [comment]
Not feasible currently due to lack of space for certain controls.
