### ISSUE TITLE
Swipe to navigate between categories

### ISSUE THREAD

**Issue by OmarNazzal150** [jamie-mh/AuthenticatorPro#1022]
**Is your feature request related to a problem? Please describe.**

Problem

Using two taps to go between categories can be slow sometimes

**Describe the solution you'd like**

Solution
A feature should be implemented where you can swipe left and right on the main page to quickly go between different categories

**Additional context**
And also. if we can enable/disable the swipe categories in settings. If we want.
 Replaced by issue #530

**Comment by OmarNazzal150** [comment]
Because the developer never checked the old issue, so that guy opened 530# issue a year ago. And the developer never checks that. So that's why I opened this issue.

**Comment by OmarNazzal150** [comment]
I hope the developer checks this issue. I think a few days or weeks

**Comment by Kvasenok** [comment]
@OmarNazzal150 Yeah, he definately will, and he will close it as a duplicate.

**Comment by OmarNazzal150** [comment]
I hope So. Pretty Soon

**Comment by Kvasenok** [comment]
Why do I even bother...

**Comment by OmarNazzal150** [comment]
Why the developer closed this issue as not planned. This feature is very important and useful.

**Comment by MagicLike** [comment]
> Why the developer closed this issue as not planned. This feature is very important and useful.

It's a duplicate, see #530
