### ISSUE TITLE
TOTP URI format is incorrect in plain-text backups 

### ISSUE THREAD

**Issue by sbeve72** [jamie-mh/AuthenticatorPro#1023]
**Describe the bug**
The TOTP URI format in plain-text backups is wrong

**To Reproduce**
1. Open the hamburger menu
2. Select "Backup"
3. Click "Backup to URI List File"
4. Open the backed up URI list file
5. See the wrong format of URIs - The issuer name is added write after `://totp/` and then again as a key-pair value at the end. However, it only needs to be added to the key-pair value, according to the spec.

**Expected behavior**
There's no mention of the issuer in the beginning of the URI, only at the end after the `issuer` key

**App Version**
version 1.23.0

**Additional Context**
https://github.com/google/google-authenticator/wiki/Key-Uri-Format

**Comment by jamie-mh** [comment]
Hi @sbeve72 ,

Can you please provide an example?

As far as I can tell, the spec says that the URIs should follow this format:
`otpauth://totp/[issuer]:[username]?secret=[secret]&issuer=[issuer]`

> We recommend using **both** an issuer label prefix and an issuer parameter, described below.

> Older Google Authenticator implementations ignore the issuer parameter and rely upon the issuer label prefix to disambiguate accounts. Newer implementations will use the issuer parameter for internal disambiguation, it will not be displayed to the user. We recommend using both issuer label prefix and issuer parameter together to safely support both old and new Google Authenticator versions.

Cheers

**Comment by sbeve72** [comment]
You're right. It's actually the authenticator app I use on my Gnome Desktop that parses it incorrectly. I will open an issue there. Sorry for the inconvenience.
