### ISSUE TITLE
Reverse the visual display of assigned categories

### ISSUE THREAD

**Issue by anastrophe** [jamie-mh/AuthenticatorPro#1028]
**Is your feature request related to a problem? Please describe.**
In the "Assign categories" dialogue, the **selected** categories **do not** have a black outline on them. 
The **unselected** categories **have** a black outline on them.

**Describe the solution you'd like**
The current scheme is backwards, in my opinion. Typically, when something is selected, it _gains_ a visual identifier, rather than losing it. I have to remind myself any time I'm selecting categories that the scheme is counter-intuitive. 

Alternatively to reversing the outlining scheme, which might then confuse everyone once again by then following the intuitive scheme, perhaps just a 'filled' (colored-in) button for selected, and unselected are not filled, along with the lettering being 'greyed-out'.

**Comment by jamie-mh** [comment]
Hi @anastrophe ,

The current design follows the [Material You guidelines](https://m3.material.io/components/chips/guidelines#8d453d50-8d8e-43aa-9ae3-87ed134d2e64) for filter chips. I'd rather not change the design, as this would make it inconsistent with other apps.

Cheers

**Comment by anastrophe** [comment]
I understand, but I - not a coder - visited the link you provided. The great big graphic right on the main page shows a simple 'fix' that solves the ambiguity: addition of a checkmark (a 'leading icon' as the 'spec' page for a filter describes it) to indicate the chip has been selected/activated/whatever the proper coding term is. 

I don't know how hard it would be to add that, but it would be a massive improvement, from the perspective of just an average user.
