### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by 916BGAI** [jamie-mh/AuthenticatorPro#1032]
**Name of website / service:**
## Alibaba Cloud
https://www.aliyun.com/

**Comment by ch3thanhs** [comment]
Hi @916BGAI, Can we use the global domain - https://www.alibabacloud.com instead of the region specific - https://www.aliyun.com?

**Comment by ch3thanhs** [comment]
@Kvasenok, No problem. The thought behind my question was to check the requirements on SimilarWeb.

You can create the PR as you have the icon ready.
