### ISSUE TITLE
WearOS: Tile: accessing non-favorites once a favorite is picked

### ISSUE THREAD

**Issue by DeividasJackus** [jamie-mh/AuthenticatorPro#1034]
@jamie-mh I love the app and the WearOS companion, thank you for your work!

On WearOS, I exclusively use the tile for quick access, and prefer to have a favorite entry set.
However, once a favorite is set, I am forced look for the app whenever I need something else.

I wish I could see the favorite on the tile whenever I open it, but also have an easy way to access the rest of the list.

I'm not sure if tiles allow swiping or scrolling, and it's likely not worth the effort.
Would you perhaps be open to the idea that when a favorite is selected and displayed, clicking on it opens up the full list, so you can access non-favorites?

**Comment by jamie-mh** [comment]
Same as #839.

Hi @DeividasJackus ,

Wear OS tiles are quite primitive, so swiping and scrolling is not really possible.
In fb83e0e I've made a change, tapping the tile now opens the full app.

Cheers
