### ISSUE TITLE
Wear OS Standalone?

### ISSUE THREAD

**Issue by xrh0905** [jamie-mh/AuthenticatorPro#1047]
**Is your feature request related to a problem? Please describe.**
When I need to use my wear os device to generate my TOTP code, It usually indicated that I don't have access to my phone, so it would be reasonable to cache the creditical in the Wear APP, and generate the code on wear.

**Describe the solution you'd like**
It's reasonable to design the APP to only use remote creditical since Wear device are usually weak, but I believe introduce the feature to require double authenicate use system screen locker like the WearAuthn would be a reasonable choice.

**Additional context**

**Comment by jamie-mh** [comment]
> When I need to use my wear os device to generate my TOTP code, It usually indicated that I don't have access to my phone, so it would be reasonable to cache the creditical in the Wear APP, and generate the code on wear.

This is already the case, you don't need a persistent connection to the phone to generated codes.
