### ISSUE TITLE
Code Group Size: "None"

### ISSUE THREAD

**Issue by discgolfdc** [jamie-mh/AuthenticatorPro#1057]
**Is your feature request related to a problem? Please describe.**

No. Purely preference. No functional deficits that I can define.

**Describe the solution you'd like**

The app currently provides for code group sizes of 2, 3, and 4.  Requesting a "none" (or similarly/appropriately-named) option so the string of numbers/characters is not broken up or chunked.  Option for 123456 as opposed to 12 34 56 or 123 456 or 1234 56.

**Additional context**

None.  Wanted to follow your requested protocol for feature requests.  I know email can be goofy, and this is a better way to keep "stuff" together.  Thank you.

**Comment by jamie-mh** [comment]
Added in 1.24.0
