### ISSUE TITLE
[FR] Network disk backup?

### ISSUE THREAD

**Issue by magojohnji** [jamie-mh/AuthenticatorPro#1058]
**Is your feature request related to a problem? Please describe.**
I often struggle with the hassle of manual backups.

**Describe the solution you'd like**
Using Outlook and other cloud storage for synchronization.

**Additional context**
None

**Comment by ch3thanhs** [comment]
You can use an app like FolderSync to set up scheduled backups.

**Comment by jamie-mh** [comment]
Duplicate of #16.
