### ISSUE TITLE
More Encryption Options

### ISSUE THREAD

**Issue by archit9169** [jamie-mh/AuthenticatorPro#106]
Is it possible to get more encryption options such as scrypt or argon2 ? And is the vault encrypted in the same way that backup is encrypted or something else? Maybe encrypt the vault with the current standard and enrypt the backups with more secure standards?

Please state your thoughts on this.

**Comment by jamie-mh** [comment]
PBKDF2 is used to derive keys for both the backup files and the database. Using scrypt or Argon2 is unlikely to bring any real world security benefits in this scenario. The best way to improve security would be to simply use a longer more complex password.
