### ISSUE TITLE
in steam method, cancelling the space between 3&4th letters looks better

### ISSUE THREAD

**Issue by THR-hub** [jamie-mh/AuthenticatorPro#1065]
it is better to cancel the space between the 3rd and 4th characters (for steam type keys).

the one time key with type steam, which looks like 'A1B2C', is showed like 'A1B 2C'. the space makes it look better for common totps(6 numbers), but strange for steam type.

**Comment by K0-RR** [comment]
So you're telling me 5 digits are easier to read than 3 + 2 separated?

**Comment by THR-hub** [comment]
> So you're telling me 5 digits are easier to read than 3 + 2 separated?

yes

**Comment by jamie-mh** [comment]
https://www.youtube.com/watch?v=pWdd6_ZxX8c
