### ISSUE TITLE
Android 14 incompatible warning

### ISSUE THREAD

**Issue by truthsword** [jamie-mh/AuthenticatorPro#1083]
**Describe the bug**
When I installed this to my Pixel 5a, I got a warning that the app is incompatible with my Android version. Still it installed. 

**To Reproduce**
Install on device with Android 14

**Expected behavior**
No compatibility warning

**App Version**
1.24.0 F-Droid sourced

**Additional context**

**Comment by jamie-mh** [comment]
Hi,

Can you please provide the exact wording of the warning message?
The app targets Android 14 ([SDK 34](https://github.com/jamie-mh/AuthenticatorPro/blob/a6744478f060862948c35c527505461e26d860a7/AuthenticatorPro.Droid/Properties/AndroidManifest.xml#L5)) so there shouldn't be a warning. Indeed, I can't reproduce the issue on an Android 14 emulator nor my physical device (S22 with Android 14).

Thanks

**Comment by Kenny417** [comment]
> This app isn't compatible with the latest version of Android. Check for an update or contact the app's developer.

This happens on first launch after installing it. I was able to reproduce it for this screenshot but clearing cache and app storage. After I tap OK, it seems like I can use the app normally. 

![Screenshot_20240203-104412](https://github.com/jamie-mh/AuthenticatorPro/assets/46543251/03e62b75-5ede-47cf-8446-a3489c6ece90)

**Comment by truthsword** [comment]
My installation was from Izzy. Would that make a difference?

If I ran a backup and then uninstalled, deleting cache/memory storage, would the backup restore include my settings?

**Comment by Kenny417** [comment]
It seems like maybe this is an error that happens when running a 32 bit app on a 64 bit device, if that helps you test this @jamie-mh 

https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/core/res/res/values/strings.xml;l=5420?q=deprecated_abi_message%20f:strings.xml%20%22compatible%20with%20the%20latest%20version%20of%20Android%22%20%20

**Comment by truthsword** [comment]
I'm unsure this case is bitness related, as I have many apps on my phone, and I doubt that they are all 64-bit. Yet this is the only installation where I've seen this warning.

**Comment by Kenny417** [comment]
@jamie-mh Is the armeabi-v7a version the one uploaded to the Izzy / Fdroid repo? When I scroll down to the bottom of [this page](https://apt.izzysoft.de/fdroid/index/apk/me.jmh.authenticatorpro), that's the version it shows. That's not the right version for my Pixel 6. 

I just manually installed the `me.jmh.authenticatorpro-arm64-v8a.fdroid.apk` version from the Releases page in this repo and did not get the incompatible message on first launch.

It's late and I'm exhausted so I may be completely wrong here, but I feel like the wrong version was uploaded to Fdroid or I somehow downloaded the wrong version from Fdroid.

**Comment by truthsword** [comment]
That's interesting as the download I received is named me.jmh.authenticatorpro_100000092.apk

Feb 6, 2024 2:19:56 AM Kenny - notifications at github.com ***@***.***>:

**Comment by jamie-mh** [comment]
Yes, the version on Izzy's repo is the 32-bit version (see #724 for info). Since the error message is unique, that seems like the most likely explanation.

@IzzySoft would switching to the 64-bit build be seamless for users (provided they have a 64-bit device of course) ?

Cheers

**Comment by Kenny417** [comment]
Ah, I see. That issue #724 clears it all up for me. I'll probably experiment with using Obtanium to download the version I need from this repo and keep getting updates when they are released. 

I'll keep following this Issue though since using the Izzy repo on Fdroid is more ideal for me in the long run.

**Comment by IzzySoft** [comment]
> would switching to the 64-bit build be seamless for users (provided they have a 64-bit device of course) ?

If the `versionCode` of the 64bit one is always equal or higher than the one of the 32bit, yes. But those on "pure 32bit" devices are then stuck and won't receive updates anymore.

When I one day have the spoons for it (too many other tasks at the moment), I might set up another repo for "legacy devices"…
