### ISSUE TITLE
Adding a windows client

### ISSUE THREAD

**Issue by JohnVictoryz** [jamie-mh/AuthenticatorPro#1089]
**Is your feature request related to a problem? Please describe.**
Yes, it's something that i feel would be cool and useful to have instead of having like to open my phone i can just open my codes on my PC

**Describe the solution you'd like**
A official version of the app that can run on PC like windows, mac and linux

**Additional context**
It would be cool if they can sync all together like Authy and other authenticators

**Comment by jamie-mh** [comment]
Duplicate of #484.
