### ISSUE TITLE
Massive entries adding

### ISSUE THREAD

**Issue by Engel1ST** [jamie-mh/AuthenticatorPro#11]
Hello,

I've try to import massively some entries by using the import option. I've recreate the Json architecture as on an export example but it's crash after the import.

I've used few websites to test my json and validate it. On multiple website, the json is valid.

How works AuthenticatorCategories ? I should put and CategoryId targeting an id in the Categories and use an AuthenticatorSecret from Authenticators right ?

Any way to add an error log or warning or something equivalent? I'am importing 55 entries :).

Thanks.

Alex.

**Comment by jamie-mh** [comment]
Hi @Engel1ST 

I don't see why the number of entries would be a problem. There must be an issue with your file. Here is an example of what a backup file looks like:

```
{
  "Authenticators": [
    {
      "Type": 2,
      "Icon": "google",
      "Issuer": "Google",
      "Username": "google@gmail.com",
      "Secret": "SECRETKEY123ABCD",
      "Algorithm": 0,
      "Digits": 6,
      "Period": 30,
      "Counter": 0,
      "Ranking": 0
    }
  ],
  "Categories": [
    {
      "Id": "a8323a2a",
      "Name": "Web",
      "Ranking": 0
    }
  ],
  "AuthenticatorCategories": [
    {
      "CategoryId": "a8323a2a",
      "AuthenticatorSecret": "SECRETKEY123ABCD",
      "Ranking": 0
    }
  ]
}
```
The Category Id is a random string of 8 alphanumeric characters.
The AuthenticatorCategory is a pair made up of the Category Id and the Authenticator Secret.

In your case, it might be easier for you to leave the Categories and AuthenticatorCategories arrays empty and just create them in the app once you've imported your authenticators.

Let me know if this works for you.

**Comment by Engel1ST** [comment]
Hi jamie-mh,

First of all an HUGE merci (en Français haha). I figure out the problem!

For information, I used http://json.parser.online.fr/ to validate my JSON. Almost everytime, my JSON was valid.

After multiple try (around more than 100 ), I discovered that, if you import a .authpro files with "_AuthenticatorSecret_" containing LOWERCASE or SPACE in it, the apps crash after few seconds (or almost instantly).
Some provider (like Google (not every time) or Instagram) give secret key with SPACE or in LOWERCASE. When creating manualy the JSON for the .authpro file, the user has to put every "_AuthenticatorSecret_" in UPPERCASE and without SPACE. I've tested multiple time and the SAME key with or without SPACE OR lower/uppercase doesnt matter => generated code is the same.

Maybe it will be great if you can write somewhere a little tutorial or an info/warning to prevent this trouble. Another solution will be to remove automatically the SPACE and put all "_AuthenticatorSecret_" in UPPERCASE during the import process!

Now, I've 55 entries in my DB and all is AWSOME!

Thanks you for this great apps. I was looking for a lonnnnnng time an app with search function.

**Comment by jamie-mh** [comment]
Great!
I'll write some documentation on how the backup files work, it could be useful for anyone else with this issue. As for the icons request you created, I'll get round to that soon when I get the time.
