### ISSUE TITLE
Import from Authenticator Plus fails

### ISSUE THREAD

**Issue by Mave922** [jamie-mh/AuthenticatorPro#110]
I'm trying to import from Authenticator Plus. I'm being told either the password is incorrect or the file is corrupt. I have verified and changed the password. I have also created a new backup file with no success. I understand this is probably out of your hands, just curious if there is another step I should take?

**Comment by jamie-mh** [comment]
I don't know the intricacies of the Authenticator Plus format, so there is perhaps something I've missed which is throwing of the import. I'll continue testing it to find edge cases that I might not have considered.

In the meantime, I suppose you could use the "Export as Text and HTML" option and extract the accounts.txt file from that. You should be able to import that using the "URI list" option.

**Comment by EvilBMP** [comment]
You can use Aegis Authenticator to import the Authenticator Plus export to Aegis. And from Aegis you can export and import to Authenticator Pro. I know that sounds weard, but I my case I was testing Aegis before Authenticator Pro. And I had the same problems importing the data from Authenticator Plus direction directly. But I was able to import the export from Aegis.

Maybe, that's a workaround for you too.

**Comment by rkerr** [comment]
I also had the same issue so had a poke around the backup file - in my case I found that there were two accounts in the export where the issuer field was blank. If I removed those two accounts from Authenticator Plus before exporting then the backup imported into Authenticator Pro fine.

I can't really be sure how those accounts came to have a blank issuer, but they were the oldest accounts I had in Authenticator Plus. I would suspect the Authenticator Plus database format changed at some time in the past and Authenticator Plus may not have recorded issuers for really old accounts. There doesn't unfortunately seem to be any way to add/modify issuer for an account once added to Authenticator Plus.

**Comment by jamie-mh** [comment]
Hi everyone,
Thanks for your feedback.

I've looked into this further and trying every combination of issuer / username, no issuer and username, etc... I'm having trouble finding a case where it fails, so perhaps the database format changed at some point. I've been able to test with the latest version.

In the database there is another field called `original_name` which should contain the issuer and username even if they're not displayed. So, I've changed the code to import from that instead.

If anyone could help me test this, that would be much appreciated.

**Comment by rkerr** [comment]
I think you have to be careful here... original_name looks less consistent in the backup I have.

The entries with a blank issuer have email = original_name
I have two entries with issuer set correctly but email = original_name
The majority of entries have original_name set as issuer:email

You're probably better off just importing with Unknown as the issuer if it's blank. At least Authenticator Pro allows you to change the issuer after import.

**Comment by jamie-mh** [comment]
After some investigation, I think I've arrived at the best possible solution:

- If issuer and email fields are filled, use them
- If the issuer field is blank, check the original name field
    - If the original name field is in the issuer:email format, extract the issuer
    - If all else fails, use the email field as the issuer

Since the email cannot be blank, we should have an issuer in every case.
Does this sound correct, or is there a scenario where this wouldn't work with your backup?

**Comment by rkerr** [comment]
Sounds sane to me and looks like it would work for the backup I have.

**Comment by rkerr** [comment]
Have tried an import with the latest version and can confirm it works fine with the backup I have.

**Comment by jamie-mh** [comment]
Thanks, I'll consider this solved then.
