### ISSUE TITLE
Errors when importing files from other applications

### ISSUE THREAD

**Issue by Coolkkmeat** [jamie-mh/AuthenticatorPro#1100]
When I import .2fa files generated by 2FAS Auth using the latest version of Authenticator Pro, a few are successfully imported, but most of them say that the import is incomplete "Import failed, Too few digits, expected at least 6", for example GitHub and Microsoft account.
Is this a bug or is there something I'm doing wrong?

**Comment by jamie-mh** [comment]
This seems to be due to how 2FAS handles the defaults for the digit parameter. Fixed in ef7e1b82adf5ccdff7c18f0b6ce7262a577e93d1.
