### ISSUE TITLE
Import says it failed, but it succeeded

### ISSUE THREAD

**Issue by paolostivanin** [jamie-mh/AuthenticatorPro#1101]
Hello,
I've added import/export plain/encrypted support of your app to my [software](https://github.com/paolostivanin/OTPClient/) and, while I was testing it, I found a couple of issues.

1. when importing the attached plain text json, it asks for a password. I supply none, get an error, exit the app and re-enter it and all the tokens are there working fine
2. when importing the attached encrypted file, it asks for a password, I give the correct one, I get an error, I exit and re-enter the app and all tokens are there working fine.

OS: Android 12
App version: latest available as of today from the Play Store.

The zip containing the plain and encrypted exports: [authpro.zip](https://github.com/jamie-mh/AuthenticatorPro/files/14431552/authpro.zip)

The password for the encrypted export is `test`.

Thanks

**Comment by jamie-mh** [comment]
Hi @paolostivanin ,

This seems to be due to a validation error when loading your backup. The Steam:Sophia entry has a type of 2 when it should have a type of 4 (Steam). I realise the error could be clearer in this scenario.

Cheers

**Comment by paolostivanin** [comment]
Ah wonderful, thanks a lot! I'll fix that asap :)
