### ISSUE TITLE
AttackIQ

### ISSUE THREAD

**Issue by ManiusNG** [jamie-mh/AuthenticatorPro#1107]
Please fill out the fields below where applicable:

https://www.attackiq.com/

**Comment by jamie-mh** [comment]
Hi,

Unfortunately, this service doesn't meet the requirements for an icon.

![image](https://github.com/jamie-mh/AuthenticatorPro/assets/7887162/bfbd4711-ee1a-4b7e-9ba9-96d21be90579)

Cheers
