### ISSUE TITLE
Camera Scan Don't work

### ISSUE THREAD

**Issue by saltsoftdrink** [jamie-mh/AuthenticatorPro#1109]
It doesn't auto scan from camera, it only works when we import photo

**Comment by s-gbz** [comment]
Same here 🙁
Nothing happens!

**Comment by saltsoftdrink** [comment]
@jamie-mh

**Comment by dhoove** [comment]
This also happens to me on Samsung a S21fe with auth pro version 1.25.0, if my phone is in **portrait** mode.

I am able to add a new entry by:

- Taking a screenshot and then scanning from the gallery
- Switching to landscape mode before I scan the QR code

**Comment by shuvooo5111** [comment]
Please qr scan show
