### ISSUE TITLE
Request for an Option to hide a Category from All

### ISSUE THREAD

**Issue by Gh0st0** [jamie-mh/AuthenticatorPro#111]
It would be very useful to be able to hide/exclude the codes of a category from the All list.
I always prefer to have the All list as my default, but there are multiple codes that I rarely use.

**Comment by jamie-mh** [comment]
This would simply default the purpose of the "All" category. If you hide a item from the "All" list and it's not assigned to any category, it would disappear into the void. You can create a category with your most frequently used authenticators and make that the default.

**Comment by Gh0st0** [comment]
Thank you for your reply.
I understand the risk of hiding individual items, I actually was thinking about an option to hide a category from the "All" list, so all the items in that category won't show in the "All" list.
Your advice is also helpful, but that's the difference between "Blick List" and "White List", instead of choosing the most used authenticators, I can just choose the ones that I don't often use.

**Comment by jamie-mh** [comment]
I understand what you're saying now, I didn't quite catch the meaning the first time. However, as I've said, there is already an option to achieve the effect you're looking for, it's just the opposite of the way you suggested it.
In my opinion, the idea of selecting items you don't want to appear is less user friendly that selecting the items you do.
