### ISSUE TITLE
Bug? Cosmic Rays?

### ISSUE THREAD

**Issue by anastrophe** [jamie-mh/AuthenticatorPro#112]
I opened up Authenticator Pro just now, as I do nearly every day - often multiple times a day. It...went straight to app. It didn't pop up the Biometric lock. Checked in settings. Biometric lock disabled, and can't be enabled. Clicked on password. NO PASSWORD in place, which is why bio can't be enabled. 

How could the app lose it's password? Could this suggest my phone's been 'hacked'? Unlikely, I'm pretty darned good with my security hygiene.

I'm pretty worried about this. I just now re-added the password, and it seems to be working fine, but that's small consolation...

Note that I was apparently one rev behind on the app when I first opened it while it wasn't asking for password. I dutifully updated the app to the jan 28 release, but obviously it made no difference, as the app had simply lost the password I had set it up with. 

Also, no Android OS updates recently, other than the early january security update.

Help.......

**Comment by jamie-mh** [comment]
I don't understand how this would be possible. In order to clear the password, the database would need to be unlocked so that the data can be read and decrypted. Futhermore, assuming that you're not using a rooted device or a debug build of the app, there would be now way for anyone to access the database file directly.

Can you remember what version you were on when you set the password (or a rough date perhaps)?

**Comment by anastrophe** [comment]
I can only assume I was on the immediate previous version of AP before updating, since I do have auto-update on in google play. The device isn't rooted (Pixel 3 XL)(although I wish it was, I've been meaning to do so ever since I got two years ago, lol). Not on any special build debug or otherwise, installed and updated directly from app store.

I believe I updated my device password back around Jan 15, when I received two new YubiKeys and used the opportunity to just do a top-down refresh of all critical passwords - but I don't think I directly changed the AP password, just the device password.

Because of the encryption, I'd have to assume that somehow the password was wiped/cleared/whatever while the app was unlocked, but I still can't imagine a mechanism for that to happen without my direct involvement. 

Who knows, maybe it really was a bit-flip due to a cosmic ray! I'm keeping a close eye on things. 

Should I consider installing a debug version for further monitoring/diagnosis, and if so, how do I go about that?

**Comment by jamie-mh** [comment]
I doubt that unless you were using the app in outer space or whilst standing in the Chernobyl reactor core, a random bit flip is unlikely to have any significant effect. Also, the app password is not tied to the device password, so changing that won't make a difference.

There is no need to install any debug versions, just let me know if anything strange happens again.

**Comment by anastrophe** [comment]
Heh, I'm inclined to agree on the likelyhood of it being cosmic rays. Anyway, I'll keep an eye on it. I have a minor UI feature suggestion, I'll start a new thread on that. Thanks!
