### ISSUE TITLE
How does Authenticator Pro handle timezones?

### ISSUE THREAD

**Issue by s22-tech** [jamie-mh/AuthenticatorPro#1121]
I downloaded Authenticator Pro the other day and it works fantastically!  Thank you.  Another alternative to Google's offerings.

Your FAQ says "A difference of more than a few seconds may cause invalid codes to be generated."

Since Authenticator is time based, how does it deal with the time being an hour or more different?  Especially if we're overseas using a local SIM?

Thanks again.

**Comment by kwilcz** [comment]
It always uses UTC time:

https://github.com/jamie-mh/AuthenticatorPro/blob/b7d64024081c79f311bb3e91665a18a9f83cd193/AuthenticatorPro.Core/src/Entity/Authenticator.cs#L107-L129

Simply said, as long as your device has proper time set up, you don't have to worry about time zones.

**Comment by s22-tech** [comment]
That's good news!  Thank you.
