### ISSUE TITLE
Unable to Backup, Showing toast : Cannot open file picker, A file manager must be installed

### ISSUE THREAD

**Issue by ifahadone** [jamie-mh/AuthenticatorPro#1125]
**Describe the bug**

**To Reproduce**
1. Go to 'Menu'
2. Click on 'Backup'
3. Any item from the options

**Expected behavior**
Unable to backup

**App Version**
Version number of the app, found in Settings -> About.

**Additional context**

**Comment by ch3thanhs** [comment]
Is file manager like Google Files or Material Files installed on your device?
