### ISSUE TITLE
Adding cloud sync via Android

### ISSUE THREAD

**Issue by CatGamer23** [jamie-mh/AuthenticatorPro#1133]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Eg. I'm always frustrated when [...]
I want to be able to sync my encrypted backup file to Google Drive or other syncing services without having to setup a 3rd party service.

**Describe the solution you'd like**
Instead of syncing directly to Google Drive, etc. by adding the APIs/SDKs to the app, I think adding the "All files" permission, or the write version of it would allow access to the Google Drive storage of accounts signed in on the phone via the android file explorer.

**Additional context**

**Comment by jamie-mh** [comment]
Hi,

I don't want to add the all files permission as it's a "high risk" permission according to Google. They will simply remove the app from Google Play if they don't think the usage is acceptable.

Cheers
