### ISSUE TITLE
Feature Suggestion: Importing from Bitwarden Authenticator

### ISSUE THREAD

**Issue by OmarNazzal150** [jamie-mh/AuthenticatorPro#1136]
Dear Jamie M. Hodgson (jmh),

I hope this message finds you well. I am an avid user of Authenticator Pro and truly appreciate the work you’ve put into creating such a robust and user-friendly 2FA app.

I’m reaching out to suggest a feature that I believe would significantly enhance the app’s functionality for many users. Currently, Authenticator Pro supports importing tokens from several popular authenticator apps, which is incredibly useful. However, I noticed that it does not support importing from Bitwarden Authenticator.

Bitwarden is a widely-used password manager that also offers 2FA token generation, and it allows users to export their vault, including the 2FA tokens, as a file. Having the ability to import these tokens directly into Authenticator Pro would streamline the process for users transitioning between services or looking to consolidate their 2FA codes.

I understand that implementing new features takes time and resources, and I’m more than willing to wait patiently. I believe this addition would be welcomed by the community and further solidify Authenticator Pro’s position as a top choice for secure authentication.

Thank you for considering my suggestion. Keep up the fantastic work!

Warm regards,

**Comment by jamie-mh** [comment]
Please use the issue templates. The Bitwarden Authenticator app appears to use the same format as the regular Bitwarden exports. A small issue has been fixed in the importer so it will work as expected in the next release.
