### ISSUE TITLE
Message in Spanish, please translate it.

Quisiera saber y no sé si ya algunas personas hayan pedido lo mismo, sería la opción de agregar copia de seguridad en la nube, que se pueda guardar con Google Drive para poder guardar las copias de seguridad en la cuenta de Google, creo que sería algo genial y me motivaría a donar al projecto ya que es muy bueno.

### ISSUE THREAD

**Issue by af-laiton** [jamie-mh/AuthenticatorPro#1141]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Eg. I'm always frustrated when [...]

**Describe the solution you'd like**

**Additional context**

**Comment by jamie-mh** [comment]
[FAQ](https://github.com/jamie-mh/AuthenticatorPro/wiki/Frequently-Asked-Questions#can-you-add-sync-to-google-drive-onedrive-etc)
