### ISSUE TITLE
QR Scan not working

### ISSUE THREAD

**Issue by Carmelo309** [jamie-mh/AuthenticatorPro#1148]
When I go to add a token with qr code the camera doesn't detect the code. If I scan the qr code from the system camera and select the application, it works. Would you know how to fix it? 
Smartphone : Poco F3, software Miui 13.0.11, android 12
App version: 1.25.0

**Comment by Carmelo309** [comment]
@jamie-mh Sorry for the trouble, I wanted to let you know

**Comment by jamie-mh** [comment]
No worries. I'm well aware though.
I've received loads of messages about the subject (despite it working perfectly fine on every device I've tried).
Duplicate of #1109.

**Comment by Carmelo309** [comment]
@jamie-mh I just reinstalled the app , put me version 1.25.1 and now the addition of OTPs seems to work correctly with the QR Scan Code in the app!
