### ISSUE TITLE
when opening a new screen, a weird animation glitch occurs

### ISSUE THREAD

**Issue by sbeve72** [jamie-mh/AuthenticatorPro#115]
If you, for example, go to the settings page from the main screen (where all the codes are shown), you would notice a weird glitch where the screen youre currently on would turn black and the screen you asked to navigate to shows after that happen. Its definitely not a huge deal and nitpicking at this point but its still something that happens and i like how perfect this app is so I just want it to be more perfect.

**Comment by jamie-mh** [comment]
Is it just the list of authenticators or the whole screen that disappears?
The list should disappear, that it intentional. I suppose it could be animated to fade out if that would improve the appearance.

**Comment by sbeve72** [comment]
The list of codes

**Comment by sbeve72** [comment]
> The list should disappear, that it intentional. I suppose it could be animated to fade out if that would improve the appearance.

I dont think its very intuitive. It should seem like the new page is coming over the old page as if they are stacking on top of each other.

**Comment by jamie-mh** [comment]
The idea is to prevent any account details from being visible before the password screen appears.
As for the new page stacking on top of the other one, that's up to Android, not up to me.

**Comment by sbeve72** [comment]
then I guess you could make it a fading aanimaion

**Comment by sbeve72** [comment]
i should mention that didnt exist 4 updates ago

**Comment by jamie-mh** [comment]
Hi,

The list should now fade out and be less jarring in the latest version (1.14.3) can you confirm? Thanks.

**Comment by sbeve72** [comment]
yes its perfect now thanks
