### ISSUE TITLE
Plain text URI list backup replaces @ and : with HTML escape sequences

### ISSUE THREAD

**Issue by 103sbavert** [jamie-mh/AuthenticatorPro#1154]
**Describe the bug**
When you make a backup to a plain text file as a URI list, the actual ":" and "@" characters are replaced by %3A and %40, respectively.
So for example
`otpauth://totp/GitHub:email@example.com?secret=xyz&issuer=GitHub`

becomes
`otpauth://totp/GitHub%3Aemail%40example.com?secret=xyz&issuer=GitHub`

**To Reproduce**
1. Click on backup
2. Select the third and last option (Plain text URI list)
3. Save the file somewhere
4. Open the file
5. See the characters being replaced incorrectly

**Expected behavior**
The literal @ and : are used

**App Version**
Has been happening since forever but rn I am at `1.25.1`

**Additional context**
This is a problem because even tho Auth Pro correctly decodes the escape sequences, the Gnome Authenticator App on my Linux PC gets confused (and rightfully so).

**Comment by jamie-mh** [comment]
Hi,

This is intended. The behaviour is consistent with the [spec](https://github.com/google/google-authenticator/wiki/Key-Uri-Format#label).

**Comment by 103sbavert** [comment]
Well, ig i need to open an issue over there at Gnome Authenticator.
