### ISSUE TITLE
Wear OS tile countdown

### ISSUE THREAD

**Issue by dedabrane** [jamie-mh/AuthenticatorPro#1180]
Hi!
Just a thought, I think it would maybe be useful...
When swiping to open the watch tile it would be great to have a countdown like in the phone app to know if you're gonna wait for the new code of you have enough time to use the current.

This could maybe be a blue circle countdown like the one that shows up rotating when loading the watch app for the first time.

Thanks!

**Comment by jamie-mh** [comment]
Hi,

It's not possible. Wear OS tiles are very simple and cannot be updated frequently enough to show a countdown timer.

Cheers
