### ISSUE TITLE
Phone and watch won't sync

### ISSUE THREAD

**Issue by backslashV** [jamie-mh/AuthenticatorPro#1181]
**Describe the bug**
Phone app won't sync with watch app.

**To Reproduce**
1. Install wear app on Pixel Watch 3
2. On the phone (Pixel 9), import accounts from Google Authenticator to AuthenticatorPro
3. Wait...

**Expected behavior**
Accounts should appear on the watch app.

**App Version**
Phone: 1.25.2 F-Droid
Watch: 2.15.4

**Additional context**
Tried uninstalling and reinstalling apps on both devices to no avail.

**Comment by jamie-mh** [comment]
https://github.com/jamie-mh/AuthenticatorPro/wiki/Frequently-Asked-Questions#why-does-the-wear-os-app-say-no-authenticators-with-a-blue-cloud-icon

**Comment by backslashV** [comment]
> https://github.com/jamie-mh/AuthenticatorPro/wiki/Frequently-Asked-Questions#why-does-the-wear-os-app-say-no-authenticators-with-a-blue-cloud-icon

Thank you for your response. I specifically went through the FAQ so I apologize for missing that section. After Installing the Google Play version on the phone, things are working.
