### ISSUE TITLE
Add new icon

### ISSUE THREAD

**Issue by Engel1ST** [jamie-mh/AuthenticatorPro#12]
Hello,

Sorry, I'am unable to put this request into "Pull requests".

Can you add icons for theses Websites/services on the next release please ? 
- Online.net : www.online.net
- 3CX : https://www.3cx.fr/
- Snapchat : https://www.snapchat.com/
- Uptime Robot : https://uptimerobot.com/
- Wargaming : https://eu.wargaming.net/en/

Thank you so much.

Alex.

**Comment by jamie-mh** [comment]
Icons added in 53e8b79, published in release 1.7.3.
