### ISSUE TITLE
Fastlane changelogs

### ISSUE THREAD

**Issue by IzzySoft** [jamie-mh/AuthenticatorPro#13]
It looks like since v1.6.2, you forgot to add the [per-release changelogs in Fastlane](https://github.com/jamie-mh/AuthenticatorPro/tree/master/fastlane/metadata/android/en-US/changelogs). Could you please start adding them again (maybe starting with the current one – not essentially needed to fill the entire gap, though that would be consistent)? Thanks!

**Comment by jamie-mh** [comment]
Oh my bad, I forgot about that. The changelogs are up to date now.

**Comment by IzzySoft** [comment]
Ah, great – Thanks! No blame, was just a "friendly reminder" :smile: Good they are back now.

**Comment by IzzySoft** [comment]
Sorry for nagging, but 1.7.5 lacks them again…

**Comment by jamie-mh** [comment]
Oops, I simply forgot to push the latest commit :)

**Comment by IzzySoft** [comment]
Heh… Same happened to me yesterday on one of my projects. Had to drop the tag again, add that last commit, and tag again :rofl: Thanks!

**Comment by jamie-mh** [comment]
I've deleted the tag and added it again. Hopefully that works.

**Comment by IzzySoft** [comment]
Thanks! Yes, it's there now.
