### ISSUE TITLE
Using WinAuth as a better way to import Blizzard Authenticator

### ISSUE THREAD

**Issue by Thunderschnozzle** [jamie-mh/AuthenticatorPro#132]
Hi everybody,

I tried to follow the current specified method for importing from Blizzard Authenticator using Python and didn't have much success. I installed python-bna and python-qrcode, but than got stuck on the following steps (the rest of the instructions just look like gibberish to me :)). 
So, I searched online and found an easier way to do so using WinAuth . I'll put the instructions below in case you want to replace the current wiki instructions with these. Please thank the proper people from the 2 sources that I've provided as they deserve all the credit here. I just rewrote their work into an easier to understand set of instructions.
Note: You can also use WinAuth in the same manner to add a Steam account 2FA code generator to Authenticator Pro!!!

----------------------------------------------------------------------------------------------------------------------------------------------
Adding a Blizzard account 2FA code generator to Authenticator Pro:

Sources:

1. https://www.reddit.com/r/Blizzard/comments/6pixcg/how_to_use_a_third_party_otp_app_for_2_step/

2. https://github.com/winauth/winauth

Instructions:

1. Download the "WinAuth-3.5.1.zip" file from "https://github.com/winauth/winauth" and extract its content.

2. Double-click on the "WinAuth.exe" file to run it.

3. Click on "Add" ---> "Battle.Net" ---> "Create Authenticator". This will generate a serial number and an authenticator (a.k.a. Login) code. You'll need those for step # 6. Check the "Allow copy?" check box so you'll be able to copy those 2 codes to the clipboard.

4. Go to "www.blizzard.com" and log in to your account.

5. Go to "Account Settings" ---> "Security" and then click on "SET UP AN AUTHENTICATOR" ---> "Set up a mobile authenticator".

6. Enter the verification code sent to your Email/SMS to get through the security check.

7. Enter the serial number and authenticator code from step # 2 into the "ENTER AUTHENTICATOR INFORMATION" window and then click on "Add Authenticator" ---> "Back to security".

8. In the "WinAuth" window, click on "OK" ---> "Cancel" ---> "Cogwheel" ---> "Export..." ---> "Browse..." (DO NOT CHECK ANY OF THE 2 "Protect" CHECK BOXES!!!) ---> "Save" ---> "OK".

9. Open the "winauth-current year-current month-current day.txt" file you just created and copy its content (a single line of text) to the clipboard.

10. Go to "https://www.qr-code-generator.com/" and paste the line of text you just copied in step # 9 where it says "Enter your website, text or drop a file here". A QR code will be generated automatically.

11. Scan the QR code with the "Authenticator Pro" app and you're good to go!!!

12. Optional: In the "Authenticator Pro" app, change the issuer name to "Blizzard", the username to your username, and assign the "blizzard" icon manually.
----------------------------------------------------------------------------------------------------------------------------------------------

**Comment by jamie-mh** [comment]
Hi @Thunderschnozzle ,

Thanks for your contribution. I've added it to the wiki as another method for importing. Since WinAuth is, as the name implies, Windows only, I've kept the original guide for those on Mac and Linux.
