### ISSUE TITLE
Default category back to All

### ISSUE THREAD

**Issue by Gh0st0** [jamie-mh/AuthenticatorPro#133]
When I set any category as the default, and then when I open the app, I get presented by that category, but when I click the back button, I go to the All list instead of existing the app.

1. Set a category as default
2. Close and Open the app, then you will get presented by the selected category
3. Click the back button, you will see the All list

Expected behavior:
When I click back it should exit the app.

The app version is 1.14.3

**Comment by jamie-mh** [comment]
Indeed, the back button should always return to the default category. Fixed in 17cd3b1.
