### ISSUE TITLE
Version code difference detected between F-droid install and play store

### ISSUE THREAD

**Issue by Porkepix** [jamie-mh/AuthenticatorPro#134]
**Describe the bug**
I installed Authenticator Pro from F-droid with Izzy's repo.
However, my phone also have the Aurora Store (https://gitlab.com/AuroraOSS/AuroraStore) to interact with the play store.

It always shows a new update is available, and the difference always is on the big number at the end of the version code: I have the one starting with `100`, and it offers one starting with `210`. I don't know if this is because there's a special flavor for the playstore version, or because of the different ARM archs versions (Izzy picks the ARMv7 one, so maybe the ARMv8 one have a different version code?), but it would be nice if something could be done so that it doesn't always tell there's an update to do.

See the screenshot: 
![Screenshot_20210208-153831](https://user-images.githubusercontent.com/709500/107240318-121d1a80-6a2a-11eb-80be-780f16eb11e7.png)

**Expected behavior**
As the version number is the same, it shouldn't say there's an update to do.

**Comment by jamie-mh** [comment]
The version on Google Play is distributed as an app bundle, so the version code remains the same for every architecture. The apk versions are assigned a prefix based on the architecture. The version codes are always going to be different unfortunately.

Can you try going into the Aurora Store Settings -> Filters and check Filter F-Droid apps, this should prevent it from checking for updates.

**Comment by Porkepix** [comment]
Well, I didn't turned it on but it seems it is on by default. So it's already checked, but do not hide Authenticator Pro update.

**Comment by jamie-mh** [comment]
Does blacklisting the app make any difference?

**Comment by Porkepix** [comment]
Blacklisting does the trick. However, it's not possible to have the same version code for both apks, armv7 and armv8?

**Comment by jamie-mh** [comment]
There isn't anything that can be changed here I'm afraid. I'll mark this as solved.
