### ISSUE TITLE
GUI bug:  Start screen is overlaid on the authentication list

### ISSUE THREAD

**Issue by Schokobecher** [jamie-mh/AuthenticatorPro#152]
**Describe the bug**
After adding a new Authenticator via the camera (other options untested), the authenticator list is overlaid with the start screen.

By start screen, I'm referring to the screen below:

> Nothing here!
![image](https://user-images.githubusercontent.com/1642634/108520677-85ae0a00-72fd-11eb-9e26-699c29c8d11f.png)

Sorry for the blurry screenshot, but since the screenshots are disabled/hidden I had to resort to unusual measures :sweat_smile: 

**To Reproduce**
1. Add Authenticator
2. Click on 'Scan a QR code'
3. Click 'Scan from camera"
4. Scan code
5. Get sent back to the authenticator list

**Expected behavior**
Return to the authenticator list without any overlay

**App Version**
v1.14.0

**Comment by jamie-mh** [comment]
Hi,

Is that version correct or did you mean 1.14.4? This was mentioned in #124 , but I assumed it was fixed in the latest version. At least I can no longer reproduce this on my device.

Thanks.

**Comment by Schokobecher** [comment]
The version according to the 'About' dialog is 1.14.0
On the changelogs of F-Droid and the Play Store, I see version 1.14.4, but no update is available to me at this point.

![image](https://user-images.githubusercontent.com/1642634/108591291-9496ca00-739a-11eb-8c8e-8b96855988ab.png)

**Comment by jamie-mh** [comment]
That's rather odd, you may need to uninstall - reinstall to get the latest update perhaps.

**Comment by jamie-mh** [comment]
Hi,

Have you tested the latest version and is the issue still present?

Thanks
