### ISSUE TITLE
Import Data from FreeOTP

### ISSUE THREAD

**Issue by peschie1967** [jamie-mh/AuthenticatorPro#153]
Until recently I used the FreeOTP app from F-Droid. But there is no encryption for backup. So I switched to AuthenticatorPro. The export - import seemed to work. I have compared the output of the codes. But now I noticed that the codes are not running synchronously. Don´t know if this is a bug, or I did something wrong.

**App Version**1.14.4

**Comment by jamie-mh** [comment]
Hi,

I don't quite understand what you mean by "not running synchronously". Are the codes invalid or do they appear earlier or later than the ones in FreeOTP?

**Comment by peschie1967** [comment]
Sorry, for my late answer. Its like you presumed. The problem is, that the new codes come to different times.

**Comment by carun** [comment]
Can we close this issue please?

**Comment by peschie1967** [comment]
Sorry, i am late. Yes close it. All runs fine.
