### ISSUE TITLE
Adding Cross Platform Support

### ISSUE THREAD

**Issue by mbeps** [jamie-mh/AuthenticatorPro#157]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Eg. I'm always frustrated when [...]

**Describe the solution you'd like**
Cross-platform support via the web can be added. The current implementation for backing up can be used for syncing. 

**Additional context**
The backup file will be automatically generated and uploaded into the cloud. Users can host it using services such as Google Drive, OneDrive, Dropbox, etc. The clients will check the drives for any recent backups.

**Comment by jamie-mh** [comment]
Your proposal is rather vague.

- If you mean adding support for other platforms see: #71 and #68 .
- If you mean adding first-party support for cloud providers see: #16
