### ISSUE TITLE
Wear OS starting bug

### ISSUE THREAD

**Issue by upD8R** [jamie-mh/AuthenticatorPro#158]
**Describe the bug**
Every time I open the Wear OS app on my TicWatch 3 I only see the the loading animation. Initially I thought it just needs to fetch data from the phone but it didn't stop. Even minutes later only the animation is shown. Phone is connected.
Now I discovered by accident I can swipe down and select a different category and immediately all the entries (of that category) are visible again. I can go back to show all entries and it works until I leave the app and come back, the same loading animation is shown again.
This worked before. To be fair - not sure if this was introduced by an app update or by H-MR2, which I recently received.

**To Reproduce**
See above.

**Expected behavior**
"real time" visibility of all entries (at least after initial fetching)

**App Version**
Wear OS: 2.3.1
Phone:  1.14.6

**Comment by jamie-mh** [comment]
Hi,

Since the entries appear after changing category, I'm guessing this is probably a ui bug. The progress bar is not disappearing when it should.

I haven't see this happen on my device, but I will investigate.

**Comment by upD8R** [comment]
Thanks, let me know if I can provide any additional logs or something ...

**Comment by upD8R** [comment]
Hey jamie,

it seems I found the cause. For whatever reason no layout was actually selected in the app. I use dark theme but in the app setting none of them (system, light, dark) was active. I set dark again and now also the Wear OS app behaves again as expected.

Hope this helps.

**Comment by jamie-mh** [comment]
Hi,

That seems a little strange, I don't see how to two things could be linked. Perhaps it's a coincidence?
Anyway, I've made some general improvements to the Wear OS code that should prevent strange behaviour like this from happening.

**Comment by upD8R** [comment]
Indeed, it sounds strange. But I tried on the watch, was upset again, looked through the settings in the phone app again, set a profile and immediately after that, it worked on the watch, too 😉

**Comment by upD8R** [comment]
And thanks for the support!

**Comment by euinor** [comment]
> Indeed, it sounds strange. But I tried on the watch, was upset again, looked through the settings in the phone app again, set a profile and immediately after that, it worked on the watch, too 😉

What did you do to get it working? It still doesn't work for me.

**Comment by upD8R** [comment]
> What did you do to get it working? It still doesn't work for me.
It's still not fully reliable for me. Basically, I did two thing to mitigate the occurrence:

At first I set a default entry to be shown on the watch (you do this by long pressing an entry).
If I still end up in the loading screen, I swipe down and select one of my sub categories. This will show up immediately and in most cases I can swipe down again and set it to show all entries again.

**Comment by euinor** [comment]
Thanks for your quick response!
Actually it turns out I was using an old version on my phone. I had directly installed the apk and it hadn't updated since. Uninstalling and reinstalling from the play store and I can now see my codes in the watch app.

**Comment by Ka4234** [comment]
ในวันที่ พ. 24 ก.พ. 2021 01:08 jmh ***@***.***> เขียนว่า:
