### ISSUE TITLE
Info about icons in Contribution Guide

### ISSUE THREAD

**Issue by kwiateusz** [jamie-mh/AuthenticatorPro#164]
Hi,

After making first merge request with new icons I get compilation error and I think that can be avoided by next contributors.

It would be a good idea to add to Contribution Guid info, for users that don't use Visual Studio, that icons should be added into AuthenticatorPro.Droid.Shared/AuthenticatorPro.Droid.Shared.csproj file too. People who use VS will do this automatically but rest doesn't.

I can make PR with that but firstly I wanted to ask if this isn't needless.

**Comment by jamie-mh** [comment]
I don't want this to be a barrier to people contributing new icons. Perhaps it should be an optional step for those who want to compile and test the project with the new icons.

**Comment by kwiateusz** [comment]
Sure it can be optional but without it someone like me may be suprised that PR is marked as failed

**Comment by jamie-mh** [comment]
I've altered the guide slightly. It should be clearer how to test the project now.
