### ISSUE TITLE
Wear OS - No Authenticators

### ISSUE THREAD

**Issue by euinor** [jamie-mh/AuthenticatorPro#169]
Hi, I installed the wear is companion app and it says I have no authenticators. Any ideas why?
I have four listed in the Authenticator Pro app.

I have tried force stopping and clearing data in the wear os app.

Edit: in case in makes any difference all my codes are imported, not created.

**Comment by jamie-mh** [comment]
This is probably related to #158 . I'm guessing the data is received but there is a display bug. I still need to investigate this.

**Comment by euinor** [comment]
The wear app works for me as of the latest version. Thanks!
