### ISSUE TITLE
icon requests

### ISSUE THREAD

**Issue by astarq** [jamie-mh/AuthenticatorPro#17]
Great app!

Would you consider adding the icons for: 
Bitwarden; https://play.google.com/store/apps/details?id=com.x8bit.bitwarden

Tutanota; https://play.google.com/store/apps/details?id=de.tutao.tutanota

Samsung (do I need to introduce this one?)

Icons rather than just names are a decent idea BTW, makes it a lot easier to find what I'm looking for.

**Comment by jamie-mh** [comment]
Thanks. I'll make sure they're part of the next release.

**Comment by astarq** [comment]
Thanks!
