### ISSUE TITLE
Wear OS app not connecting to phone app

### ISSUE THREAD

**Issue by jwr12135** [jamie-mh/AuthenticatorPro#192]
**Describe the bug**
I installed the Authenticator Pro app on my devices, and while my watch and phone are connected, the watch app will not sync my authentication keys. I even tried the QR code here: https://github.com/jamie-mh/AuthenticatorPro/issues/145#issuecomment-778645740, but that did not show up on my watch either.

**To Reproduce**

1. Install Authenticator Pro through F-Droid
2. Add token by scanning QR code
3. Test token to make sure it's working
4. Install Authenticator Pro wear os app on watch
5. Verify Bluetooth connection
6. Open watch app
7. App displays: "**No Authenticators**", "Nothing here. Add some authenticators from the phone app." With a "no connection" icon at the top of the screen, while connected through Bluetooth and wife

**Expected behavior**
I expect there to be a list of my authentication keys (or at least not have the "no connection" icon)

**App Version**
Phone (Fire HD 8 Gen 8): 1.14.7 from F-Droid
Watch (TicWatch E): 2.3.2 from Google Play Store

**Additional context**
Watch Screenshot:
![](https://user-images.githubusercontent.com/47087725/115796467-da264200-a39f-11eb-9d09-d35c73f584a8.png)

**Comment by jamie-mh** [comment]
Hi @jwr12135 ,

Unfortunately, the Google Play and F-Droid versions of the apps cannot be used together since the Google Play versions are signed with the Google key, hence why the connection is blocked by the OS. You can either install the phone app via Google Play or install a Wear OS apk directly.

**Comment by jwr12135** [comment]
I have side-loaded the wear OS apk to my watch, and now all my keys are showing up! Unfortunately Google Play on my phone says: "Your device isn't compatible with this version.", I'm guessing there isn't a way to fix this. Anyway, thanks for all of your help @jamie-mh.
