### ISSUE TITLE
Impossible to restore a backup

### ISSUE THREAD

**Issue by peschie1967** [jamie-mh/AuthenticatorPro#193]
I chanced my device. So I want to restore the backup of authenticatorpro. But if I want to choose it, the folder is empty. It seems, that the file has a wrong ending. The filenames are: backup-2021-03-10_142241.authpro What do I wrong?

**Comment by jamie-mh** [comment]
Hi,

The file extension is correct. All file opening is handled by the system file picker, so the folder is probably empty and not a bug.
What storage are you restoring from device or cloud provider?

**Comment by peschie1967** [comment]
I tried to restore from the device. Location  /storage/emulated/0/Authenticator/backup-2021-03-10_1234.authpro 
Now I tried to load the backup, not with mixplorer and it works! Thanks. I wonder, why this is so.
