### ISSUE TITLE
NVIDIA Icon

### ISSUE THREAD

**Issue by bonn2** [jamie-mh/AuthenticatorPro#194]
Please fill out the fields below where applicable:

**Name of website / service**
NVIDIA
**Link to high-quality icon**
[https://www.nvidia.partners/assets/images/nv_geforce_logo_new_egg.png](https://www.nvidia.partners/assets/images/nv_geforce_logo_new_egg.png)

**Comment by jamie-mh** [comment]
Thanks. I've added the icon.
