### ISSUE TITLE
Tile for Wear OS

### ISSUE THREAD

**Issue by simpleittools** [jamie-mh/AuthenticatorPro#200]
This application is fantastic on Wear OS, and is the reason I moved over to it.
One thing that would be helpful is if the application were able to load in a tile.  Right now, I have to load the application from the applications list. The ability to simply swipe over to the tile would be a huge benefit.

**Comment by icedvigilante** [comment]
Actually, killing this request. I just read through the Android Developer docs for tiles and I see a big flaw in my thoughts on the matter. The constant re-rendering would have a negative effect on the battery life of the Wear OS device.
