### ISSUE TITLE
Make restoring from backup easier

### ISSUE THREAD

**Issue by yoyosamo** [jamie-mh/AuthenticatorPro#203]
**Is your feature request related to a problem? Please describe.**
After my phone faced an untimely death, I went to restore my AuthenticatorPro backup and found this to be a quite confusing task. Forgive me if I missed something, but I found the Restore method not to be very obvious.

After downloading my Backup file from Dropbox, I had to go to Settings, Auto Backup and set the location and password, then hit Restore Now.

**Describe the solution you'd like**
Could a more simple single-use "Restore From Backup" option be added either on the launch screen, or within the "Import from other apps" menu?

If this is the intended method (through the Auto Backup menu), could this be documented on the Wiki here - for those, like me, who are frantically trying to restore their codes? I found it very confusing having to go into "Auto Backup" when I was actually trying to restore.

Thanks so much for your fantastic app, please let me know if I can be of any further assistance - I just hope to help avoid the stress I faced for anyone else in the future :smile:

**Comment by jamie-mh** [comment]
Hi @yoyosamo ,

I think what you're suggesting already exists. If you click the plus button and select "Restore a backup", you should be able to restore a backup directly from Dropbox. Does this not work on your end?

Thanks

**Comment by yoyosamo** [comment]
Ahh, yes that's exactly what I was looking for 🤦 and works great!
Think I just got distracted by the "Import from other apps" button and then went on a wild goose chase...

Thanks for the great app, and apologies for my silliness!

**Comment by Carlolius** [comment]
Hi, sorry to reopen.
I had the exact same problem as @yoyosamo and I had to came here to find the solution (not that fast). Might be a good idea to add this option to other menu or just document that you need to hit the plus button.
Thanks for your work! :smiley:
