### ISSUE TITLE
WearOS

### ISSUE THREAD

**Issue by Pukkahq** [jamie-mh/AuthenticatorPro#21]
When you leave the app and go back to the main watch face and then access the AuthenticatorPro app again you just get a blue bar scrolling on the display.  

Does the watch work in stand alone mode or does it check with the app on the phone each time it loads?

**Comment by jamie-mh** [comment]
Hi @Pukkahq ,

This is by design. The watch app is merely a client that uses the data stored on the phone.
When the app opens, it contacts the phone and requests a list of all authenticators. Nothing is stored on the watch.

I hope this answers your question.

**Comment by Pukkahq** [comment]
Are they any plans to allow the watch to work on it own? maybe a sync button on the phone.

**Comment by jamie-mh** [comment]
No, not currently. It seems like a lot more work than the current solution; the final result might not be very different.

Besides, I'm personally not a huge fan of generating codes on the watch itself, as this would require transmitting and storing secret keys on the watch. Which is not ideal.

**Comment by Pukkahq** [comment]
that makes sense :)
