### ISSUE TITLE
Possibility to change Accent Color

### ISSUE THREAD

**Issue by alalloush** [jamie-mh/AuthenticatorPro#210]
**Is your feature request related to a problem? Please describe.**
No problem, but it would be nice to change the accent color from the default blue.

**Describe the solution you'd like**
A color picker for accent colors in the settings.

**Additional context**
Eg. view like this 
![vivaldi_P3pVQADlyX](https://user-images.githubusercontent.com/54959118/119487409-a1400b00-bd59-11eb-8edc-001f4b21e5c5.png)

**Comment by luximus-hunter** [comment]
👍🏼

**Comment by kwiateusz** [comment]
It can be closed. Option to change accent color is present in 1.14.10
