### ISSUE TITLE
Add Arabic Language

### ISSUE THREAD

**Issue by alalloush** [jamie-mh/AuthenticatorPro#211]
**Is your feature request related to a problem? Please describe.**
No current Arabic support

**Describe the solution you'd like**
Add Arabic support via Crowdin/Strings file.

**Additional context**
A friend and I can translate all strings into Arabic, but I'm unsure if they'll be any issues with right-to-left languages.

**Comment by jamie-mh** [comment]
Hi,

I've made the necessary changes to the app layout in order to support RTL text. Also, I've added Arabic to the list of languages on Crowdin so you should have access now.
