### ISSUE TITLE
TOTP token is not refreshed immediately for tokens with a period other than 30 seconds

### ISSUE THREAD

**Issue by wdhongtw** [jamie-mh/AuthenticatorPro#214]
**Describe the bug**

For TOTP token which has refresh period other than 30 seconds, the token is not refreshed immediately when change to next time slot.

**To Reproduce**

1. Add new TOTP (Enter a provided key)
2. For advanced options, set period to 10 seconds

**Expected behavior**

When the progress bar is empty (every 10 seconds), the TOTP code should be refreshed.

**App Version**

Version: 1.14.9

**Additional context**

This issue slightly impacts the UX of login flow of Twitch service. Although Twitch force user to use proprietary OTP application (Authy).

**Comment by jamie-mh** [comment]
Hi,

Is this still reproducable in the latest version (1.14.10)?

Thanks

**Comment by wdhongtw** [comment]
Hi @jamie-mh, it woks well now. Thanks for your great work. :D
