### ISSUE TITLE
[Feature] Option to hide codes and reveal them when tapped

### ISSUE THREAD

**Issue by Redsandro** [jamie-mh/AuthenticatorPro#216]
**Is your feature request related to a problem? Please describe.**

In _tile mode_ you have 14 codes on your screen at the same time. There are many camera's everywhere. I don't feel at ease displaying all the codes to cameras or people behind me, even if they are only valid for a minute or so.

**Describe the solution you'd like**

Hide all the codes with asterisks or big dots, and only show _one_ code once it is tapped. Hide it again when the timer expires. If needed, the user can tap on it again.

**Additional context**

Aegis Authenticator has a similar feature/option called _Tap to reveal:_ 'Tokens will be hidden by default. Tap on the tokens to reveal code.'

**Comment by luximus-hunter** [comment]
+1 on this feature

**Comment by kwiateusz** [comment]
It can be closed. Option to hide codes is present in 1.14.10

**Comment by Redsandro** [comment]
Confirmed. Thank you. :+1:  

Main menu > Settings > Security > Tap to reveal

Personally I don't like the `--- ---` dashes. It looks weird when there are dozens of them. Is there a reason this was chosen over more common defaults? 

If there is no particular reason, I prefer the more modern center circles: `●●● ●●●`. Or even old-school asterisks: `*** ***`

But confirmed nonetheless, so closing. :+1:

**Comment by jamie-mh** [comment]
The code font is variable width, so the code changes size when revealed. I chose dashes because the size difference during the reveal was the least noticable.
