### ISSUE TITLE
Dutch translations

### ISSUE THREAD

**Issue by luximus-hunter** [jamie-mh/AuthenticatorPro#219]
**Is your feature request related to a problem? Please describe.**
Missing translations for Dutch

**Describe the solution you'd like**
Dutch translations :D

**Additional context**
The app is missing Dutch translations, and as a native speaker and lover of your app, I'd love to contribute! Just let me know if you want me to translate, and I'll get to work

**Comment by jamie-mh** [comment]
Hi,

I've added Dutch as a language option on Crowdin. Follow the link in the [contribution guide](https://github.com/jamie-mh/AuthenticatorPro/blob/master/CONTRIBUTING.md#translations) to join the project.

**Comment by luximus-hunter** [comment]
Yessir!
