### ISSUE TITLE
Backup to Cloud Storage?

### ISSUE THREAD

**Issue by DanHakimi** [jamie-mh/AuthenticatorPro#221]
I don't see any option to backup to cloud storage. The backup option only seems to allow for local backups.

**Comment by luximus-hunter** [comment]
That's correct. Authenticator Pro works fully offline.

**Comment by jamie-mh** [comment]
I assume you're talking about the auto-backup feature. Here's the FAQ entry:

> Why doesn't Google Drive, OneDrive, Dropbox, etc... appear in the auto-backup storage location list?

> The dialog you see when you select a storage location is not part of Authenticator Pro but rather part of Android. The Storage Access Framework as it is named, receives varying levels of support from cloud providers. If the provider of your choice does not appear, then this is a limitation of their app.

> Fully supporting it is possible (Nextcloud for instance), but this may not be a high priority for the developers. A way around this would be to backup to a folder on your device and then use a 3rd party to sync the contents of that to cloud storage. First party support for cloud services will not be implemented, see above.
