### ISSUE TITLE
[Feature] Favicon download option to fetch icons

### ISSUE THREAD

**Issue by tmrizzo** [jamie-mh/AuthenticatorPro#223]
**Summary**
Add an option to fetch the `favicons` (`favicon.ico`) from the website as an alternative to adding icons to the Authenticator Pro.

**Steps**
1. Click the drop-down arrow to edit an already existing OTP key.
2. Select `Change icon`
3. Click `Use custom icon`:
    1. Show a list to choose `Local storage` and `Fetch favicon`
    2. Click `Fetch favicon` to add the URL of the site.

**Additional info**
Some challenges that come to mind:
1. General public may not understand what a `favicon` is.
2. Parsing the address to get `favicon`:
    1. Directly download `example.org/favicon.ico`, or
    2. URI pointed to a `"shortcut icon"` `<link>` tag, i.e explicitly search for `<link rel="shortcut icon" …` and/or with `rel: icon` tag to download the icon.

KeepassXC has a similar implementation of this feature in the desktop version but, I've not tested if the same thing works in the mobile app. It seems that the URL field used to add a password is also used to try fetching the `favicon` icon.

**Comment by jamie-mh** [comment]
Hi @tmrizzo ,

Thanks for your detailed feature request. However, this would require the Internet permission to implement, which is really something I'd like to avoid if possible. Sorry!
