### ISSUE TITLE
Restore from App Data partition Using Root

### ISSUE THREAD

**Issue by archit9169** [jamie-mh/AuthenticatorPro#225]
Hi, a really stupid issue. But my mobile got reset because of a failed update and I lost my data. Fortunately I was able to enter recovery and did manage to backup the /data/data/me.jamie-mh.authenticatorpro folder, so atleast I have that. Now the question of the year, can I restore this data backup? Simpy pasting it did not work. Any helpwould be appretiated.

**Comment by jamie-mh** [comment]
Hi @archit9169 ,

I've tested copying just the `files/proauth.db3` and `shared_prefs/me.jmh.authenticatorpro_preferences.xml` files to a clean install and that seems to work.

Alternatively, you can open the database file `files/proauth.db3` with [DB Browser for SQLite](https://sqlitebrowser.org/), using SQLCipher 3 mode if you have a password on it. The `authenticator` table will have all of your secret keys in it, you will need to enter them in manually however.

**Comment by archit9169** [comment]
Thanks. It worked. By the way I noticed that we need to enter a seperate password for automatic backup and restore. Shouldn't a single password suffice when manual backup and vault are using a single password too?

Closing this isse now. By the way can you add this to wiki or something so others who may have similar issues are informed that there may be a way to recover incase of rom issues.
