### ISSUE TITLE
Help Getting a Code...

### ISSUE THREAD

**Issue by Amrae** [jamie-mh/AuthenticatorPro#226]
I used to use AuthenticatorPro to back up my facebook account. I turned that off and deleted the AuthenticatorPro app because I just never seemed to need it. Then I got a new phone and now facebook says i still need the 6 digit code from this app. I redownloaded the app but it doesnt have any of my info still stored in it. Is there anyway you can help me access the code I need from this app? Or is it gone for good?

**Comment by jamie-mh** [comment]
Uninstalling the app will delete all data permanently. Without a backup, your only option is to contact Facebook support to disable 2FA on your account.
