### ISSUE TITLE
App immediately retreats the the background after fingerprint unlock

### ISSUE THREAD

**Issue by arcasinky** [jamie-mh/AuthenticatorPro#227]
**Describe the bug**
Upon unlocking the app with fingerprint, I'm immediately returned to the phone's home screen.  App continues to run in the background so I need to swipe up and bring the app to the foreground in order to access the TOTP codes.  This is fairly recent behavior...within the last couple or three weeks.

**To Reproduce**
1. Unlock the app with your fingerprint
Result: I'm taken back to my phone's home screen

**Expected behavior**
This is relatively new behavior.  Previously, the app would remain in the foreground after fingerprint unlock.  It's entirely possible that I've inadvertently changed an Android system setting that's causing this; however other apps that use fingerprint unlock don't exhibit this behavior.

**App Version**
1.14.10

**Additional context**
Pixel 3XL running Android 11 with the 06/2021 security patches

**Comment by jamie-mh** [comment]
Hi @arcasinky ,

I'm not able to reproduce this on my end and none of the unlock code has changed recently. Are you able to attach a log to the issue, if it contains anything that might narrow down the bug?

Thanks.

**Comment by arcasinky** [comment]
Hi.  Sorry for the late response.  At the risk of sounding dumb, how might I generate such a log file?

**Comment by jamie-mh** [comment]
Don't worry, it's not exactly trivial. Here's a guide on [capturing debug output from apps using logcat](https://www.xda-developers.com/how-to-take-logs-in-android/). The idea is to reproduce the issue and check for any errors in the log.

**Comment by jamie-mh** [comment]
Any update? Thanks.

**Comment by jamie-mh** [comment]
Hi,

To anyone experiencing this issue, attached is a test version of the app (different package name will not overwrite existing install). The issue may or may not be fixed. If you're able to test it, please let me know if the issue is present. Thanks.

[me.jmh.authenticatorpro.dev-arm64-v8a-Signed.zip](https://github.com/jamie-mh/AuthenticatorPro/files/7313322/me.jmh.authenticatorpro.dev-arm64-v8a-Signed.zip)

**Comment by jamie-mh** [comment]
Hi,

Attached is another dev version with some changes that may solve the issue. If anyone experiencing this issue can test it out, your help would be much appreciated. As always, it has a different package name, so won't overwrite an existing install. Please let me know if this solves the issue.

Thanks

[me.jmh.authenticatorpro.dev-arm64-v8a-Signed.zip](https://github.com/jamie-mh/AuthenticatorPro/files/7570887/me.jmh.authenticatorpro.dev-arm64-v8a-Signed.zip)

**Comment by jamie-mh** [comment]
Moved to #254
