### ISSUE TITLE
Suggestion: Ability to Copy Codes

### ISSUE THREAD

**Issue by samfriedmann** [jamie-mh/AuthenticatorPro#23]
Google Authenticator allows users to copy a code by long pressing it, in addition to rearranging that code. As these codes are only valid for such a short period of time, I don't see this as a major security concern (and, clearly, neither does Google). Would it be possible to implement such a feature to AuthenticatorPro in a non-intrusive and hopefully not-a-ton-of-work way? Thanks.

**Comment by jamie-mh** [comment]
Hi @samfriedmann ,

Have you tried a short tap on the code? This should copy it to the clipboard.
Let me know if this works for you.

**Comment by samfriedmann** [comment]
Wow, didn't even try that. Works like a charm! Perhaps some sort of in-app education like a splash screen or something so we know about that functionality (or maybe there was something and I didn't even notice). Thanks for the response.

**Comment by jamie-mh** [comment]
No worries. You're right, I will add a page in the app intro screen to teach users about all the features.
