### ISSUE TITLE
2FA and Password manager in a single app.

### ISSUE THREAD

**Issue by EuriNaiz** [jamie-mh/AuthenticatorPro#233]
I have some months using  [Authenticator Pro](https://github.com/jamie-mh/AuthenticatorPro) to auth my sessions, and I hadn't got any problem, even, the app is improving more each day, but there's not a feature that I consider necesary, the posibility to Keep Passwords, a pasword manager inside 2FA authenticator app, like Bitwarden does.

Right now I'm using bitwarden to manage my passwords, and recently I found a new App called [KeyPass](https://github.com/yogeshpaliyal/KeyPass) with a similar design, and it is released under the MIT license (it is libre) and written in Kotlin Lang, so, I suggest to merge both apps ([KeyPass](https://github.com/yogeshpaliyal/KeyPass) and [Authenticator Pro](https://github.com/jamie-mh/AuthenticatorPro)) into new one, joining efforts you can do more and better things.

I am not Python or Kotling programmer, but I suppose it is possible to do something. I am not the author of [KeyPass](https://github.com/yogeshpaliyal/KeyPass) too, but I gonna open a new issue sugesting the same, hoping some reply or consideration of the proposal. 

I haven't got money, and I don't know program C#, Python or Korlin (as i said before), but I can collaborate with Spanish translations, trying and using the betas before to release and giving periodical feedback, really, I want to help to improve the apps and experience.
Please, consider my suggestion.

[Here's the issue with the suggestion on KeyPass repository.](https://github.com/yogeshpaliyal/KeyPass/issues/16#issue-941602444)

**Comment by jamie-mh** [comment]
Hi,

First of all, sorry but I don't want to add password management to Authenticator Pro as that opens a can of worms such as porting the app to more platforms, auto filling, etc... And that's not really the focus of the app in the first place. Also, there isn't an incentive for me to do this, as I don't make any money off this project.

Furthermore, you've linked to another application, which, despite a slight visual similarity is rather quite different, so it wouldn't be possible to "merge" these apps. The password management code would need to be rewritten from the ground up.

Anyway, I personally use Bitwarden for my passwords, but I keep all of my 2FA codes in Authenticator Pro. For security reasons passwords and 2FA should be kept separate in my opinion.

Thanks.
