### ISSUE TITLE
I have to enter a password three times to access the app

### ISSUE THREAD

**Issue by jharrison03** [jamie-mh/AuthenticatorPro#235]
**Describe the bug**
I have to enter my password exactly three times to access the app.  This was not so in the previous version.  I suspect the app is actually crashing on the first two password entries and is transparently restarting.

**To Reproduce**
Enable a database password in Authenticator Pro 1.14.10 and re-start the app.

**Expected behavior**
The app should be available after one successful entry of the password.

**App Version**
1.14.10, Android 9, Motorola E6

**Additional context**
This didn't happen prior to the update to 1.14.10 (not sure exactly what version of the app I had installed prior),  I'm not mistyping my password exactly three times, every time I start the app.

**Comment by jamie-mh** [comment]
Sounds identical to #227 . If you could provide a log that would be great.

**Comment by jamie-mh** [comment]
Any update? Thanks.

**Comment by jamie-mh** [comment]
Hi,

Attached is another dev version with some changes that may solve the issue. If anyone experiencing this issue can test it out, your help would be much appreciated. As always, it has a different package name, so won't overwrite an existing install. Please let me know if this solves the issue.

Thanks

[me.jmh.authenticatorpro.dev-arm64-v8a-Signed.zip](https://github.com/jamie-mh/AuthenticatorPro/files/7570887/me.jmh.authenticatorpro.dev-arm64-v8a-Signed.zip)

**Comment by jamie-mh** [comment]
Moved to #254
