### ISSUE TITLE
Icon Requests (Quite a few)

### ISSUE THREAD

**Issue by SpasilliumNexus** [jamie-mh/AuthenticatorPro#24]
Hello. I have a few icons to request that aren't in Authenticator Pro (v1.8.2 as of this submission):

[Adafruit](https://cdn-learn.adafruit.com/guides/images/000/000/603/medium500/Logo.gif)

[AdGuard](https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/AdGuard.svg/1200px-AdGuard.svg.png)

[Etsy](https://upload.wikimedia.org/wikipedia/commons/a/aa/Etsy_logo_lg_rgb.png)

[Newegg](https://www.frugalbuzz.com/wp-content/uploads/2018/11/Newegg-Logo-1200x1200.jpg)

[Privacy](https://lh3.googleusercontent.com/xcIH2rg95sUMnhLZiQmMMuuj-GL2VuKtDjfmbvGbf5ODUCTob2DyxOoc_ZRCp9s96w=s1000-rw)

[RealVNC](https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/41/e2/69/41e269fa-7bd1-ad56-0050-d4c39969b8cd/mzl.poszceln.jpg/1200x630bb.jpg) or [Alternative](https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/RealVNC_logo.svg/1200px-RealVNC_logo.svg.png)

[Uphold](https://s3-eu-west-1.amazonaws.com/tpd/logos/567f276c0000ff000586ff46/0x0.png)

Thank you very much in advance, and thank you for making such a beautiful authenticator with WearOS support!

**Comment by jamie-mh** [comment]
Thanks for the icon request. Added in 618a024.
