### ISSUE TITLE
Icon Requests

### ISSUE THREAD

**Issue by MalteKiefer** [jamie-mh/AuthenticatorPro#249]
Hello,

cloud you please add the following icons:

- [ ]  [Arena.net](https://www.arena.net)
- [ ]  [Bitpanda](https://bitpanda.com)
- [ ]  [Codeberg](https://www.codeberg.org/)
- [ ]  [Genesis Mining](https://genesis-mining.com)
- [ ]  [Internxt](https://intertxt.com)
- [ ]  [IQMining](https://iqmining.com)
- [ ]  [Docker Hub](https://hub.docker.com/)
- [ ]  [Servercow](https://www.servercow.de/)
- [ ]  [Transcrypt](https://transcrypt.eu)

**Comment by jamie-mh** [comment]
I've added icons for Arena.net, Bitpanda and Codeberg. There is already a Docker icon. I'm not able to find sufficiently high quality icons for the others.

**Comment by MalteKiefer** [comment]
Which format and size do you need?
