### ISSUE TITLE
Restore the Blizzard Icon

### ISSUE THREAD

**Issue by bliau03** [jamie-mh/AuthenticatorPro#25]
I just updated to the newest version but I can't seem to find the Blizzard icon in this version. I looked through the changelog and it seems to have been removed. If it's possible, please add it back :)

**Comment by jamie-mh** [comment]
Hi @bliau03 ,

My mistake, I was going to rename the icon from "battlenet" to "blizzard" but I was unsure if it was still used as they have their own proprietary authenticator. But no problem, I've just added a better higher quality icon.
