### ISSUE TITLE
Set catagory shown on start 

### ISSUE THREAD

**Issue by SliX185** [jamie-mh/AuthenticatorPro#251]
I would found it nice, if there's an option to set the category wich will show up on start.

So you would have the option to "declutter" the list for only show the everyday used ones.

Or is there already some kind of workaround for that issue?

**Comment by jamie-mh** [comment]
Yes, you can set a default category in the 'Manage Categories' menu.

**Comment by SliX185** [comment]
Omg, Thanks so much and sorry for opening an issue for my stupidity.

**Comment by jamie-mh** [comment]
No worries
