### ISSUE TITLE
App won't unlock with fingerprint when opened

### ISSUE THREAD

**Issue by itspuia** [jamie-mh/AuthenticatorPro#254]
Hi there
I have been using this App for a couple of months and everything works perfectly. Especially the WearOS App is the reason I chose this Authenticator. Unfortunately for about one or two months (I guess since the last update) the app won't start as usual. When I open it, it shows me the "Scan your finger" window as usual, but it closes immediately and I need to type in my password instead. When I press on "Use biometry" it shows up again and it scans my finger well. It does not show me my OTP tho, it is just an empty app with the Authenticator Pro Icon.
If I go back to my Android home screen and open it up again, it finally opens up unlocked and it works fine.
So everytime instead of 1) open app 2) scan fingerprint 
I have to 1) open App 2) Press "use biometry" 3) scan fingerprint 4) let it load an empty screen 5) close app 6) open app again.

Here's a video on how it looks.
At the end when the screen is black, it shows the passwords as usual.
https://i.imgur.com/lbMK6M5.mp4

**Expected behavior**
I should be able to use the fingerprint sensor immediately and unlock my OTPs

**App Version**
1.14.10

**Additional context**
Huawei P10
VTR-L09
Build 9.1.0.275
Android 9, EMUI 9.1.0

**Comment by jamie-mh** [comment]
Hi,

Sounds like #227 and #235, but I'm not getting any answers there. A few questions to help diagnose the issue:

- Does disabling and re enabling Biometric Unlock make a difference?
- Does the issue persist after reinstalling the app (after backing up of course)?
- Are there any errors logged by the app when unlocking?

Thanks

**Comment by handokota** [comment]
Hi, I will answer some questions
- Does disabling and re enabling Biometric Unlock make a difference? Nothing.

- Does the issue persist after reinstalling the app (after backing up of course)? Yes.

- Are there any errors logged by the app when unlocking? No, the app just immediately retreats the background after fingerprint unlock.

I currently go back to 1.14.9 and the app work as well.

**Comment by jamie-mh** [comment]
Hi,

This is strange since the unlock code hasn't really changed between 1.14.9 and 1.14.10. Does this only happen with fingerprint or does it happen with the password too?

Thanks

**Comment by handokota** [comment]
Only fingerprint are affected

**Comment by l-marchesi** [comment]
Hi
I have a similar behaviour that might help resolve the problem here:
On an older phone of mine I have to unlock with my fingerprint twice to unlock the app. It immediately asks again after the first unlock. This happens on a Sony Xperia Z5 Compact with Android 7.1.1.
On my new phone (Sony Xperia 1 II, Android 11) this issue does not exist.

I do have developer tools ready, let me know if you would like a log of my older phone.

**Comment by jamie-mh** [comment]
Hi,

To anyone experiencing this issue, attached is a test version of the app (different package name will not overwrite existing install). The issue may or may not be fixed. If you're able to test it, please let me know if the issue is present. Thanks.

[me.jmh.authenticatorpro.dev-arm64-v8a-Signed.zip](https://github.com/jamie-mh/AuthenticatorPro/files/7313322/me.jmh.authenticatorpro.dev-arm64-v8a-Signed.zip)

**Comment by jamie-mh** [comment]
Thanks for your detailed feedback.
Does the issue persist if the timeout is set to 10 minutes? Perhaps the issue may be related to the auto-locking of the database.

**Comment by jamie-mh** [comment]
Hi,

Attached is another dev version with some changes that may solve the issue. If anyone experiencing this issue can test it out, your help would be much appreciated. As always, it has a different package name, so won't overwrite an existing install. Please let me know if this solves the issue.

Thanks

[me.jmh.authenticatorpro.dev-arm64-v8a-Signed.zip](https://github.com/jamie-mh/AuthenticatorPro/files/7570887/me.jmh.authenticatorpro.dev-arm64-v8a-Signed.zip)

**Comment by itspuia** [comment]
Hi,
I've just installed this Version and it seems to work perfectly! Thanks a lot!

**Comment by Hundhausen** [comment]
Can confirm. Unlocking now works at the first try.

**Comment by l-marchesi** [comment]
New update from the PlayStore seems to have fixed the issue for me as well :)

**Comment by jamie-mh** [comment]
Ok great. Thanks for the feedback everyone.
