### ISSUE TITLE
Hi how to use the recovery code  link plz 

### ISSUE THREAD

**Issue by clddev** [jamie-mh/AuthenticatorPro#255]
How to use the recovery code what's the link website

**Comment by jamie-mh** [comment]
Authenticator Pro doesn't use recovery codes

**Comment by clddev** [comment]
This is a open source project plz add recovery function if it doesn't provide it or add 1 time password function cz it's important for users I go for 1 time password function

**Comment by luximus-hunter** [comment]
A: what does an open source project have to do with needing a recovery code?
B: it's said in the readme, more than once, to make backups. If you have one, you can decrypt it. Of not, your codes are gone. No one can get them back

**Comment by jamie-mh** [comment]
I receive many emails from people who've forgotten their password or want me to disable 2FA on their accounts. The fact of the matter is that I have no control over anyone's data, it's encrypted on the device and not synced or connected to the Internet in any way. Backups are important.

Indeed as @luximus-hunter said, the only way to recover encrypted data is to decrypt it with the password. Resetting a password is simply not possible.
