### ISSUE TITLE
Filemanager not found

### ISSUE THREAD

**Issue by samex** [jamie-mh/AuthenticatorPro#260]
Hey, any file actions (import & export) on that app causing error message : Filemanager not found, you should install first. 

App Version 1.14.10
OnePlus Nord 12, Android 11

I have 2 filemanager installed, all other apps working fine with file management. What I do wrong? What can I try? I checked already the default app settings

**Comment by jamie-mh** [comment]
Have you disabled the system file manager?

**Comment by tdiekel** [comment]
I've got the same problem on a Oneplus 8 Pro with Android 11 and app version 1.15.8. I'm not sure which one the system file manager is. I've currently installed the following
- [com.oneplus.filemanager](https://play.google.com/store/apps/details?id=com.oneplus.filemanager) Version 2.6.4.1.210721121901.e308cc0
- [nextapp.fx](https://play.google.com/store/apps/details?id=nextapp.fx) Version 8.0.3.0
- [com.google.android.apps.nbu.files](https://play.google.com/store/apps/details?id=com.google.android.apps.nbu.files) Version 1.0.421968649

**Comment by tdiekel** [comment]
I removed `com.google.android.documentsui` with [W1nst0n/universal-android-debloater](https://gitlab.com/W1nst0n/universal-android-debloater) and apparently no other app supports the necessary android intent. After restoring it everything works.
