### ISSUE TITLE
App doesn't obey notched screen on Pixel phones

### ISSUE THREAD

**Issue by TheGorf** [jamie-mh/AuthenticatorPro#263]
I wanted to scope this to the PIxel phone as that is all I have tested the app on.  This is a design bug at most. I have a lot of TOTP codes and the problem is that the app scrolls up under the notch and over the notification bar at the top. I tried to take a screenshot of it, but couldn't.  I was going to take a peek at the code and see if bar height could be integrated and try to make a pull request.

For reference, I think all that's missing is what is called out here:
https://stackoverflow.com/questions/52514075/how-to-detect-if-device-support-notch-display/53593067

**Comment by TheGorf** [comment]
Yep that's what I'm seeing. If it's by design, that's fine. It would be nice to have the option to set the app to letterbox the cutout. Assuming the default now is LAYOUT_IN_DISPLAY_CUTOUT_MODE_DEFAULT.

**Comment by jamie-mh** [comment]
This doesn't have anything to do with the notch actually, the app never even checks if there is one. It seems what you want is an option to disable the transparent status bar. Without a transparent status bar the area to the sides of the notch would be opaque and the list would appear below it.
I'll look into this when I have time.

**Comment by jamie-mh** [comment]
1.15.0 now has an option to disable the transparent status bar
