### ISSUE TITLE
Reuse icons from aegis-icons?

### ISSUE THREAD

**Issue by Daniel15** [jamie-mh/AuthenticatorPro#268]
There's a pretty comprehensive set of icons for Aegis, available primarily in SVG format (https://github.com/aegis-icons/aegis-icons/tree/master/SVG) but they do have some older ones in PNG format too.

There's some icons available there that are missing from Authenticator Pro. Could you please consider just reusing all those icons? They're licensed under the CC0 1.0 Universal Public Domain which means they're not copyrighted and everyone has full rights to use them: https://creativecommons.org/publicdomain/zero/1.0/.

**Comment by jamie-mh** [comment]
The icons don't match any of the existing icons. They're part of a set and would look rather out of place in the app.
I don't think they should be included.
