### ISSUE TITLE
Support SVG icons

### ISSUE THREAD

**Issue by Daniel15** [jamie-mh/AuthenticatorPro#269]
**Is your feature request related to a problem? Please describe.**
SVGs are smaller than PNG files, and infinitely scalable (since they're vector images). Please add support for using SVG icons.

**Describe the solution you'd like**
SVG icons should be supported. Currently I can't pick one.

**Comment by jamie-mh** [comment]
I've looked into SVG icons before and I've concluded that it's simply not worth the effort.
SVG support on Android sucks and I don't want to introduce another dependency just to handle them.
