### ISSUE TITLE
OTP auth list messes up query parameters

### ISSUE THREAD

**Issue by NotNite** [jamie-mh/AuthenticatorPro#271]
Hi! I was trying to import some codes I had, and I wrote a quick script to make otpauth URIs. Maybe I'm just doing it wrong, but it outputs the following:

`otpauth://totp/My%20TOTP%20Code?secret=blah&issuer=My+TOTP+Code`

The entry name is supposed to be "My TOTP Code". The app parses the issuer directly as `My+TOTP+Code`, however, directly ignoring the plus signs. I could just fix this by editing the entry manually, but that's not favorable.

**Comment by jamie-mh** [comment]
Hi,

According to the spec: [https://github.com/google/google-authenticator/wiki/Key-Uri-Format#issuer](https://github.com/google/google-authenticator/wiki/Key-Uri-Format#issuer), you should use %20 for spaces in the issuer field.

Your URI should look like this:
`otpauth://totp/My%20TOTP%20Code?secret=blah&issuer=My%20TOTP%20Code`

The app will then correctly recognise the spaces.
