### ISSUE TITLE
Export auth tokens from wear os device

### ISSUE THREAD

**Issue by ZenithRogue** [jamie-mh/AuthenticatorPro#278]
**Describe the solution you'd like**
A way of exporting auth tokens from a wear os device, probably in the form of a series of QR codes, or potentially through USB debugging.

**Additional context**
My phone suffered water damage, and is unable to be repaired.  Unfortunately I do not have any repository where I have backed these tokens up, and they are currently only available on my smartwatch.  I am hoping there is some way I can recover these codes, without having to regenerate all of these codes manually.

**Comment by jamie-mh** [comment]
It sounds like it would be a mild inconvenience to reset your accounts since you still have access to them.
Next time you should make a backup, it will save you the trouble.

**Comment by ZenithRogue** [comment]
Yeah, I luckily I found an old backup of most of them. I did have to reset a handful of them though.
