### ISSUE TITLE
I have to enter the PW 2 times every time I want to open the app.

### ISSUE THREAD

**Issue by kcb3** [jamie-mh/AuthenticatorPro#285]
Stock Galaxy S7 phone.

Must enter the PW 2 times.  I just installed recently and it didn't do this at first, but now, no matter what I change in the settings, it still requires the PW twice.

Love the app, but this is a bit annoying and forces me to reduce my security by making an easy PW.

Thanks for the app,
Casey

**Comment by jamie-mh** [comment]
Sounds identical to #254, #235 and #227.
What version of the app are you using? Thanks.

**Comment by kcb3** [comment]
Very strange, I just logged in to take this screenshot and I only put my PW in once. &nbsp;So I reset everything and tried it again and it was twice again.---------- Original Message ----------On Mon, October 4, 2021 at 1:26 PM, ***@***.***&gt; wrote:&nbsp;&nbsp;Sounds identical to #254, #235 and #227.What version of the app are you using? Thanks.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.&nbsp;&nbsp;

**Comment by jamie-mh** [comment]
Hi,

To anyone experiencing this issue, attached is a test version of the app (different package name will not overwrite existing install). The issue may or may not be fixed. If you're able to test it, please let me know if the issue is present. Thanks.

[me.jmh.authenticatorpro.dev-arm64-v8a-Signed.zip](https://github.com/jamie-mh/AuthenticatorPro/files/7313322/me.jmh.authenticatorpro.dev-arm64-v8a-Signed.zip)

**Comment by jamie-mh** [comment]
Hi,

Attached is another dev version with some changes that may solve the issue. If anyone experiencing this issue can test it out, your help would be much appreciated. As always, it has a different package name, so won't overwrite an existing install. Please let me know if this solves the issue.

Thanks

[me.jmh.authenticatorpro.dev-arm64-v8a-Signed.zip](https://github.com/jamie-mh/AuthenticatorPro/files/7570887/me.jmh.authenticatorpro.dev-arm64-v8a-Signed.zip)

**Comment by jamie-mh** [comment]
Moved to #254
