### ISSUE TITLE
Feature request: Allow changing digit grouping of codes

### ISSUE THREAD

**Issue by l-marchesi** [jamie-mh/AuthenticatorPro#289]
**Is your feature request related to a problem? Please describe.**
In some languages it is much easier to read number blocks that are shown in the format 3 by 2, e. g. 12 34 56 instead of 2 by 3, e. g. 123 456.

**Describe the solution you'd like**
I'd like to see an option within the settings to toggle the code grouping style.

**Additional context**
![image](https://user-images.githubusercontent.com/17783632/136703341-4b4160f2-c744-4149-a29a-ff8f3c305f7c.png)

**Comment by l-marchesi** [comment]
Thank you for implementing my request - I will make sure to translate it into german over on Crowdin.

In german we have to rule to write out the numbers 1 to 12 (e.g. one, two, three, ...). Do you wish that I follow this rule?

**Comment by l-marchesi** [comment]
I translated the remaining missing translations and this issue can be closed. Thanks again!

**Comment by jamie-mh** [comment]
> In german we have to rule to write out the numbers 1 to 12 (e.g. one, two, three, ...). Do you wish that I follow this rule?

Thanks for letting me know. I've updated the translation to fix this.

**Comment by l-marchesi** [comment]
You're welcome - I will update the translation.
Maybe it might be worth to rename it clearer. I'm thinking of something like "2 by 3" or "2 x 3".

**Comment by jamie-mh** [comment]
That might be clearer but it assumes that all codes are 6 digits long, Battle.net codes are 9 digits for example.

**Comment by l-marchesi** [comment]
I see, didn't know that.
Maybe "groups of two" / "groups of three" / "groups of four".
Also possible "blocks of two digit numbers" - but this one sounds too complicated in my opinion
