### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by Schokobecher** [jamie-mh/AuthenticatorPro#29]
Some services/companies rely on special characters.
The README states `with spaces and special characters removed.` which can result in ambiguous naming down the line 

Examples would be:
- Name.com
- GMX.net (vs. GMX.com which doesn't support 2FA)
- mail.de (vs. mail.com/mail.ru (Only mail.de uses TOTP)
- Yahoo (no 2FA via TOTP) vs. Yahoo Japan Mail (2FA via TOTP)

What is the correct way to distinguish these services and their related icons?

`namecom` or `name` or `namedotcom`
`gmxnet` or `gmx` or `gmxdotnet`
`mailde`, `maildotde`
`yahoojp`

**Comment by jamie-mh** [comment]
Yes, the naming convention is simply to remove all special characters and put everything in lowercase.

For instance: Name.com becomes `namecom` and GMX.net becomes `gmxnet`.

**Comment by Schokobecher** [comment]
Yeah, makes sense- just wanted to make sure.
Thanks a bunch!
