### ISSUE TITLE
wear progress bar: do not start at zero

### ISSUE THREAD

**Issue by fuse314** [jamie-mh/AuthenticatorPro#295]
**Describe the bug**
Although the new progress bar looks very nice on android wear, it always starts at "0", even if the time is already halfway up and it is impossible to enter the code in time.

**To Reproduce**
1. Open a TOTP code on Wear
2. Notice the progress bar starting at a full circle
3. Close TOTP code when half of the time is expired (swipe right)
4. Open TOTP code again. The progress bar starts at a full circle again, but progresses faster than before.

**Expected behavior**
The progress bar should reflect the progress within the "30 second/1 minute/whatever" time window.
Example: if 15 seconds already passed, it should start at a half circle so I can see if it is realistic to enter the code still...

**App Version**
1.15.0 (Wear OS 2.5.0?)

**Additional context**

**Comment by jamie-mh** [comment]
Hi @fuse314 ,

Indeed, I am aware of this issue.

The widget used is a [CircularProgressLayout](https://developer.android.com/reference/androidx/wear/widget/CircularProgressLayout), which doesn't have a way of setting the starting progress. The solution was just to make it complete a full rotation in the remaining time.

I agree that it would be better to show the current progress and keep a constant speed.
If anyone has a solution, I'm all ears of course.

**Comment by jamie-mh** [comment]
Fixed in 1.15.1
