### ISSUE TITLE
Support icons through &image= parameter

### ISSUE THREAD

**Issue by mattiaverga** [jamie-mh/AuthenticatorPro#299]
I think it would be nice to support token icons through a `&image=` parameter in the URI.
I know the otpauth URI doesn't cover that parameter, but it doesn't seem there's a clear standard either. For example, FreeOTP supports the image parameter as a URI to an image. A better solution could be to support either a URI or a base64 encoded image.

That way a service can provide its own icon without having to embed the image into AuthenticatorPro code.

**Comment by jamie-mh** [comment]
Hi @mattiaverga ,

Yes, it would be feasible to pass a base64 encoded image in the otpauth URI. A URL to an image wont work since there is no Internet permission.

Is this something that is used anywhere though? Are there any services / apps that use this?

Thanks

**Comment by mattiaverga** [comment]
> Is this something that is used anywhere though? Are there any services / apps that use this?

Not at the moment, but in the future I think Fedora/CentOS account systems [could make use](https://github.com/fedora-infra/noggin/issues/565) of it.

**Comment by mattiaverga** [comment]
Re-thinking about it, the resulting URI would probably be too long with a base64 image embedded.

**Comment by mattiaverga** [comment]
I'm going to close this request, as I previously didn't realize that a feature of AP is that it doesn't require Internet access.

Embedding the image in the URL through base64 it's not feasible, as it would cause awfully long URLs.

However, I want to suggest to ensure you can actually embed the icons into the app. Mostly (all?) of the online services for which you are embedding the icon have explicit policies about their brand usage, it is possible that, legally speaking, some of them require written permission to do that... it's not just about finding a good quality svg and push a PR as said in the contributors documentation.
