### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by philblue1** [jamie-mh/AuthenticatorPro#305]
Hello,
like to have the following icons included (prepared as mentioned in the contributing guide + tinypng):

Tresorit [tresorit.png]
![tresorit](https://user-images.githubusercontent.com/38977798/139954679-ab160b48-fa24-4e07-9df9-d9705db50abd.png)

or v2, better use of space and some transparency to the inner whites for burning less in darkmode
![tresorit-b](https://user-images.githubusercontent.com/38977798/139961949-cb5d9f03-1a72-4d01-8285-95b8ead22986.png)

Barmenia [meinebarmenia.png]
![meinebarmenia](https://user-images.githubusercontent.com/38977798/139837685-794077ad-6fd4-4dbc-a1e6-c2574586f7dd.png)

[edit: fixed tresorit.png, v2]

**Comment by kwiateusz** [comment]
Tresorit looks bad on dark background it needs to be corrected a bit. Below how it looks like:
![tresorit](https://user-images.githubusercontent.com/924979/139953544-30efab96-bd4c-4f1f-ba13-08b72ac52af5.jpg)

**Comment by philblue1** [comment]
fixed

**Comment by b3pio** [comment]
> 
> 
> Hello, like to have the following icons included (prepared as mentioned in the contributing guide + tinypng):
> 
> Tresorit [tresorit.png] ![tresorit](https://user-images.githubusercontent.com/38977798/139954679-ab160b48-fa24-4e07-9df9-d9705db50abd.png)
> 
> or v2, better use of space and some transparency to the inner whites for burning less in darkmode ![tresorit-b](https://user-images.githubusercontent.com/38977798/139961949-cb5d9f03-1a72-4d01-8285-95b8ead22986.png)
> 
> Barmenia [meinebarmenia.png] ![meinebarmenia](https://user-images.githubusercontent.com/38977798/139837685-794077ad-6fd4-4dbc-a1e6-c2574586f7dd.png)
> 
> [edit: fixed tresorit.png, v2]

Hello, In future If you want to add icons, you have to create a pull request to do so as per the contribution guide. For Barmenia and Tresorit icons I fixed them up a little and added them to a pull request I just made here: https://github.com/jamie-mh/AuthenticatorPro/pull/307
:)

**Comment by jamie-mh** [comment]
Icons added in PR #307
