### ISSUE TITLE
Feature Request: 'pinned' category

### ISSUE THREAD

**Issue by anastrophe** [jamie-mh/AuthenticatorPro#308]
It's great having categories - but each time I open the app, I'm back on the 'all' category. It would be delightful if one could select a category to be the 'default', that will always open first when the app starts.

I keep my most used credentials in one category - call it 'frequents' -  so I don't have to scroll through all the others that I rarely use. Saves time and visual strain. If I could have AuthenticatorPro always open the 'frequents' category when I log in, it would save me the additional steps of selecting that most-often used category.

cheers!

**Comment by anastrophe** [comment]
Sorry this was entered as just a regular 'issue' - it took me directly in the first time I clicked 'new issue', while my second feature request attempt took me to the three options for entering an issue.

**Comment by jamie-mh** [comment]
Hi @anastrophe ,

This is probably identical to #251 . You can already set a default category in the "Edit Categories" menu.
