### ISSUE TITLE
Icon for Huobi

### ISSUE THREAD

**Issue by 5TR4TR3X** [jamie-mh/AuthenticatorPro#315]
[Please add icon for Huobi / Huobi Global](https://lisk.com/sites/default/files/media/icons/huobi-token-ht-logo.png)

**Comment by b3pio** [comment]
I can add it to my next pull request of new icons soon if someone else doesn't do it sooner.

**Comment by b3pio** [comment]
> 
> 
> [Please add icon for Huobi / Huobi Global](https://lisk.com/sites/default/files/media/icons/huobi-token-ht-logo.png)

Added in PR #316 for you sir
