### ISSUE TITLE
Companion app offline

### ISSUE THREAD

**Issue by wifi86** [jamie-mh/AuthenticatorPro#32]
Hello,

Is it possible to have the companion app generate codes while offline? 

I was used to have that functionality in my pebble. And solves some issues when your phone is drained. I really enjoy using the application and I think this functionality could make it closer to perfection.

Thank you very much for all your work and allowing us to work with your app. 
Best regards.

**Comment by jamie-mh** [comment]
Hi @wifi86 ,

This was also discussed in #21. It may certainly be possible, but have yet to figure out if sending secret keys to the watch is secure or not. I'll leave this issue open for now until I figure out a solution.

**Comment by jamie-mh** [comment]
Hi,

The latest version of the companion app (2.0.0) now functions without a persistent connection to the phone. It should be available on Google Play shortly. There are significant app changes so both applications must be updated to the latest version to work correctly.
