### ISSUE TITLE
Authenticator doesn't show the top entry

### ISSUE THREAD

**Issue by l-marchesi** [jamie-mh/AuthenticatorPro#320]
**Describe the bug**
When I open the app it shows the entries but starting with the second one on the list. The first and "top most" entry is not visible. When scrolling up, it shows up. When scrolling down it doesn't show up, unless I scroll up again.
This error exists on my old backup phone (Android 7.1.1) and my current phone (Android 11), both are Sony phones though.

**To Reproduce**
1. Open the app.
2. Authenticate
3. Check list
4. scroll up to see seemingly missing/hidden entry

**Expected behavior**
Seeing the top entry first, followed by the other entries.

**App Version**
1.15.3

**Additional context**
Seems that it showed up since the last update - I didn't see this behaviour before.

**Comment by jamie-mh** [comment]
Thanks for reporting this. It will be fixed in the next update.
