### ISSUE TITLE
No backup to remote

### ISSUE THREAD

**Issue by Offerel** [jamie-mh/AuthenticatorPro#324]
**Describe the bug**
I have mounted a remote WebDAV share via DavX5 to the standard Android filemanager. I can open for example a backup file from this share with Authenticator Pro. I can also set this share/folder as backup path successful. But if I start a backup, the process fails. 

**To Reproduce**
1. Install DavX5, mount a WebDAV share
2. Set the share as backup path
3. Start a backup
4. See error message

**Expected behavior**
Backup File is saved to the share successful

**App Version**
1.15.3

**Additional context**

**Comment by jamie-mh** [comment]
Hi,

Thanks for reporting this. It seems that the error is thrown from DavX5, it doesn't support the "rwt" access mode.
This will be fixed in the next update.
