### ISSUE TITLE
System Icon issue

### ISSUE THREAD

**Issue by salman-q** [jamie-mh/AuthenticatorPro#33]
![Screenshot_20200707-235224__01](https://user-images.githubusercontent.com/67760072/86898076-db92c080-c125-11ea-9243-e2093994b750.jpg)

In the App settings & other system level settings, the default Android icon shows up instead of the original one.

**Comment by jamie-mh** [comment]
Hi @salman-q ,

Indeed, I've noticed the same thing on my phone sometimes. No problem, simple fix cc37cb3.

**Comment by salman-q** [comment]
Was this fixed in the latest Play Store update?

P.S.: Awesome update! Everything I could hope for. Loving the tile view and custom icon option.

**Comment by jamie-mh** [comment]
Thanks.
It seems the issue reappears when packaging the app for release. I will investigate further.
