### ISSUE TITLE
Implement Material You theming

### ISSUE THREAD

**Issue by i-am-gizm0** [jamie-mh/AuthenticatorPro#339]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Eg. I'm always frustrated when [...]
N/A

**Describe the solution you'd like**
It'd be nice for this app to automatically select accent colors from Material You, if the device supports it. Maybe the colors could even still be overridden from the settings menu.

**Additional context**
In Android 12, Google announced Material You, which selects colors from the device's wallpaper and themes the whole device using those colors.
Example:
![GBoard tinted pink from my wallpaper](https://user-images.githubusercontent.com/20424374/144765565-d99f73b9-b6aa-40bd-af73-33415e4303c7.png)
Docs: https://m3.material.io/libraries/mdc-android/color-theming

**Comment by Doomsdayrs** [comment]
This can be done with a 1 line implement 
```
https://developer.android.com/reference/com/google/android/material/color/DynamicColors
```

**Comment by jamie-mh** [comment]
This is being worked on. The [README](https://github.com/jamie-mh/AuthenticatorPro/blob/master/README.md) has some screenshots of the Material You design.
