### ISSUE TITLE
Support to Import from Microsoft Authenticator

### ISSUE THREAD

**Issue by mauriliofilho** [jamie-mh/AuthenticatorPro#340]

**Comment by jamie-mh** [comment]
Not possible, from FAQ:

> 
> ➡️ Can you add import for [alternative authenticator app]?
> 
> It depends if the app supports exporting your data to a file. For instance, Microsoft Authenticator doesn't allow you to export your secrets, but rather only lets you sync with your Microsoft account. Your data is locked in and thus it's impossible to transfer to Authenticator Pro without disabling and re-enabling 2FA on all of your accounts.
