### ISSUE TITLE
Issue with installation on Android 12

### ISSUE THREAD

**Issue by Porkepix** [jamie-mh/AuthenticatorPro#343]
**Describe the bug**
Issue with installation on Android 12: I wanted to update AuthenticatorPro on my work's phone, which has since updated from Android 11 to 12. I usually install from F-droid and got the message visible on the below screenshot. Then I tried to grab apks here, both armv7 and v8 versions, and file managers said there was a problem parsing the file.

![Screenshot_20211213-101747](https://user-images.githubusercontent.com/709500/145785731-567f3cbd-dc81-4f6e-8cba-ed0631d8fa8d.png)

**To Reproduce**
Just try to install latest version on Android 12

**Expected behavior**
I expect the installation to go flawlessly like it used to.

**App Version**
From 1.15.3 to 1.15.4.

**Additional context**
Device is a Pixel3a on the official Android 12 and didn't encounter any issue when it was on Android 11.
My Android 8 device didn't got any issue either.

**Comment by jamie-mh** [comment]
Hi,

Thanks for reporting this.
Seems like yet another useless change to Android that only serves to break apps.

`
adb: failed to install me.jmh.authenticatorpro-x86_64.apk: Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl324624256.tmp/base.apk (at Binary XML file line #23): crc64b0b952e8bab340e6.WearQueryService: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present]
`

Anyway, I've pushed a fix. Version 1.15.5 has no problems installing.
