### ISSUE TITLE
I can't change the language

### ISSUE THREAD

**Issue by gusantoscode** [jamie-mh/AuthenticatorPro#345]
**Describe the bug**
I can't change the language of my app, it just doesn't work. I've already tried clearing my cache and reinstalling the app, but the problem persists. I can't change to any language, I even tried to change the language of my smartphone, but without success.

**To Reproduce**
1. Go to main button
2. Click on settings
3. Click on the language and select a language 

**Expected behavior**
Well, I was hoping this would change the language of my app.

**App Version**
1.15.5

**Additional context**
...

**Comment by jamie-mh** [comment]
Hi,

What error are you experiencing?

**Comment by Kvasenok** [comment]
I can confirm the language of the app doesn't change as it should. There is no error or anything, just nothing happens once you change the language. 
In my experience, as I have my system default language set to russian, If I set the app language to system default or to russian it will change accordingly, but if I choose any other language it just switches back to english.
I beliave other people have the same issue but with their language. The app seems to only recognize system language and, if supporred, can switch to it, but can't be manually switched to other language.

**Comment by jamie-mh** [comment]
This is most likely an issue with App Bundles. When downloading an app from Google Play, it only downloads the languages available on the device to save data. I'm not sure there is anything I can do to fix this.
This shouldn't be an issue when installing from the APK however.

**Comment by Kvasenok** [comment]
Is it possible to filter out unavailable languages in the language selection screen maybe? Like, in my case I would only see English and Russian, but others would see their language and probably English.

**Comment by jamie-mh** [comment]
Perhaps, but it doesn't explain the issue. People will simply wonder why their language is not in the list.
