### ISSUE TITLE
Making icons the same style

### ISSUE THREAD

**Issue by luaxlab** [jamie-mh/AuthenticatorPro#35]
Hello,

I've noticed that the icons dont quite match eatch other.
Most icons have got no frame, tough some icons, e.g. Nextcloud, Snapchat and Nintendo got one.

I'd recommend adding rounded corners, some icons (e.g. Nintendo, Nexcloud) have got to many details, I'd replace them completely. (Even on my Galaxy A71 they dont quite look good)

If someone agrees with me.... I could "do the work".

Have a great day.

**Comment by jamie-mh** [comment]
Hi @luaxlab ,

Are you proposing adding rounded corners to all the icons or just the ones with frames?
For many of these icons it wouldn't be too difficult to just remove frame around them.

**Comment by luaxlab** [comment]
Hi @jamie-mh,

Only the ones with frames. Of course removing the frame completely would be the better choice,  just haven't tought about that.
For some (overdetailed) icons, I'd suggest replacing them tough.

**Comment by jamie-mh** [comment]
Indeed, that is preferable. The Nextcloud icon for instance can be replaced with just the blue image (https://upload.wikimedia.org/wikipedia/commons/6/60/Nextcloud_Logo.svg) without the text. That would probably look better.
Some icons such as Facebook and LinkedIn have a frame as part of the design, so removing that might not work.

**Comment by luaxlab** [comment]
I'll do that, I'll commit when I'm done.
