### ISSUE TITLE
QR scanning through camera on Pixel 6

### ISSUE THREAD

**Issue by PremiumSaltine** [jamie-mh/AuthenticatorPro#350]
QR scanning through the camera does not work on Pixel 6.

Tried on two different Pixel 6 phones with newest version of app. QR codes are clear on screen. Nothing happens at all.

QR codes from saved images work fine.

**Comment by PremiumSaltine** [comment]
Updated to 1.15.6 and still have the same problem.

**Comment by jamie-mh** [comment]
Original discussion in #286
