### ISSUE TITLE
Add support to import from Duo Mobile

### ISSUE THREAD

**Issue by MiguelNdeCarvalho** [jamie-mh/AuthenticatorPro#351]
**Is your feature request related to a problem? Please describe.**
I wanted to migrate all of my stuff inside Duo Mobile to Authenticator Pro

**Describe the solution you'd like**
Possible to import the entries inside the Duo Mobile app

**Comment by jamie-mh** [comment]
Not possible without root access. You cannot export your accounts to a file, so they cannot be imported by Authenticator Pro.

**Comment by MiguelNdeCarvalho** [comment]
And shouldn't we add a possible way of doing that with root? Thanks

**Comment by ThatOneCalculator** [comment]
@jamie-mh Actually, there is a way to do this without root. When adding a new device to Duo, there's a QR code you can scan, and there's already code to process the HOTP: https://gist.github.com/fifty-six/80fa6f9d18952ec21253fc10d1c9d548 and a working implementation: https://github.com/AvikRao/duo-extension
