### ISSUE TITLE
Custom order is not reflected on WearOS

### ISSUE THREAD

**Issue by kalikiana** [jamie-mh/AuthenticatorPro#352]
**Describe the bug**
I changed the order to **Custom** and moved things around the way I like. Even after a restart the order seems to be unchanged on my Watch.

**To Reproduce**
1. Hit the top-right ≡ (not exactly the icon but I couldn't find a way to type it)
2. Select Custom ◯
3. Open Authenticator Pro on WearOS
4. Compare the order

**Expected behavior**
The order is the same on WearOS and on Android

**App Version**
1.15.5

**Additional context**
I restarted my Galaxy Watch twice and double-checked that it was connected and there's no 🚫☁️ at the top

**Comment by jamie-mh** [comment]
Hi,

A few questions to help diagnose the issue:
- Are they stuck in alphabetical order on the watch?
- Does clearing the cache on the watch app make a difference?
- Is this in a category or in the "All" category?

Thanks

**Comment by kalikiana** [comment]
> * Are they stuck in alphabetical order on the watch?
Yes.
> * Does clearing the cache on the watch app make a difference?
I don't know how to do that,
> * Is this in a category or in the "All" category?
I haven't configured any categories so far.

I had another thought, that batter saving might affect it but it doesn't seem to.

**Comment by jamie-mh** [comment]
To clear the cache, you need to find the app in the watch settings menu and find the clear cache option. This will force a resync of the app with the phone.

**Comment by kalikiana** [comment]
> To clear the cache, you need to find the app in the watch settings menu and find the clear cache option. This will force a resync of the app with the phone.

I still couldn't find anything like that.

Meanwhile something has indirectly caused the order to get updated. There was an update to the app, and I also migrated a bunch more logins.

I don't know what else to check. It feels like whatever the regular sync between the watch and the phone is, is not working.
