### ISSUE TITLE
Unable to handle Wordfence QR-codes / keys

### ISSUE THREAD

**Issue by steinsag** [jamie-mh/AuthenticatorPro#353]
[Wordfence](https://wordpress.org/plugins/wordfence/) is a popular "security" plugin for Wordpress. Besides many other things, it enables 2FA on Wordpress sites.

Authenticator Pro is unable to read generated QR code and also manually entering the key doesn't work. Protocol is said to be TOTP.

Here a sample QR code:

![qr-code](https://user-images.githubusercontent.com/1233703/147166789-5c4a2392-4ecb-4f95-bd07-d744d09f5dd1.png)

The belonging key is:

2DKVPVVH4FXHTBNOR462JVTBI5JZCX2U

Not sure if relevant, but recovery code reads:

    bd0b 0ec7 92a0 9363
    f8b6 df7c e5aa a6f3
    279e 0ead 2f91 7896
    433e b6cb 3e65 179d
    458e b875 969b ba8f

Also, when scanning the code with Google Lens (Android camera), it shows an URL starting with: otpauth://totp/www.altherrengedeck.de/...

**Comment by steinsag** [comment]
![qr-code](https://user-images.githubusercontent.com/1233703/147166751-83c87856-7e5c-45ba-a620-d6c83e67cee6.png)

^^^ QR code mentioned in report above

**Comment by jamie-mh** [comment]
Hi,

I'm not sure what the problem is. I've scanned the QR code on my device and it works fine. I've even tried entering the secret key.
Can you be more specific as to the issue you're experiencing?

Thanks

**Comment by steinsag** [comment]
That's totally strange, I still can't scan the code. I have Authenticator Pro version 1.15.6 on Android 12 with December security patches.
When I try to scan the QR-code, nothing happens. It seems it doesn't recognize the QR-code at all. If I select to scan it from an image I have taken before, it says

"QR-Code is not in correct format or it can't be read".

Now, if I enter everything manually (key, issuer with full domain, and username), it works. So issue seems to be related to scanning QR-code. Maybe some Android API change?

**Comment by jamie-mh** [comment]
It sounds like the QR code scanning is not working as it should. Some other users are having issues in #286.
