### ISSUE TITLE
Unable to handle AWS QR-codes

### ISSUE THREAD

**Issue by ungarida** [jamie-mh/AuthenticatorPro#355]
**Describe the bug**
Unable to handle AWS QR-codes

**To Reproduce**
1. Go to AWS IAM Console
2. Select a user
3. Go to Multi-factor authentication (MFA)
4. Assign Virtual MFA device
5. Show QR Code
6. Using Authenticator Pro just installed add a new entry
7. Scan a QR Code - tried both using the camera or using a picture

**Expected behavior**
Add a new entry

**App Version**
1.15.6

**Comment by jamie-mh** [comment]
This probably isn't AWS specific (#353). Some other users are having issues with QR codes in #286.
