### ISSUE TITLE
QR code do not work

### ISSUE THREAD

**Issue by gusantoscode** [jamie-mh/AuthenticatorPro#357]
**Describe the bug**
When I try import a new key with the QR code, just not working. My camera is working perfecly, is focusing normally.

**is To Reproduce**
1. Click on more button
3. Click on scan a QR code
4. Click on scan from camera
5. And see the error, you can point at the qr code and not working.

**Expected behavior**
...

**App Version**
1.15.6

**Additional context**
...

**Comment by jamie-mh** [comment]
Duplicate of #286
