### ISSUE TITLE
Bad wording may lead to unencrypted backups for users being confused by settings

### ISSUE THREAD

**Issue by c0deright** [jamie-mh/AuthenticatorPro#358]
## Describe the bug
The current wording in *Settings* regarding **Backup with Database Password** and **Auto Backup** is confusing and might lead to
* users thinking their automatic backups are encrypted when in fact they are not or
* users being confused as to **which password** is being used to encrypt automatic backups

## App Version
1.15.7

## Users thinking their automatic backups are encrypted when in fact they are not
* Start with fresh install
* Open Settings
* Set a Password (under Security)
* Tap Auto Backup (under General)
  * Select location
  * Set an empty password
  * ACK the warning message about unencrypted backups
* Enable Auto Backup

The user has now enabled _unencrypted_ auto backups.

At a later time the user might want to enable encryption for his automatic backups so the user opens up *Settings* again and sees under *Security* the following option:

> **Backup with Database Password**
> Encrypt all backups using the database password so you don't need to enter it each time [YES/NO]

Because of the wording **Encrypt all backups** the user enables this options believing this will result in encrypted _automatic_ backups when in fact this setting only will encrypt _manual_ backups, not automatic ones (The password for automatic backups being still empty).

## Users being confused as to **which password** is being used to encrypt automatic backups
Same as above but set a non-empty password for automatic backups.

The user may believe his Password to enter the APP is being used as passphrase for automatic backups because of the wording **Encrypt all backups using the database password** when in fact the password set in the **Auto Backup** dialog is used for encrypting _automatic_ backups and the APP password is only used for _manual_ backups.

This may lead to users being unable to restore their automatic backups.

## Current Design

The currend design of the options and text presented in *Settings* might be confusing (at least it was for me)
* best case: The user can't restore his backups
* worst case: Backups are stored unencrypted

## Possible Solution
* Don't differentiate between manual and automatic backups
  * let the user define a custom passphrase for all their backups in settings (regardless of it being manual or automatic backup)
* Improve wording to make it 100% clear which password is used for which type of backup

**Comment by jamie-mh** [comment]
Hi @c0deright ,

Thanks for the write-up. I've made a change so that the "Backup with Database Password" option applies to the auto backups from now on. An while it's set, it's no longer possible to enter a separate password for the auto backups. This should eliminate any confusion.

Thanks
