### ISSUE TITLE
As user, I want to receive reminder to reenable/recreate the 2FA of an account after n days(180 days?) , so that a new secret code will be created. 

### ISSUE THREAD

**Issue by siakhooi** [jamie-mh/AuthenticatorPro#362]
**Is your feature request related to a problem? Please describe.**
not a problem, but i believe the secret should be recreate after some times, just like our password. Anyone get the secret, can generate the same code.

**Describe the solution you'd like**
notification? with snooze? or todo task in app?

**Additional context**
n/a

**Comment by tmc-au** [comment]
What problem are you trying to solve with this? 

is this a measure to prevent initialisation vectors for the 2FA sequence being brute-forced or are you concerned about the fact that a breach of a system that discloses usernames and passwords might also expose the 2FA seed material?

**Comment by siakhooi** [comment]
yes, no.
also risk of secret iv get compromise in the backup
and risk of poor password of the backup
and risk of brute-forced of the backup.

it may not be 180 days, just an example figure. it could be 1 year, 2 years.

and at minimum, at least the app should show us the date/time when the secret iv was first generated. (this is easier to do right?)
we can judge ourselves if we want to regenerate it.

**Comment by jamie-mh** [comment]
This appears to be a very niche feature of dubious security benefit.
I'm not looking into supporting this.
