### ISSUE TITLE
Enable GitHub wiki

### ISSUE THREAD

**Issue by luaxlab** [jamie-mh/AuthenticatorPro#37]
Hi,
I'd suggest enabling the GitHub wiki. Documentation, FAQs and contribution guide could be moved over there to make the README.md and the overall structure cleaner.

**Comment by jamie-mh** [comment]
Hi @luaxlab ,

I understand what you mean. Wouldn't moving some info into separate markdown files be a better approach? GitHub wikis are as the name suggests specific to GitHub and not part of the repo files. Keeping documentation available no matter where it is hosted seems preferable too me.

**Comment by luaxlab** [comment]
I did some quick research just now. I think a [contribute.md](https://gist.github.com/PurpleBooth/b24679402957c63ec426) (maybe a little fewer text) is what fits best.

**Comment by jamie-mh** [comment]
I agree. I'll move some stuff into a new markdown file.
