### ISSUE TITLE
I would like to add an icon

### ISSUE THREAD

**Issue by applejapan** [jamie-mh/AuthenticatorPro#370]
Nice to meet you. from Japan. I would like to add an icon
If possible, I would like to ask for Japanese support. 
There was still a bug, and it hung up during the registration of dozens of cases, probably because of backup. The error could not be sent 

Name of website / service	https://www.aikq.de/index.php
![aikQ](https://user-images.githubusercontent.com/45900620/154410857-bf5ef41b-821d-49f9-a16a-d3642a7187c9.png)
Name of website / service	https://www.aol.com
![Aol](https://user-images.githubusercontent.com/45900620/154410942-41cca65d-bd43-4db9-9cee-7792b4b10a23.png)
Name of website / service	https://dismail.de/
![dismail de](https://user-images.githubusercontent.com/45900620/154410990-af069aa2-fbb5-4d73-8292-678e396a2594.png)
Name of website / service	https://www.eclipso.eu/
![eclopso](https://user-images.githubusercontent.com/45900620/154411008-34f093c5-812b-49c4-9642-0c34284ee7b3.png)
Name of website / service	https://firemail.de/index.php
![Firemail de](https://user-images.githubusercontent.com/45900620/154411032-0a1a0bfc-a757-45f9-8a73-9fc0879a5763.png)
Name of website / service	https://accounts.freemail.hu/a/login#authdone/checktid/notid
![freemail hu](https://user-images.githubusercontent.com/45900620/154411051-1eec32f1-8e69-40d4-a6dc-69d7e3407dbc.png)
Name of website / service	https://gab.com/home
![gab](https://user-images.githubusercontent.com/45900620/154411087-e5afe7d2-d81e-49c6-bb9a-936a4acdb17d.png)
Name of website / service	https://www.inbox.la/
![inbox la](https://user-images.githubusercontent.com/45900620/154411105-3a142690-e7ce-4f28-9270-bde89b5e885b.png) 
Name of website / service	https://www.inbox.lt/
![inbox lt](https://user-images.githubusercontent.com/45900620/154411158-bcd04adb-53f3-45ed-a6cc-7e489b8cdecf.jpg)
Name of website / service	https://www.inbox.lv/
![inbox lv](https://user-images.githubusercontent.com/45900620/154411176-e9514cd9-e5b7-4576-913e-2ca6c7c7fde4.jpg)
Name of website / service	https://mail.co.uk/en/
![mail co uk](https://user-images.githubusercontent.com/45900620/154411197-6b267d49-6c7b-4d6b-967a-b916716bf418.png)
Name of website / service	https://www.mail.ee/
![mail ee](https://user-images.githubusercontent.com/45900620/154415775-5e50cdbc-c146-4ac2-b01c-8b8452ec991e.png)
![mail ee2](https://user-images.githubusercontent.com/45900620/154415791-9cd8e081-32d0-4f3c-9074-bc954d1e8fa9.png)
Name of website / service	https://www.mailo.com/
![mailo com](https://user-images.githubusercontent.com/45900620/154415850-5b5540d1-82b9-4b4e-ab02-89868470b0d7.png)
Name of website / service	https://www.mailjunky.de/index.php?action=signup
![mailjunky](https://user-images.githubusercontent.com/45900620/154415889-6765ca1d-3369-4a3b-a5bd-d63215877a4b.png)
Name of website / service	https://moneyforward.com
![moneyforward](https://user-images.githubusercontent.com/45900620/154415916-16ba60a2-c8cd-4d08-89c2-8a23d4dd1b3d.png)
Name of website / service	https://myaccount.getmoneytree.com/login?locale=ja
![moneytree](https://user-images.githubusercontent.com/45900620/154415959-65ac2ec8-5fbe-4890-ac98-e102087db6c7.png)
Name of website / service	https://www.nicovideo.jp
![niconico](https://user-images.githubusercontent.com/45900620/154415979-bee65574-ecca-4166-b36b-e11da51dee02.png)
Name of website / service	https://www.onmail.com/
![onmail](https://user-images.githubusercontent.com/45900620/154416014-7532fa7b-5f6f-40ef-8ff0-bd0b52db7461.png)
Name of website / service	https://skymail.de
![skymail](https://user-images.githubusercontent.com/45900620/154416040-23c44be9-c3f0-4577-9894-f8b6445aefa9.png)
Name of website / service	https://toucharcade.com
![toucharcade](https://user-images.githubusercontent.com/45900620/154416097-dac4852e-b540-476e-9851-d4ec17e76e14.png)
Name of website / service	https://woelkli.com/en
![woelkli](https://user-images.githubusercontent.com/45900620/154416116-683fc482-6ce1-4740-8e5c-148aff375ad5.png)

**Comment by jamie-mh** [comment]
Added some of the icons in f6b3954. Most are too niche to have high quality icons.

**Comment by applejapan** [comment]
Thank you

**Comment by MINHHA1978** [comment]
Thanks much!!!

Vào 15:55, CN, 3 Th4, 2022 jmh ***@***.***> đã viết:
