### ISSUE TITLE
Automatic Backups

### ISSUE THREAD

**Issue by IncognitaDev** [jamie-mh/AuthenticatorPro#372]
**Is your feature request related to a problem? Please describe.**
I like to save a backup when every new token are added

**Describe the solution you'd like**
I think a config to set automatic backups, included this method.

**Comment by kwiateusz** [comment]
You already have that option in settings,
![Screenshot_20220219-051518](https://user-images.githubusercontent.com/924979/154785734-b5ab623c-31ca-4437-a911-547b480e6169.jpg)
 it's second position.
