### ISSUE TITLE
Circle timer not updating on watch

### ISSUE THREAD

**Issue by ClarkBoggle** [jamie-mh/AuthenticatorPro#373]
When displaying the code on watch, the timer works (the code is updated periodically) but the round blue circle does not progress on screen, so you can't see when the code is going to update.

You need to go back to the list and call for the code again to update once the blue circle timer.

Version 1.15.8

**Comment by dschoerk** [comment]
my Galaxy Watch 4 (SM-R860) shows the blue running circle, what watch are you using?

**Comment by ClarkBoggle** [comment]
Hi

Thanks for your answer.

I use the first Huawei watch classic, with wearos 2.

When I go back to the main screen and reload the code screen, the blue
circle is updated just once when the screen is displayed.

When time if off, the code change and the blue circle is reseted, but it
never runs live.

I can do a small video if you want?

**Comment by jamie-mh** [comment]
Due to the lack of activity, I'm closing this issue.
