### ISSUE TITLE
Theme icons don't toggle when changing from a theme to system.

### ISSUE THREAD

**Issue by luaxlab** [jamie-mh/AuthenticatorPro#38]
Hello,
I've noticed following in the recent version 1.9.0: When you change from any theme to "System" in the "Theme" settings while you device is in the opposite mode than you had selected before, the background color changes, but the icons do not.

I've tested this on Samsung Galaxy A71, Samsung Tab S6 and on Emulator Pixel Q 10.

**Comment by jamie-mh** [comment]
Hi @luaxlab ,

Good find. Fixed in 556fdef.
