### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by haarp** [jamie-mh/AuthenticatorPro#4]
Currently entries are shown in the order they were added. This can make finding something quickly hard when there's lots of items. I think it would be sensible to sort items by Issuer first, and then by username.

Thanks!

**Comment by jamie-mh** [comment]
You can hold and drag authenticators in any order you choose. This probably isn't a very intuitive feature, but it's there. Same with categories.

**Comment by haarp** [comment]
Ah, so you can. I did not notice this, thanks! I still think automatic sorting would be convenient, but this'll do too.

**Comment by jamie-mh** [comment]
Yes, I think you're right. I will make the authenticators ordered by username then issuer by default and if the user wishes to make changes they will still be able to manually set the order.
