### ISSUE TITLE
versionCode mishap?

### ISSUE THREAD

**Issue by IzzySoft** [jamie-mh/AuthenticatorPro#40]
Could it be you accidentally introduced a zero too much into the latest release's versionCode? At least the armeabi identifies as

    package: name='me.jmh.authenticatorpro' versionCode='210000040' versionName='1.9.1.1' compileSdkVersion='29' compileSdkVersionCodename='10'

which is one digit more than in previous versions, and not matching what fastlane's changelogs have (again a zero too much).

Question now is, will you continue from there? Otherwise all those having updated to this version won't get future versions offered as update. Or do you want to risk a "quick replace", before too many people updated? Then please let me know soon so I can replace the APK in my repo as well.

**Comment by jamie-mh** [comment]
Hi @IzzySoft ,

Thanks for spotting this, indeed this was not intended. I added a '0' to submit the app as a bundle on Google Play. Seems I messed up with the apk release.
I've updated the tag, the apks now have the correct version code.

**Comment by IzzySoft** [comment]
Uh, OK – then I'll quickly trigger a repo update on my end before too many people grab the messed-up APK. Should be out in a few minutes. Thanks!
