### ISSUE TITLE
Using Authenticator Pro on multiple devices?

### ISSUE THREAD

**Issue by panyann** [jamie-mh/AuthenticatorPro#404]
I have Authenticator Pro installed on my tablet. When I installed it on the mobile and restored backup, it doesn't work. Still works on the tablet.

Can it be done to work on multiple devices? Is it possible?

**Comment by jamie-mh** [comment]
You will need to be more specific as to what the problem is.

**Comment by panyann** [comment]
I think the problem is pretty clear... The Authenticator Pro can be used on only one device at a time.

1. I made a backup on my tablet.
2. I restored the backup on the mobile.
3. The restored backup on the mobile doesn't work.
4. It still works on the tablet.
5. Can't use Authenticator Pro on mutliple devices.

**Comment by jamie-mh** [comment]
The app doesn't connect to the Internet so one device cannot interfere with another.
"It doesn't work" is as clear as mud frankly, what you meant to say is that the generated codes are wrong.

The answer can be found in the wiki : [Codes not working](https://github.com/jamie-mh/AuthenticatorPro/wiki/Codes-not-working).

**Comment by panyann** [comment]
What the hell, I actually had a wrong time on one of the devices...
I guess I will "buy you a coffee" for wasting your time.

Maybe you could add such a FAQ page in the future to the app itself, could be useful to have it at hand.
