### ISSUE TITLE
Wrong badge in Readme?

### ISSUE THREAD

**Issue by IzzySoft** [jamie-mh/AuthenticatorPro#408]
Just a suggestion: you're currently using the F-Droid badge to link to my repo – which can be a little irritating. Maybe it could be replaced [by this badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it)?

![IoD Badge](https://gitlab.com/IzzyOnDroid/repo/-/raw/master/assets/IzzyOnDroid.png)

**Comment by jamie-mh** [comment]
No problem, I've changed it.

**Comment by IzzySoft** [comment]
Thanks a lot, Jamie! I had almost closed the request at F-Droid.org thinking the app was already there :see_no_evil:

**Comment by jamie-mh** [comment]
I used the F-Droid badge thinking people would be more familiar with it. But I agree, it's a little misleading.

**Comment by IzzySoft** [comment]
Yupp, I understand the reasoning, so no complaints :smile: Luckily, my own repo got a little popularity on its own already, too…
