### ISSUE TITLE
[Feature request] categories  in WearOS and Widget for phone   +   [Feedback]

### ISSUE THREAD

**Issue by rICTx-T1D** [jamie-mh/AuthenticatorPro#41]
----- English -----
hi folks, 
the app is very usefull and I like it so much! Thanks! My favorite benefits are the categories function to sort all my 14 OTPs  and the option to backup it.

If I still to have two wishes, then I would like to have a widget that can be filtered for a category and an option to use categories in the WearOS app. (Start the WearOS app -> list of categories (All, Cat1, Cat2, ...) and then the OTPs there.

Have many thanks in advance.

----- German -----
Klasse App... Endlich kann man mal die mittlerweile 14 OTPs in Kategorien unterteilen und auch sichern. Auch die WearOS-Integration ist Spitze, wo selbst Google diese bei ihrer eigenen Authentificator-App gestrichen hat. Wenn ich noch zwei Wunsch frei habe, dann hätte ich gern noch ein Widget welches man auf eine Kategorie filtern kann und die Auswahlmöglichkeit der Kategorien in der WearOS-App. (WearOS-App starten -> Liste mit Kategorien (Alle, Kat1, Kat2, ...) und dann dadrin die OTPs.

Vorab vielen lieben Dank.

**Comment by jamie-mh** [comment]
Hi @rICTx-T1D ,

Indeed, categories is something I've previously considered adding to the Wear OS app, I just haven't had the time to implement it just yet. As for a widget, I'm not sure this is a good idea for a few reasons:
- Battery life and performance: a widget where the data changes very frequently will certainly be detrimental to battery life.
- Security: you can effectively bypass a lock screen by using a widget.
- Speed: is it much more convenient that opening the app and selecting a category? I'm not convinced.

Sorry, I probably won't work on a widget as I don't see the use case.

**Comment by jamie-mh** [comment]
Hi,

The latest version of the companion app (2.0.0) now features a category menu that can be accessed by swiping downwards.
