### ISSUE TITLE
How to install the Wear OS Companion App?

### ISSUE THREAD

**Issue by AxelMKlein** [jamie-mh/AuthenticatorPro#42]
Hi all,

Sorry for the stupid question, but I don't find the Wear OS companion app.

Where do I find that to install?

Thank you in advance and best regards
Axel

**Comment by jamie-mh** [comment]
Hi @AxelMKlein ,

Don't worry, it's not a stupid question. The answers depends on where you downloaded the phone app from.

- Google Play: in this case, simply open Google Play on your watch and search for Authenticator Pro.
- F-Droid / APK: this is a bit more tricky. You need to download the latest Wear OS apk of the app from the [GitHub releases](https://github.com/jamie-mh/AuthenticatorPro/releases). Then sideload it onto your watch, [like this](https://www.techadvisor.co.uk/how-to/google-android/sideload-apps-android-wear-3673967/).

Both versions of the app (phone and watch) must be from the same source or else it won't work. I obviously recommend installing from Google Play, it's much simpler.

Let me know if this answers your question.

**Comment by AxelMKlein** [comment]
Hi @jamie-mh ,

Thank you for your quick answer.

It totally answers my question and it works perfectly like that.

Thank you and best regards
