### ISSUE TITLE
Please Add Language Japanese

### ISSUE THREAD

**Issue by motty-mio2** [jamie-mh/AuthenticatorPro#422]
**Is your feature request related to a problem? Please describe.**
Japanese is not available.

**Describe the solution you'd like**
I do translate.

**Additional context**
I'm impressed by your app, so I want to contribute this project.

**Comment by jamie-mh** [comment]
Hi,

I've added Japanese to the list of languages on Crowdin. You should have access now.

Thanks

**Comment by motty-mio2** [comment]
I finished!!! I'll edit it again when I notice anything wrong that I find in while using.
Thank you.
