### ISSUE TITLE
Tap to unhide shows code for a split second only

### ISSUE THREAD

**Issue by adoeller** [jamie-mh/AuthenticatorPro#425]
Android 11
The code showed up longer on Android 10, although I had to tap a couple of times. Now it shows up shortly all the time. 

The code should be revealed for a couple of seconds in order to memorize it.

**Comment by jamie-mh** [comment]
The code should be visible until it expires, is this not the case?

Thanks

**Comment by adoeller** [comment]
Never did on my phone, huawei mate 20.
The code is shown less than 1 second, but the duration also varies.

**Comment by adoeller** [comment]
to be more exact, the code gets cleared with the next update of the 30 seconds progress bar

**Comment by jamie-mh** [comment]
> to be more exact, the code gets cleared with the next update of the 30 seconds progress bar

That's the planned behaviour. Can you be more clear please? This appears to contradict your original post.

**Comment by adoeller** [comment]
Hi,
it does not contradict, as I said "next **update** of the 30 seconds progress bar", and not "after 30 seconds"

https://user-images.githubusercontent.com/45470571/169649921-1fb83764-8814-41dc-99a7-4defdea91c44.mp4

Please have a look at the video

**Comment by Tokariew** [comment]
I think that i found the culprit setting for such behaviour at least on lineageOS 19.1
In the `Settings` go to `Accessibility` and to `Text and display` and then select `remove animation`.
Force close auth app, run again and see the bug. Toggle that setting off and after running app again in works normally and code don't display for split second

**Comment by adoeller** [comment]
Hi, I can confirm that this is affected by the mentioned option. However, when switching back to off (default) the otp code is shown for a split second again. (huawei mate 20) Best regards, Alex

**Comment by jamie-mh** [comment]
Fixed in 26ccd83.
