### ISSUE TITLE
Feature request - Wear OS Offline mode

### ISSUE THREAD

**Issue by schrauger** [jamie-mh/AuthenticatorPro#43]
I'd love to be able to use the app without a phone connection. On my old Pebble watch, there was an authenticator app that stored the seeds on the watch and was able to generate codes without needing to be connected to the phone. Currently, this app doesn't work without an active connection to the paired phone.

If the Wear OS app could work while the watch was in offline or airplane mode, I'd be able to use it to generate codes while still keeping my watch in battery saving mode with connectivity disabled.

**Comment by Schokobecher** [comment]
This sounds like #32 (which was discussed in #21:sweat_smile:)

**Comment by schrauger** [comment]
You're right, it's the same as #32.
