### ISSUE TITLE
Security pattern

### ISSUE THREAD

**Issue by Michal-Mikolas** [jamie-mh/AuthenticatorPro#433]
Hello, 
it would be great if we can use pattern to lock the app, while the app could remember password for database encryption for some limited time. 

So if I open Authenticator Pro 10 times during 20 minutes, It's anoying to write password 10 times. Pattern is much faster to enter. 

Thank you for the app.

**Comment by jamie-mh** [comment]
Since the app database is encrypted with a password, the pattern would need to translate to a password somehow.
I have doubts on the security of this, so I'm not looking to support right now.
