### ISSUE TITLE
Allow showing the password after an incorrect login attempt

### ISSUE THREAD

**Issue by b3nj5m1n** [jamie-mh/AuthenticatorPro#437]
**Is your feature request related to a problem? Please describe.**
I often have a typo in my password, when I try to login, I get an error. Obviously, I don't know where exactly I made the typo, so I have to show the password.
Currently, I have to make some change to the input to get the reveal password button back, like adding a random character and deleting it again.

**Describe the solution you'd like**
I'd like to be able to click on the red exclamation mark indicating failure to reveal the password, or something along those lines.

**Additional context**
It's a rather small thing and easy to work around, but because of how frequently this happens to me, it's got quite annoying.

**Comment by jamie-mh** [comment]
Thanks for pointing this out. Fixed in 7945662.
