### ISSUE TITLE
WearOS displaying wrong code 

### ISSUE THREAD

**Issue by ksuxtc** [jamie-mh/AuthenticatorPro#44]
Let me start by saying I am very grateful that you have provided Wear OS compatibility. Having 2FA on my wrist was the primary reason I bought a smartwatch, and I bought it just in time for Google Authenticator to drop support.

The issue I'm having is the app works fine for awhile on Wear OS, then after some time when I select a different login, the generated code does not work. A reboot of the watch seems to resolve the issue, temporarily. After the second time today, I opened the app on my phone and compared to the watch and noticed the generated code was actually for a different login, the login I had used earlier in the day. After some more fiddling I found that when I select an account on the watch it does show the correct code for a split second, then shows the incorrect code again. I realize that is probably clear as mud, but I'm not sure how else to explain the issue.

An example scenario:
I have 10 logins loaded into the app.
At 1:00pm I select login 2, it generates a working code.
At 3:30pm I select login 1, for a split second it shows a working code, then immediately starts showing the code for login 2.
Selecting any of my other logins (3 through 10), also show a correct code for a split second, then immediately shows the code for login 2.
Selecting login 2 shows a working code.
The logo and login names are always correct regardless of what I select, just the generated code is incorrect.

I am not a developer, but I don't feel like it's a functionality issue, just maybe a display issue.

Worth noting that the app on my phone is working flawlessly.

The app was downloaded and installed from the Google Play Store.

Watch details:
Fossil Sport 1033
Wear OS 2.17

Phone details:
Samsung Galaxy S7 SM-G930V
Android version 8.0.0

Thanks!

**Comment by jamie-mh** [comment]
Hi @ksuxtc ,

Thanks for your detailed report. I've been informed about this issue before but I have not been able to reproduce it on my end, it seems like a very subtle bug but I have an idea where it might come from.

In your example scenario, is login 2 the first one in the list?

**Comment by ksuxtc** [comment]
Login 2 is the second on the list. To simplify the scenario, my login numbers correspond to their placement on the list.

**Comment by jamie-mh** [comment]
Hi @ksuxtc ,

The reason I ask is the fact that it always shows the second code in the list seems rather arbitrary, if it were always the first one it would make more sense from a software bug perspective.
Anyway, in the latest update (1.9.2), I've made a few changes to the Wear OS app that might make a difference. I don't know if it fixes the bug though.

It should be available on Google Play once it passes review. I'll leave this issue open for the time being.

**Comment by ksuxtc** [comment]
I understand, and maybe my example doesn't clarify it, but it is the first
login that I use that has the persisting code. In my example, the first
login I used happened to be number 2 on my list. If I had run the 10th on
my list first, then number 10's code is the persisting code.

**Comment by ksuxtc** [comment]
After updating to version 1.9.3 and using it for a couple of days, the issue appears to be resolved. Thank you very much for you quick support and expertise!
