### ISSUE TITLE
Add more icons

### ISSUE THREAD

**Issue by ciotorcristian** [jamie-mh/AuthenticatorPro#440]
Please fill out the fields below where applicable:

**Name of website / service**
- Advcash
- Cake DeFi
- Celsius
- Cisco
- Hodlnaut
- Sony
- Trading 212

**Link to high-quality icon**
- https://iconape.com/wp-content/png_logo_vector/advcash-logo.png
- https://www.cakedefi.com/downloads/press-materials/cake/mark/mark-cakedefi-rgb.png
- https://pbs.twimg.com/profile_images/1491178826537254916/8JRQDuX0_400x400.jpg
- https://cdn.freelogovectors.net/wp-content/uploads/2016/12/cisco_logo.png
- https://miro.medium.com/max/3150/2*yPQl1kjZsNFTzJhl6gcNEQ.png
- https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Sony_logo.svg/1280px-Sony_logo.svg.png
- https://play-lh.googleusercontent.com/fHfTlNIq5PMps_296XPMC2N-u5ARCmaSM_lNuukKjhK8ITbHHS5YyYyT5ABJU1s8_Q

**Comment by RobertHarnett** [comment]
I have created all these icons and will add my pull request for this change very soon.

**Comment by RobertHarnett** [comment]
These have been added with #446
