### ISSUE TITLE
Duo support

### ISSUE THREAD

**Issue by ThatOneCalculator** [jamie-mh/AuthenticatorPro#444]
The ability to add HOTP codes from Duo would be great.  There's already code to process the HOTP: https://gist.github.com/fifty-six/80fa6f9d18952ec21253fc10d1c9d548 and a working implementation: https://github.com/AvikRao/duo-extension.

When I tried to add the key directly via the HOTP method it simply said the key wasn't valid.

**Comment by jamie-mh** [comment]
Duplicate of #351.
That QR code requires activation with a server. Since the app doesn't have Internet access, that won't be possible unfortunately.
