### ISSUE TITLE
Add "Show password" icon when backing up database

### ISSUE THREAD

**Issue by erazemkokot** [jamie-mh/AuthenticatorPro#45]
When backing up the database encrypted, the password prompt doesn't show an option to view the password, which can in case of long and complex passwords lead to un-restorable databases (speaking from experience).

Scenario: You backup your database with a (longer) password, but accidentally miss a symbol. When trying to restore the database, the app says the password is either incorrect or the file is corrupted - you just lost your passwords.

In my case I have multiple backups from multiple apps which saved me from quite some trouble, but I think an option to see the password (the little eye icon) before backing up the file to check if it's correct would benefit a lot of users.

**Comment by jamie-mh** [comment]
Hi @erazemkokot ,

Agreed, this makes sense. Added in 1242ae3.
