### ISSUE TITLE
Ubisoft account support

### ISSUE THREAD

**Issue by dansou901** [jamie-mh/AuthenticatorPro#47]
First of all thanks for this great app! Since Google removed Wear compatibility from their app, this is the only real alternative.
To my problem: Trying to add my Ubisoft login, I get "wrong formatted qr code" or similar. When trying to enter the key manually, the codes are wrong. Is this something you can fix or is it something only Ubisoft can fix?
Regards,
dansou901

**Comment by jamie-mh** [comment]
Hi @dansou901 ,

I have just tested setting up 2fa on my Ubisoft account and I am not able to replicate the issue.
There are a couple of things to check:

- Are you running the latest version of the app (1.9.3)?
- Is the time correct on your device? It can't be off by more than 30 seconds or else the codes will be wrong.

Let me know if this works for you.
Thanks.

**Comment by dansou901** [comment]
Just saw that you pushed an update which I haven't installed yet. I'll try again and let you know.
