### ISSUE TITLE
Challenge-Response (Yubikey)

### ISSUE THREAD

**Issue by danube** [jamie-mh/AuthenticatorPro#478]
Not sure if this has been asked already before, at least I could not find anything related. I just wanted to raise the idea of supporting challenge-response, hence the support of Yubikey, to load the database. That would be a nice thing.

**Comment by jamie-mh** [comment]
This would be a cool feature but unfortunately the Yubikey SDK for .NET doesn't support Android at this time.
[https://docs.yubico.com/yesdk/users-manual/getting-started/how-to-install.html](https://docs.yubico.com/yesdk/users-manual/getting-started/how-to-install.html)
