### ISSUE TITLE
Adding new icons + version number + search Option + misc

### ISSUE THREAD

**Issue by Engel1ST** [jamie-mh/AuthenticatorPro#48]
Good evening,

First sorry to not put this request in "Pull requests" but I really dont know how to do that !

**New icons :** 
Can you add theses icons please:
- [Altaro](https://www.altaro.com/)
- [Funio](https://funio.com/)
- [Square](https://squareup.com/us/en/)
- [TBS Internet](https://www.tbs-internet.com/)
- [Wasabi](https://wasabi.com/)
- [ZyXEL](https://www.zyxel.com/)

**Version Number:**
Is it possible to add somewhere in the software (example in the bottom of the menu), the apps version number?
That can be interessing to know if this is the latest version or not.

**Search Option:**
Can you please add the possibilite to search in the username ? Actually, the search in only working for the Emitter and not the Username. A dropdown option in the menu with "Search in :" and "Emitter/Issuer" or "Emitter/Issuer & Username" can be an idea.
I've a lot of OTP from customer and I put the description of the service in the Issuer. So I have for example 15 Instagram with the same name but the only difference is the username. I wish to have the possiblitie to search in it.

**Misc:**
Can you add a "ghost" categorie to sort all uncategorized/non categoried. I've more than 60 OTP and some are not categorized and I dont want to open them one by one to correct that.

Thank for everythink in all of case! Love to use this apps daily.

Alex.

**Comment by jamie-mh** [comment]
Hi @Engel1ST ,

Don't worry, this is in the right place. Pull requests are for merging code into the repository.
I'll add the icons and look into the features you suggested.

**Comment by Engel1ST** [comment]
> ll add the icons and look into the features you suggested.

As always thank for your help and your great software!

Have nice week-end.

Alex.

**Comment by jamie-mh** [comment]
Hi @Engel1ST ,

Thanks for your kind words. Some of the features are now available in the latest version of the app (1.10.0).

- I've added all the icons except TBS Internet, I can't find an icon that works well enough, maybe it is too niche?
- The about screen (Menu > Settings > About) now shows the version number at the top.
- A search now includes both the issuer and username fields, so you can type one or the other.
- I haven't found an elegant solution for showing uncategorised items, but I will look into it further.

**Comment by Engel1ST** [comment]
Hello Jamie,

Thank you so much for all requests that you included in your awsome software. I will earn time for sure. No problem for TBS! Maybe you can create a filter "uncategorised" as you mentionned.

Wish you a great day.

**Comment by LibreFoss** [comment]
Add the nordPass and nordlocker icons

**Comment by jamie-mh** [comment]
I've added the icons. Please create a new issue in future instead of commenting on an existing one.
