### ISSUE TITLE
Wear OS: App Name

### ISSUE THREAD

**Issue by upD8R** [jamie-mh/AuthenticatorPro#485]
Hi there,

I'm using the app on phone and watch, both set to German language.
For whatever reason in the watch the app is called "Authentifikator" instead of expected "Authenticator Pro".

Is there any reason for this or is this just a strange translation issue?

Thanks!

**Comment by jamie-mh** [comment]
Hi @upD8R ,

The translations are from contributors on [Crowdin](https://crowdin.com/project/authenticator-pro). Managing the correctness and consistency of all the languages is a little outside of my area of expertise :)

By default, it should display the word "Authenticator" by itself. In your opinion, is it best to use the English or German word?

Thanks

**Comment by upD8R** [comment]
Hi @jamie-mh ,

thanks for your response. I'd appreciate the English naming here.
It's interesting that in my phone it indeed uses the original/English name, this funny German translation only appears on the watch - both devices set to German.

I see where this translation [comes from](https://www.deepl.com/translator#en/de/authenticator) but the result is a word, which nobody uses or knows. I suggest to use "Authenticator" as "proper name" also for German, noone would translate e.g. "Uber" to "Über" in German.

Cheers.

**Comment by matt873** [comment]
Can't see cloud backup option. Why it's listed in it's features?
