### ISSUE TITLE
Authy account deletion: clarification

### ISSUE THREAD

**Issue by achilleas-k** [jamie-mh/AuthenticatorPro#488]
The [Import from Authy](https://github.com/jamie-mh/AuthenticatorPro/wiki/Importing-from-Authy) wiki page states that

> Because of the way Authy generates codes, you are not able to delete your Authy account as this invalidates the secrets.

Is this true only for the 7-digit Authy codes or does it also include 6-digit TOTPs?
I would imagine it doesn't matter for the standard TOTPs, in which case the wiki page could be edited to make it clear, though I'm not entirely sure.

**Comment by jamie-mh** [comment]
Yes, you are correct. This only applies to the 7 digit codes for sites such as Twitch as they're proprietary.
Regular TOTP is unaffected as it relies on a shared secret and not Authy services.
I'll update the wiki to clarify this.
