### ISSUE TITLE
Can't import Authenticator Plus database

### ISSUE THREAD

**Issue by ghost** [jamie-mh/AuthenticatorPro#49]
I exported the database and when I try to import it through Authenticator Pro I get an error saying that either the password is incorrect or the db is corrupt. I tried several times and I'm sure that both the password is correct and the db is not corrupt.

Am I missing something?

**Comment by jamie-mh** [comment]
Hi @sinfuldreamer ,

If I understand correctly, you are trying to import a backup from another app. I'm afraid that won't work. 
Importing other backup file formats is not supported.

**Comment by swanknight** [comment]
> 
> 
> Hi @sinfuldreamer ,
> 
> If I understand correctly, you are trying to import a backup from another app. I'm afraid that won't work.
> Importing other backup file formats is not supported.

You are correct. I guess I misunderstood. In any case, is there a way to import data from txt/html?
