### ISSUE TITLE
My proposed branding update

### ISSUE THREAD

**Issue by RobertHarnett** [jamie-mh/AuthenticatorPro#494]
Hello! It's me again. I'm not a developer but rather a hobbyist graphic designer, hence my constant updates to the icons. I felt it was about time I contributed some of my time to open-source software. Well because I like playing around designing things, I decided to have a shot at re-doing the branding used for Authenticator Pro. 

Below is my attempt at this:

![Example of my proposed rebrand.](https://raw.githubusercontent.com/RobertHarnett/AuthenticatorPro/master/doc/Rebrand%20Example.png)

This is just a general branding refresh idea I had. Notice the updated icon that really shows a true sense of the light hitting it, a simple 'clay' phone model that incorporates the screenshots as well as Authenticator Pro's trademark blue. 

I would love to continue this further and create new images and branding for the Playstore listing of the app, I just want to hear your thoughts on this and any potential feedback you might have?

If you have any suggestions, ideas or want me to change things I would be more then happy to have back and fourths with you to get something you're both happy with and want to represent your app.

**Comment by jamie-mh** [comment]
Hi @RobertHarnett ,

Thanks for working on this, it looks really nice!
If you feel confident working on any more pieces of branding, then that would be great. I can provide some high-res screenshots if necessary. Just a couple of ideas:

- The blue in the icon is closer to a cyan, it's a different hue to the one in the screenshot.
- It might be best to showcase the regular view mode, it's less functional but looks nicer in screenshots :)

Let me know your thoughts.
Cheers

**Comment by RobertHarnett** [comment]
Yay glad you like them!

I would be more then happy doing more pieces, I really enjoy doing these kind of things.

You were spot on about the cyan-blue issue. I was both using the colours of the old logo and I also hadn't clocked that while the apps default theme is 'Light Blue' that the screenshots I was using to make this were using the 'blue theme' hence the slightly different hue. 

I've tweaked the logo a smidge to focus more on the blue and remove that slight green tint of the old V1 version. I have also softened the shadows of the layers a little bit making it more subtle and done a couple of minuscule refinements to just generally polish it up a little bit more.

![Logos](https://user-images.githubusercontent.com/18248672/182673581-8f836901-81f5-4c44-9afa-beaaa418a584.png)

I also did some more work on the devices to be used in the branding that harmoniously follow the same style. Loosely based off the Pixel Watch, Pixel 6, and I did the tablet in the proportions of the iPad Pro 11" (I know... I'm sorry).

![Devices](https://user-images.githubusercontent.com/18248672/182674307-55e2cafc-157b-495a-a1ae-51a7d0963153.png)

Unfortunately because the app it annoyingly secure I discovered early on it's nigh impossible to get a screenshot, even via weird methods. I assume the only way to get one is to run the app in Android Studio and use a [2FA code generator tool,](https://stefansundin.github.io/2fa-qr/) to get what I need? If that is the way then let me know and I’d be happy to play about to get what I need, unless you know of a easier way?

Again any issues, suggestions, or if you want to go a totally different direction with the projects branding then don’t hesitate to let me know.

**Comment by jamie-mh** [comment]
Hi again,

I like the changes to the icon. It might need some form of background to work as an [adaptive icon](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive). It could be white, though.
The screenshot frames are very clean and modern.

As you've discovered, the app uses the secure flag to prevent screenshots. The only way to take them is within the emulator.
There is a [demo backup](https://raw.githubusercontent.com/jamie-mh/AuthenticatorPro/master/extra/backup_test/demo.authpro), it's the one used in the current screenshots. You can also enter secrets in manually, you can write anything in the field it will work for a test.

Thanks again!
