### ISSUE TITLE
Wear OS default code

### ISSUE THREAD

**Issue by mnowok** [jamie-mh/AuthenticatorPro#50]
I think it would be quite a nice feature to show default authentication code of selected (or last used) authentication code on Wear OS app. I have one (google) authenitication and WearOS app requires to tap this provider, than it shows the code.  Even if I have more authentication providers there is a chance one of them would be used most of time. I remember Google Authenticator for WearOS was showing the last code immediately (maybe I was using it with one auth only). This option (of opening last auth code) should be configurable on the watch because somebody may not like this feature.

**Comment by jamie-mh** [comment]
Hi @mnowok ,

This use case seems quite niche in all honesty. If you drag your most frequently used authenticators to the top of this list, this will certainly make them easier to select quickly. Let me know if this works for you.

**Comment by mnowok** [comment]
Maybe you're right but I mostly need auth code for my home QNAP device and both old Google Authentivator and Authenticator Plus works this way.  Anyway it was a suggestion - I don't think it is a hard task to give an option to show last used authenticator code on watch, but it is your project :-) Maybe only a few users would enable it but as your project is open source I suggested some minor feature improvement.

**Comment by jamie-mh** [comment]
Due to popular request, this is a feature in 2.3.1.
