### ISSUE TITLE
Generate TOTP on tap instead of default intervals

### ISSUE THREAD

**Issue by mattiaverga** [jamie-mh/AuthenticatorPro#507]
I may be wrong, but as far as I know TOTP have a validity of a certain amount of seconds (usually 30) from the time it is generated.
What I find annoying about AuthenticatorPro is that TOTPs seems generated at default intervals: for example, I need an OTP, I open the app and I find that the current TOTP is valid only for a few seconds, so I need to wait these seconds to get a new one to have the time to copy or manually enter it where I need it.

If my first assumption isn't faulty, I'd like to have AP to generate the TOTP when I tap the authenticator to reveal the code, so that I don't have to wait 5 / 10 seconds more to get the new one.
If my understanding of how TOTP works is wrong, feel free to trash my request...

**Comment by upD8R** [comment]
You may take a look to RFC 6238. Timesteps are predefined, usually 30s. And those 30s are the same on the client (but the client usually compares with one step back and 2 steps forward, if I'm not mistaken). So I don't think think you would earn much.

**Comment by mattiaverga** [comment]
Yup, mine was a stupid request, after all. I was not aware about the server would (should) accept the TOTP from the previous time window.
