### ISSUE TITLE
Time Sync

### ISSUE THREAD

**Issue by gjf** [jamie-mh/AuthenticatorPro#508]
**Is your feature request related to a problem? Please describe.**
According to [FAQ](https://github.com/jamie-mh/AuthenticatorPro/wiki#frequently-asked-questions) the problem is quite clear: when the time on device is not correct the codes cannot be generated in a proper way.

**Describe the solution you'd like**
To add a time sync option similar to [Google Authenticator](https://support.google.com/accounts/answer/2653433?visit_id=637906474371614933-2503988291&p=timesync&rd=1&hl=en).

**Additional context**
Some advanced users enjoy having an alternative time on device. That's why "local" time syncing that is used for AuthenticatorPro contect only will be preferrable. Actually it is exactly what Google implements - please see above.

**Comment by jamie-mh** [comment]
Unfortunately, this would require Internet access for an NTP sync. There are currently no plans to enable the Internet permission in the app.
