### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by stbxxl** [jamie-mh/AuthenticatorPro#512]
Will the new release version 1.16.0 be available through the Google Play store or do I have to manually update it with the apk file available here?

**Comment by jamie-mh** [comment]
Hi @stbxxl ,

The update has been under review by Google for the last 2 weeks. I have no idea when it will be approved unfortunately :(

**Comment by jamie-mh** [comment]
The Wear OS app (and therefore the entire update) has just been rejected. It might be a while until the 1.16.0 is available.

![image](https://user-images.githubusercontent.com/7887162/187017765-25b5173d-da52-48e4-83c2-2b64a76f61aa.png)

**Comment by stbxxl** [comment]
Thanks for the update. I appreciate that it's a hassle to get apps approved in Google Play. Do you recommend a manual update via the apk file available on Github? Or will this create an issue with later updates through Google Play?

**Comment by jamie-mh** [comment]
In order to install an APK from GitHub, you will need to uninstall the Google Play version. They have different version codes and signatures, so they don't work together.
I've appealed the rejection, I'm hoping that the release will be available soon.

**Comment by stbxxl** [comment]
I still don't see an update on Google Play. What is the recommendation how to get the latest version?

**Comment by jamie-mh** [comment]
Hi @stbxxl ,

After over 1 month of waiting, I'm please to announce that the latest version has been approved by Google and is now available 🎉.

Cheers
