### ISSUE TITLE
Add icon for Bugzilla@Mozilla

### ISSUE THREAD

**Issue by xmha97** [jamie-mh/AuthenticatorPro#515]
Please add an icon for the Bugzilla@Mozilla

**Comment by RobertHarnett** [comment]
This can be closed. I have added it in #521.

**Comment by xmha97** [comment]
Thanks 🙏
Will this update be released in Play Store?

**Comment by RobertHarnett** [comment]
It will eventually, It has to me merged first and then whenever @jamie-mh sees fit the build will be put on the Playstore.

**Comment by jamie-mh** [comment]
Added in #521.
