### ISSUE TITLE
Icons request

### ISSUE THREAD

**Issue by D0geDev** [jamie-mh/AuthenticatorPro#527]
https://mail.ru/ - 30 rank
https://www.pochta.ru/  - 1,721 rank
https://www.faceit.com/ - 3,945 rank
https://gameguardian.net/forum/ - 17,202 rank
https://enot.io/ - 64,090 rank
https://www.obsidian.net - 92,795 rank

**Comment by DogeeDev** [comment]
https://bhf.im/ - 73,723 rank

**Comment by DogeeDev** [comment]
https://wallet.wax.io/ has no rank but the main domain wax.io has 19,438 rank

**Comment by jamie-mh** [comment]
All the icons except BHF (no high-quality icon) have been added and will be available in the next release.
