### ISSUE TITLE
Edit item info

### ISSUE THREAD

**Issue by Galacticai** [jamie-mh/AuthenticatorPro#537]
**Is your feature request related to a problem? Please describe.**
After adding an account, it's not possible to change the account email, or other info,  without deleting the entry completely (losing 2FA key)

**Describe the solution you'd like**
Allow changing all the info of an item, including the secret key, email.. etc..

**Additional context**

Example: (in [Aegis Authenticator](https://github.com/beemdevelopment/Aegis))

<img height=480 src="https://raw.githubusercontent.com/beemdevelopment/Aegis/master/metadata/en-US/images/phoneScreenshots/screenshot3.png" />

**Comment by jamie-mh** [comment]
You can use the three dots menu to change the issuer and username. What is the use case for changing the other details?

**Comment by MagicLike** [comment]
If something changes, something is misstyped (e.g. when manually adding an entry) or if you just would want to tinker with the settings...

**Comment by Galacticai** [comment]
As @MagicLike mentioned... It is very useful to have more flexibility.

I had so much time used up to set up AuthenticatorPro because I was migrating from several auth apps to this 1 app which meant I had to test and make sure everything is 100% correct (and change details all the time... a lot).

I did that process with Aegis before I came to AuthenticatorPro and it was so much easier and faster.

But I stayed with AuthenticatorPro because you did a great job making it look good. 💯

**Comment by MagicLike** [comment]
Any updates on this?

**Comment by Ryonez** [comment]
A QR code is handy, but some things just won't take that. If you're against users changing the secret without deleting the entry, I'd ask the the secret at lest be displayed in a field you can copy from alongside the QR Code.

The current setup is limiting for no reason.

**Comment by jamie-mh** [comment]
The main gripe I have with this feature is that it gives people the impression that they can just change a parameter, such as the expiration time, and it will just work. Clearly, to those in the know, the server and client parameters must be identical.

It seems that what this issue boils down to, is just to have the ability to copy the secret key, not necessarily change it.

**Comment by Ryonez** [comment]
I can see use cases in being able to edit them. For example, I tend to deal with the secret keys, and when changing them on a service I tend to just change the keys rather than recreate the entry.

If you're worried about users getting the wrong impression, maybe add an advanced mode with a warning, that allows advance entry editing? I'm not really in favour of dumbing things down for everyone just because some don't understand something.

**Comment by jperezruiz** [comment]
> I can see use cases in being able to edit them. For example, I tend to deal with the secret keys, and when changing them on a service I tend to just change the keys rather than recreate the entry.
> 
> If you're worried about users getting the wrong impression, maybe add an advanced mode with a warning, that allows advance entry editing? I'm not really in favour of dumbing things down for everyone just because some don't understand something.

Good suggestion, something like developer mode in android, to explicitly enabling more advanced features with a warning.

**Comment by jamie-mh** [comment]
Added in version 1.20.0
