### ISSUE TITLE
Implement sorting options "Last used" and "Most used".

### ISSUE THREAD

**Issue by MagicLike** [jamie-mh/AuthenticatorPro#547]
**Is your feature request related to a problem? Please describe.**
Since I have many accounts stored in AuthPro, I have to do a lot of searching and scrolling to find the accounts I use the most.

**Describe the solution you'd like**
As already implemented in [andOTP](https://github.com/andOTP/andOTP) (Unmaintained), there are sorting options to order the accounts by the most recently used and the most used. It would be nice if this could also be implemented in AuthPro.
(Technically, I could also just sort the accounts manually, but that would not adapt dynamically.)

**Comment by happenpappen** [comment]
I recently switched from andOTP to AuthenticatorPro and this is one of the two andOTP features i miss most. It would be very useful from my point of view to have the option to change the sort order of the account list from alphabetically to most/least used.

**Comment by MagicLike** [comment]
Fixed in https://github.com/jamie-mh/AuthenticatorPro/commit/65aa57135307420e294c7d292e5cc8cfed7088ee
