### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by Schokobecher** [jamie-mh/AuthenticatorPro#55]
Would it be possible to add translations to the App?
I could contribute to German and Thai localization.

Crodwin/.po files/strings whatever floats your boat @jamie-mh  :smile:

**Comment by jamie-mh** [comment]
Hi @Schokobecher ,

There is already a German localisation on the app. You can certainly add a Thai translation, if you create a `values-th` strings file and make a PR, I will add it to the app. Although, I have no way of checking the accuracy of the translation, as I don't know any Thai :)

**Comment by Schokobecher** [comment]
Ok, no problem.

Going forward, maybe something like Crowdin would enable more people to participate? No PR's needed, which also attracts people outside of the GitHub _scene_

**Comment by jamie-mh** [comment]
The Google Play description isn't that important, I generally tweak it regularly so it might not be worth translating.
Good idea, I will look into creating a Crowdin project for the app.

**Comment by Schokobecher** [comment]
Great, then I'll wait for that so someone else might be able to verify what I've translated :)
Just ping me once ready

**Comment by jamie-mh** [comment]
Hi @Schokobecher ,

I've created a project on Crowdin, you can join it with the auto-invite link [here](https://crwd.in/authenticator-pro).

**Comment by Schokobecher** [comment]
That was fast!

**Comment by martinsefcik** [comment]
@jamie-mh How can I request new language (Slovak) to be added on Crowdin or do you prefer PR here ?

**Comment by jamie-mh** [comment]
Here is fine. I've added Slovak to the list of languages on Crowdin.

**Comment by martinsefcik** [comment]
@jamie-mh Thanks for adding. Slovak should be ready for release ;-)

**Comment by jamie-mh** [comment]
Thanks for contributing!

**Comment by comradekingu** [comment]
Happy to help setting up shop on a Weblate instance.
