### ISSUE TITLE
Translating the project further

### ISSUE THREAD

**Issue by MagicLike** [jamie-mh/AuthenticatorPro#550]
I would like to start translating the project further, for example the README or the CONTRINUTING.md, etc.... (Maybe even the wiki).
In my case they would be translated into 🇩🇪 German, but I'd like more people to join in and translate them into their native languages.
Is that okay?

**Comment by MagicLike** [comment]
Any updates on this?

**Comment by jamie-mh** [comment]
Hi,

As far as I know, you can't change the language of the GitHub interface. It makes sense to keep everything in English for the time being.

Cheers
