### ISSUE TITLE
Push Authentications

### ISSUE THREAD

**Issue by KarmaPoliceT2** [jamie-mh/AuthenticatorPro#552]
**Is your feature request related to a problem? Please describe.**
I have several apps which setup push based authentication through duo and okta verify... these seem to not work with authenticator pro

**Describe the solution you'd like**
Would it be possible to enable these push based accounts inside authenticator pro.

**Additional context**
It appears to be possible technically (at least for okta, i'm not sure how fragmented these push-based technologies are) as seen here: https://developer.okta.com/docs/guides/authenticators-custom-authenticator/android/main/

Just looking for insight as to whether this is possible at all and if it is, would you be considering adding it to this application? I love the app for everything else and would really like to consolidate away from these other authentication apps.

Thanks!

**Comment by WeirdAlex03** [comment]
I'm not sure if Duo push notifications specifically could be implemented, but after doing some research, it seems Duo's HOTP codes can be added to the app relatively simply.

This blog post goes over the process in good detail, which would be good for implementing it as a source (or if you want to manually add it as a login): https://shreyasminocha.me/blog/duo-mobile-2fa/
The linked F-Droid app (DuOTP) is a really easy solution for automatically adding a Duo HOTP login: https://f-droid.org/en/packages/net.scintill.duotp/
