### ISSUE TITLE
Crashes on backup

### ISSUE THREAD

**Issue by Mokura** [jamie-mh/AuthenticatorPro#56]
App crashes on trying to back up codes due to missing storage permissions, with no apparent way to grant it.  Version 1.10.0

![Screenshot_20201008-112858_Permission_controller](https://user-images.githubusercontent.com/5167919/95480942-78017480-095a-11eb-8614-b84dd7afb4c6.png)

**Comment by jamie-mh** [comment]
Hi @Mokura ,

The reason why you are not able to grant the storage permission, is that the app doesn't require it. The file saving is handled by using the built-in file saving dialog. This probably isn't the source of the crash.

I cannot reproduce this bug, can you describe the circumstances of the issue (when exactly the crash occurs for instance). And if possible a crash log.

**Comment by Mokura** [comment]
It crashes if com.android.documentsui is missing or disabled (if you're mainly using another file manager, for example.)  It didn't seem to detect Material files (https://f-droid.org/en/packages/me.zhanghai.android.files/) until Documents UI was reenabled, and it didn't detect Simple File Manager (https://f-droid.org/en/packages/com.simplemobiletools.filemanager.pro/) at all.  Logcat filtered to "AuthenticatorPro" attached. 
[2020-10-09-09-58-55.txt](https://github.com/jamie-mh/AuthenticatorPro/files/5355412/2020-10-09-09-58-55.txt)

**Comment by jamie-mh** [comment]
The Android Storage Access Framework is an integral part of the operating system. If you go out of your way to disable it then, it's going to break a lot of stuff. If you absolutely must change the default document provider, you will need to [setup a new resolver](https://android.stackexchange.com/questions/210143/alternative-file-open-not-stack-documentsui-for-whatsapp/210168#210168) for the `ACTION_CREATE_DOCUMENT` intent.
