### ISSUE TITLE
Can restore from OneDrive but not backup to OneDrive

### ISSUE THREAD

**Issue by exterrestris** [jamie-mh/AuthenticatorPro#57]
When creating a backup, the only options that show up are the Downloads folder, my SD card, and two Google Drive accounts (I have two Google accounts on this phone). However when restoring a backup, I also get the option to select OneDrive.

Whilst backing up to Google Drive is acceptable, and of course I can manually copy the file to OneDrive, I'd much prefer to backup to OneDrive directly if possible

**Comment by jamie-mh** [comment]
Hi @exterrestris ,

Unfortunately, this is a problem with the OneDrive app. It doesn't yet support the standard Android protocol to save files : [GitHub issue](https://github.com/OneDrive/onedrive-api-docs/issues/1134). Google Drive, Nextcloud, etc... all support it so OneDrive is an outlier in this regard. I have no idea if they're planning on implementing it.

**Comment by exterrestris** [comment]
Ah, OK. Hopefully OneDrive will implement it at some point.
