### ISSUE TITLE
Please add support for "Entrust Identity"

### ISSUE THREAD

**Issue by daveloyall** [jamie-mh/AuthenticatorPro#572]
Hi.  There is an app out there called Entrust Identity.  Here is their [support page](https://www.entrust.com/resources/identity-and-access-management/support/entrust-identity-app).

Some work (I think all the work that is necessary, and more!) has already been done to parse their QR codes.  See the [entrust-identityguard-tools repo](https://github.com/ss23/entrust-identityguard-tools).

Please add support for this app to Authenticator Pro.

**Comment by jamie-mh** [comment]
Since this appears to be an enterprise 2FA solution, I would not be able to validate any implementation of this reliably. I don't plan on supporting this at this time.

Cheers
