### ISSUE TITLE
Request for additional icons

### ISSUE THREAD

**Issue by exterrestris** [jamie-mh/AuthenticatorPro#58]
Would you be able to add icons for the following services:

- [Bitdefender](https://www.bitdefender.co.uk)
- [Integromat](https://www.integromat.com)
- [AwardWallet](https://awardwallet.com)
- [Airtable](https://www.airtable.com)
- [Migadu](https://www.migadu.com/)
- [Nominet](https://www.nominet.uk/)
- [Gandi](https://www.gandi.net)
- [500px](https://500px.com)
- [Fanatical](https://www.fanatical.com)

Thanks

**Comment by Schokobecher** [comment]
If no one minds, I'm up for it :+1:

**Comment by jamie-mh** [comment]
Hi @Schokobecher ,

Sure, go ahead.
The design consensus is to avoid frames / backgrounds on the icons and to keep the icons in a simple flat style if possible.
Also, no need for a Gandi icon as it already in the app: https://github.com/jamie-mh/AuthenticatorPro/blob/master/AuthenticatorPro.Shared/Resources/drawable-xxxhdpi/auth_gandi.png

**Comment by Schokobecher** [comment]
### To do:
- [ ] Bitdefender
- [ ] Integromat
- [ ] AwardWallet
- [ ] Airtable
- [ ] Migadu
- [ ] Nominet
- [ ] 500px
- [ ] Fanatical

I'm not sure about **Nominet** and **500px**

This is the original **Nominet** logo:
![nominet](https://user-images.githubusercontent.com/1642634/95655341-c36d7b80-0b30-11eb-837e-3edd02e31835.png)


I guess stripping the wave effect around it would work, but it's a very generic N
![nominet_modified](https://user-images.githubusercontent.com/1642634/95655358-e6982b00-0b30-11eb-9140-aa08e7149d47.png)

For **500px** they have changed their logo back in 2016 to just their name:
![500px_logo](https://user-images.githubusercontent.com/1642634/95655383-1a735080-0b31-11eb-8895-04713a61132a.png)

I don't think it really works as an icon, but maybe I'm just biased :sweat_smile: 

While not official, the infinite symbol was closely associated with the old loge (as it made up the two 0's in the 500)
![image](https://user-images.githubusercontent.com/1642634/95655438-7f2eab00-0b31-11eb-970a-196309a192ae.png)

**Comment by jamie-mh** [comment]
I think you're right about the Nominet logo, it's not very distinguishable without the waves. It's probably best to keep them.

As for the 500px logo, I think it's preferable if we use the most recent version of the logo for the icon. People who started using the service after 2016 might not even recognise the old one. Their [iOS](https://apps.apple.com/us/app/500px-photography-community/id471965292) and [Android](https://play.google.com/store/apps/details?id=com.fivehundredpx.viewer) apps both use the text.
If the icon is too small, perhaps we could use the just the "500" or the "px" for icon?

It's always hard to determine what's best until it's tested in the app :)

**Comment by Schokobecher** [comment]
> It's always hard to determine what's best until it's tested in the app :)

Easier said than done :)
I've not yet found a way to build it on my Linux machine, and the Windows Box I forced VS2019 on was not very cooperative.
When building the entire Solution or AuthenticatorPro.Android can't resolve the values fro the colors.xml

**Comment by jamie-mh** [comment]
Icons merged in PR #59 .
