### ISSUE TITLE
From AndOTP export: The file could not be imported

### ISSUE THREAD

**Issue by brianjmurrell** [jamie-mh/AuthenticatorPro#590]
**Describe the bug**
Trying to import a plaintext JSON file exported from AndOTP results in _The file could not be imported_.

**To Reproduce**
1. Export from AndOTP
1. Try to import into AuthenticatorPro

**Expected behavior**
Should import.

**App Version**
1.16.2

**Comment by ipkpjersi** [comment]
Importing from AndOTP works fine for me FWIW.

**Comment by jamie-mh** [comment]
Due to the lack of activity, I'm closing this issue.
