### ISSUE TITLE
Option to transfer authenticator codes from google authenticator

### ISSUE THREAD

**Issue by sbeve72** [jamie-mh/AuthenticatorPro#60]
Let us scan the QR code the Google authenticator app shows when you click on the "export" option to transfer your authenticator info to this app. I use google authenticator and I wanna switch to this new all but I dont  wanna have to go through every single account's setting and set everything  up again.

**Comment by jamie-mh** [comment]
Hi @sbeve72 ,

You should be able to do this, what happens when you scan the QR code?

**Comment by sbeve72** [comment]
I am sorry i didnt realize i was supposed to use the normal scanning method for importing qr codes too. I thought there would he a separate option for that. anyways I couldn't try it since I accidentally cleared the data of my google authenticator app so I had to setup rebutting from
