### ISSUE TITLE
DS Logon

### ISSUE THREAD

**Issue by mherberg** [jamie-mh/AuthenticatorPro#604]
Please fill out the fields below where applicable:

**Name of website / service:**
DS Logon
https://myaccess.dmdc.osd.mil/identitymanagement/app/login

PS:
This is the DoD and Veterans universal login.
Here is the icon:
https://www.myhealth.va.gov/mhv-portal-web/documents/314545/444503/DS-Logon-Icon-Large.png/3b6c4fa5-d257-617a-451d-63f6372e8f89?t=1628528295771

**Comment by jamie-mh** [comment]
Added in 30fb0ae56d4c916bebe69d587ea6ca0ffb9c56cf
