### ISSUE TITLE
Add Screen Connect Logo

### ISSUE THREAD

**Issue by yakov116** [jamie-mh/AuthenticatorPro#608]
Thanks for this awesome app!

**Is your feature request related to a problem? Please describe.**
I would like to ask if you can please add the logo

**Describe the solution you'd like**
Sample URL: https://a.screenconnect.com/

Google play app: https://play.google.com/store/apps/details?id=com.screenconnect.androidclient

**Additional context**
![screenconnect](https://user-images.githubusercontent.com/16872793/209475172-a127fe9c-89f5-478f-ae3b-74c51e006e68.png)

**Comment by jamie-mh** [comment]
Added in 30fb0ae56d4c916bebe69d587ea6ca0ffb9c56cf
