### ISSUE TITLE
Scrolling in Wear OS app appears triangular, not circular

### ISSUE THREAD

**Issue by arm32x** [jamie-mh/AuthenticatorPro#61]
On a round watch, the list scrolls in a weird triangular way, with an abrupt change of direction in the center.  Could this be changed to match the way the home screen’s app list scrolls, which is more circular?

**Comment by jamie-mh** [comment]
Hi @arm32x ,

I haven't noticed this on my device. What device are you using?

**Comment by arm32x** [comment]
I'm using the black Puma smartwatch. It looks like this: ![Image](https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/929035/01/fnd/PNA/fmt/png/PUMA-Smartwatch)

**Comment by jamie-mh** [comment]
Fixed in 568278d. Icons now follow the curve of the screen.
