### ISSUE TITLE
Add option to hide account names

### ISSUE THREAD

**Issue by ylefebvre** [jamie-mh/AuthenticatorPro#616]
**Is your feature request related to a problem? Please describe.**
No, it is related to the visual appearance of the application.

**Describe the solution you'd like**
I would like to see an option to hide the account names when showing all of the items.

**Additional context**
I only have a single account for each service for which I use 2FA and in 95% of cases, my account name is my e-mail. Displaying the account name for each entry makes the interface looks very cluttered, especially when display in Tile view, which is my preferred viewing mode. Seeing the account name does not benefit me in any way. What I need to see is the name of the service and the authentication code.

Seeing account names can be useful for someone who has multiple accounts on the same service to differentiate between them, but this is not the case here.

Aegis Authenticator offers this option. However, I much prefer the tile display mode that Authenticator Pro offers.

**Comment by jamie-mh** [comment]
Added in version 1.20.0
