### ISSUE TITLE
Changes on multiple devices do not properly sync via backup/restore

### ISSUE THREAD

**Issue by makkonen** [jamie-mh/AuthenticatorPro#617]
**Describe the bug**
There seems to be an issue/race condition with the auto-backup/auto-restore function when changes are made from multiple locations. Some entries will end up on only one device, and will not sync. I'm using syncthing to sync the backups folder, but I think this would happen with any sort of asynchronous sync tool.

**To Reproduce**
1. Enable automatic backups and automatic restores on Device A and Device B
2. Put both devices in airplane mode
3. Scan otpauth code X on Device A. (new backup is created, with timestamp 1)
4. Scan otpauth code Y on Device B. (new backup is created, with timestamp 2, more recent than timestamp 1)
5. Close Authenticator Pro on A & B.
6. Turn airplane mode off. The backups will sync.
7. Re-open Authenticator Pro on A & B.

At this point, things got weird. I expected 1 device to auto-restore, but neither did. When I went into settings and manually restored, both said "nothing to restore". I waited a couple minutes, force quit, reopened and tried again, device A auto-restored, and then showed entries X & Y, but device B still said "nothing to restore" and only showed entry Y.

I then deleted entries X & Y on device A (creating a new backup with timestamp 3). I restored backup on device B. It said 0 entries & 2 groups updated, but after doing so still showed entry Y in the list.

**Expected behavior**
New entries X & Y should appear on both devices. Deleted entries should be removed on both devices.

**App Version**
1.16.2

**Additional context**
My testing was fairly minimal, I definitely have missed some edge cases.

I understand this could be a difficult problem and require (something like) storing timestamps for every update, so they can be interleaved from multiple backups and avoid these races. My only experience with this is with KeePass, which does something similar to allow merging from multiple databases or multiple dissimilar copies of the same database.

**Comment by jamie-mh** [comment]
Hi @makkonen ,

I expect this is not what you wanted to hear, but I've decided to remove the auto-restore option for now. It's clear that it doesn't work as many would expect, entries are never deleted, for instance. Furthermore, caching in the Storage Access Framework also causes many issues.

I hope to return to this at some point, but it seems that the Android storage APIs are not fit for this purpose.

Cheers
