### ISSUE TITLE
Custom theming

### ISSUE THREAD

**Issue by MagicLike** [jamie-mh/AuthenticatorPro#618]
**Describe the solution you'd like**
Something like an advanced option for completely custom theming, to be able to change every color variable on their own.

**Additional context**
I just think it would be nice to have the freedom of changing something like this.

**Comment by jamie-mh** [comment]
Hi @MagicLike ,

This isn't something that is easy to accomplish on Android unlike a webapp for instance. I can't see this been implemented.

Cheers

**Comment by MagicLike** [comment]
No problem, I just had athought and kinda saved it here ^^

But what about Material You? (Or would that also be difficult to implementate?)

**Comment by jamie-mh** [comment]
There is an issue open for Material You (#339). I've looked into implementing this, but I haven't been satisfied with the results so far. I just don't think it looks very good with the default settings. In the future, I may add an option to switch between Material 2 and Material 3.
