### ISSUE TITLE
"Scan" a QR code from a gallery image

### ISSUE THREAD

**Issue by Nowaker** [jamie-mh/AuthenticatorPro#62]
Reasoning: I can easily "export" QR codes in Google Authenticator by taking a screenshot of two big QR codes that contain all my 2FA sites.

But there's no way to "scan" them in Authenticator Pro. Providing an easy and effective mechanism for anyone to jump ship from proprietary authenicators to open source ones will surely increase our adoption.

**Comment by jamie-mh** [comment]
I agree, this is a useful feature. Implemented in 8d74f40.

**Comment by Nowaker** [comment]
Awesome! When is Google Play release planned?

**Comment by jamie-mh** [comment]
I'm not sure yet, there is still some stuff in the works that I want to put in the next release.
