### ISSUE TITLE
upon changing the theme from the app's settings, it doesn't show any effect unless the app is restarted.

### ISSUE THREAD

**Issue by sbeve72** [jamie-mh/AuthenticatorPro#63]
this doesn't happen if instead of changing the theme from the settings of the app i do it from the quick panel settings. then it happens immediately. only when i change the theme from within the app does it show that behavior.

**Comment by sbeve72** [comment]
accidentally closed it oof

**Comment by jamie-mh** [comment]
Hi @sbeve72 ,

Indeed, the theme doesn't update the moment the setting is changed, to make this work is tricky.
If you back to the main screen once you have changed the setting, does the theme update?

**Comment by sbeve72** [comment]
> Hi @sbeve72 ,
> 
> Indeed, the theme doesn't update the moment the setting is changed, to make this work is tricky.
> If you back to the main screen once you have changed the setting, does the theme update?

yes it does, thats interesting behavior.

**Comment by jamie-mh** [comment]
I've figured out a simple way of making it work. Fixed in dd48525.

**Comment by sbeve72** [comment]
awesome waiting for the playstore update.
