### ISSUE TITLE
Device credentials support

### ISSUE THREAD

**Issue by corobin** [jamie-mh/AuthenticatorPro#637]
**Is your feature request related to a problem? Please describe.**
I wish to encrypt my 2fa app database with the android device credentials and have the app require it to unlock on launch.

this has 2 main benefits:
1. security: it makes the database secured by the device and harder to separate from the device - the whole point of 2FA is to prove physical possession of a specific physical thing
2. convenience: it means that the app shares the android device authentication method, so if, for example, i change the android password, the 2fa app will automatically use it and do not require separate management of credentials

**Describe the solution you'd like**
Support device credentials for app locking and database encryption

**Additional context**

andOTP was the only major open source app that supported it but it is now unmaintained

FreeOTP has just migrated to the android keystore, but does not appear to have app locking functionality at all at present

Aegis authenticator seems to refuse to implement it because of concerns with reliability ([reference](https://github.com/beemdevelopment/Aegis/issues/212)), however, the situation on android side appears to have been *much* improved since before, and anyway andOTP deals with it by putting up a big warning about it upon configuration. i have had no problems using device credentials with andOTP.

despite the potential reliability issue, there is still a lot of value. 2FA tokens were never meant to be a SPOF in the first place, there should be backup codes saved separately for access recovery in case of token loss.

**Comment by jamie-mh** [comment]
Same as #666 probably.

You can already do this, as the database password is encrypted with your device credentials when you enable biometric unlock. You could in theory set a random password, and forget about it. However, the downside becomes clear when you change your biometric settings and the keys are invalidated. You will be locked out.

While you may accept and understand the risk, if I enable such as use case, I can foresee the issues flooding in with people locked out, no matter how many red warning signs are placed in front of them.

Cheers

**Comment by corobin** [comment]
just leaving this here for posterity/in case you revisit this in the future:

the device credentials is not just biometric. it can be used with e.g. pin, pattern, password... which authenticator pro does not currently support.

with andotp i have it using device credentials, and have changed my passcode without changing auth method multiple times without disrupting the andotp data store.
