### ISSUE TITLE
New Watch

### ISSUE THREAD

**Issue by toptaljj** [jamie-mh/AuthenticatorPro#639]
**Describe the bug**
I had to reset my watch, and the name changed.  I honestly can't remember what i had it named.  After restoring the google play version of Authenticator Pro on both phone and watch, i see the FAQ mentioned "blue cloud" and "No Authenticators" message.

**To Reproduce**
1. Setup a custom name for the watch in Wear app
2. Setup Authenticator Pro on both phone and watch
3. Enjoy Authenticator Pro on watch
4. Succumb to senseless "reset the watch" request by Verizon tech support
5. Install google play version of Authenticator Pro on watch and phone
6. Restore a backup
7. Find that the "blue cloud" and "No Authenticators" is still evident

**Expected behavior**
There should be a "sync settings to watch" or something, shouldn't there?  _Is it right in front of me?_

**App Version**
Phone version is 1.16.2 (can't see a version on the watch, but i [just installed it from google play](https://play.google.com/store/apps/details?id=me.jmh.authenticatorpro&hl=en_US&gl=US)

**Additional context**
I do have them connected in Wear and i also have them connected to the same Wi-fi.

**Comment by jamie-mh** [comment]
Hi @toptaljj ,

The latest release 1.17.0 brings some improvements to the reliability of the watch sync, both versions of the app must be updated.
Can you try it out when it becomes available to you?

Thanks

**Comment by dyslecix** [comment]
Same problem.

I reset my Galaxy Watch 4 (but not the phone - Galaxy S20 FE)

After re-installing Authenticator Pro on the watch, I get a blue cloud icon with "No Authenticators. Add some authenticators from the phone app". Authenticator Pro is open on the phone and I can see and access all my Authenticator Pro codes (25 of them).
But they don't show up on the Galaxy Watch 4.
