### ISSUE TITLE
The QR Code is not in the correct format or cannot be read

### ISSUE THREAD

**Issue by dvjones89** [jamie-mh/AuthenticatorPro#64]
**App version**: 1.11.0
**Android Version:** Android 11:
**Phone model**: Pixel 2

Hi there,

First of all, thanks for your hard work on an awesome project; it's great to see something like this open-source and the support for WearOS is much needed (and much appreciated).

I'm currently scanning my collection of QR code images and most import perfectly, though a handful consistently fail with the following message: 

```
The QR Code is not in the correct format or cannot be read.
```
Honestly, I'm not sure how to troubleshoot this further, though I hope posting here might be a step in the right direction.
Would it help if I sent across an example QR code that fails to import? I can always rotate the secret to make the code invalid.

Thanks in advance for any help you can offer!
Dave J

**Comment by jamie-mh** [comment]
Hi @dvjones89 ,

Thanks for reporting this issue.
There must be an edge case in the QR code reader that hasn't been considered. If you can send over an example code that doesn't work I should be able to figure out the issue relatively quickly.

**Comment by dvjones89** [comment]
Hi @jamie-mh 

Thanks for the speedy reply! As requested, I've just sent you an email to contact@jmh.me, attaching a `.png` image of a QR code that's failing to scan.

Thanks for your help and please let me know if you need any further information.

Cheers,
Dave

**Comment by jamie-mh** [comment]
Thanks @dvjones89 ,

I've figured out the issue, it didn't have anything to do with the format being incorrect. It was due to this code not having a username, which was handled incorrectly.
I'll push a new release with the fix soon.

**Comment by dvjones89** [comment]
What a hero, thank you, Jamie 🙏 Do you have a `buymeacoffee` or GitHub sponsor link where I can throw you a few ££?

**Comment by jamie-mh** [comment]
Thank you for the kind offer Dave, however I am not currently accepting donations for this project.

**Comment by dvjones89** [comment]
OK, well let me know if that ever changes, and I'll keep an eye out a "donate" option in any future releases. Thanks again for your help and contribution to the community.
