### ISSUE TITLE
Inclusion into FDroid.org repo

### ISSUE THREAD

**Issue by MagicLike** [jamie-mh/AuthenticatorPro#646]
Related to #576 

Explanation: https://github.com/jamie-mh/AuthenticatorPro/pull/576#issuecomment-1418019197

@jamie-mh @izzysoft

**Comment by jamie-mh** [comment]
Hi,

This is a duplicate of #2 . It's been a little stale until recently.

**Comment by MagicLike** [comment]
> Hi,
> 
> This is a duplicate of #2 . It's been a little stale until recently.

ooops ^^
