### ISSUE TITLE
Consider to switch to Codeberg

### ISSUE THREAD

**Issue by MagicLike** [jamie-mh/AuthenticatorPro#647]
**Is your feature request related to a problem? Please describe.**
- GitHub is
  - privacy-invasive
  - Microsoft-owned
  - proprietary
  - vendor-lock-in
  - Tor-hostile
- [GitHub Copilot™ attacks copyleft licensing](https://nogithub.codeberg.page/)

**Describe the solution you'd like**
Moving (or at least mirroring/syncing) the whole repo and all code over to [Codeberg](https://codeberg.org), a libre, free, open-source, privacy-friendly and non-profit Git platform, running the Gittea soft-fork [Forgejo](https://forgejo.org).

**Additional context**
- https://codeberg.org/Recommendations/Mirror_to_Codeberg
- https://nogithub.codeberg.page

If you need any help with the transfer I am happy to assist.

**Comment by jamie-mh** [comment]
Hi,

I agree that GitHub has its flaws, but as another case of the Network Effect, it's difficult to use anything else.
A mirror seems feasible, but I would rather have everything in one place rather than checking two places.

Cheers
