### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by happenpappen** [jamie-mh/AuthenticatorPro#649]
Please fill out the fields below where applicable:

[https://www.domaindiscount24.com/] / [https://login.domaindiscount24.com/]
A link to the site is usually best if it's available.

**Comment by jamie-mh** [comment]
Hi,

Unfortunately, this site doesn't meet the criteria for an icon.

Cheers

![image](https://user-images.githubusercontent.com/7887162/219948945-c64132f5-5572-4032-b7b9-2ad94e73ca54.png)
