### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by xmha97** [jamie-mh/AuthenticatorPro#656]
Please fill out the fields below where applicable:

**Name of website / service:**
https://nc.saber.adil.hanney.org
https://github.com/adil192/saber

---
**This section should be deleted before you submit your request, but it's worth knowing we only add icons as per our [Contribution Guidelines:](https://github.com/jamie-mh/AuthenticatorPro/blob/master/CONTRIBUTING.md)**

> - Platforms that use a 'Single Sign-On' should have the icon added for the sign-on account and not for the individual platforms. Eg: instead of a YouTube icon a Google icon would be needed, or instead of a Photoshop icon an Adobe icon should be used  
> - Web based platforms should be within [Similarweb's](https://www.similarweb.com) top 200,000 global rank. [Simply search for the site and see for yourself](https://www.similarweb.com).
> - Mobile platforms should have at least 100k+ downloads on the [Google Play Store](https://play.google.com/). 
> - If the service is not web based or on the Play Store it will have to be reviewed individually, in which case it's best to just [submit a request as a issue.](https://github.com/jamie-mh/AuthenticatorPro/issues/new?assignees=&labels=enhancement&template=icon_request.md&title=)

If you're in any doubt, there's no harm in submitting your request anyways and we'll take a look!

**Comment by jamie-mh** [comment]
Hi,

This is a little too niche for an icon, it's simply a customised Nextcloud instance. It doesn't make sense to include it at the moment.

Cheers
