### ISSUE TITLE
short_descriptions too long

### ISSUE THREAD

**Issue by IzzySoft** [jamie-mh/AuthenticatorPro#660]
Fastlane's `short_description.txt` are limited to 80 chars – everything beyond that will simply be truncated. Seems like all of yours are too long:

```
de-DE/short_description.txt has 88 chars
pl-PL/short_description.txt has 94 chars
pt-BR/short_description.txt has 93 chars
ru-RU/short_description.txt has 135 chars
sk-SK/short_description.txt has 115 chars
uk-UA/short_description.txt has 141 chars
```

Just to let you know so you can take care :wink:

**Comment by MagicLike** [comment]
@jamie-mh Should we just remove Wear-OS from the short_description?

**Comment by jamie-mh** [comment]
Yeah, I suppose the Wear OS part can be removed. Some languages are a little more wordy though, I wonder if I can set a max length on Crowdin 🤔

**Comment by MagicLike** [comment]
> Yeah, I suppose the Wear OS part can be removed. Some languages are a little more wordy though, I wonder if I can set a max length on Crowdin thinking

Opened a PR: #683

**Comment by IzzySoft** [comment]
Thanks @MagicLike – but that was the wrong locale. `en-US` is totally fine with its 71 byte. Please see my initial post for affected locales. Or did you remove it from `en-US` as the other locales are adjusted via some translation tool/service based on that?

**Comment by MagicLike** [comment]
> Thanks @MagicLike – but that was the wrong locale. `en-US` is totally fine with its 71 byte. Please see my initial post for affected locales. Or did you remove it from `en-US` as the other locales are adjusted via some translation tool/service based on that?

Jup, if the en-US locale is changed, all locales get the "update" - they are managed over Crowdin...
