### ISSUE TITLE
Secret key reveal

### ISSUE THREAD

**Issue by skariko** [jamie-mh/AuthenticatorPro#662]
**Is your feature request related to a problem? Please describe.**

Currently, it seems only possible to see the QR code of a 2FA and not the secret key. It is a bit inconvenient if you have to copy it to another application on the same smartphone because it is impossible to scan the QR Code, with the secret key you would just have to do copy and paste.

**Describe the solution you'd like**

When editing a 2FA add the secret key in addition to the QR code.

**Comment by jamie-mh** [comment]
Related to #537
