### ISSUE TITLE
WearOS version keeps loading

### ISSUE THREAD

**Issue by shanzhaxiaok** [jamie-mh/AuthenticatorPro#664]
I'm using Galaxy Watch 4(system version 11/WearOS 3.5/One UI watch 4.5) and Galaxy S23(Android 13/One UI 5.1).  Both have installed the github version of the apk(1.17.1/2.7.1).
But the software on the watch keeps loading (the blue ring is spinning). After I turned off the Bluetooth connection between the watch and the phone, the blue cloud icon can appear on the watch client, which should prove that the communication between the two devices is actually possible. 
I have tried reinstalling the software and rebooting this two devices, but it does not solve the problem .
I don't know what the problem is because I was using the previous version the other day and everything was fine.  Hope you can tell me where the problem might be, thanks a lot!

**Comment by jamie-mh** [comment]
Hi @shanzhaxiaok ,

Have you installed an F-Droid release of the APK ? These don't contain the code necessary to make Wear OS work.
Can you try installing both apps from the Play store instead ?

Cheers

**Comment by shanzhaxiaok** [comment]
Yes I installed the apk named with"fdroid".
I can install the phone app from Play Store, but I can not install the watch app from Play Store because the samsung csc policy, my galaxy watch can not connect to the google services.
so... I just tried the apk"me.jmh.authenticatorpro.apk" (no fdroid in the name)from github,I don't know what's the diffenences between them, but I tried, and still, it's not working...
I'm curious why the old version can be used, but the newly released version of fdroid does not contain the code to make Wear OS work? And could you tell us how to find the app with the google signature without Play Store?
I like AuthenticatorPro~Thanks a lot!
