### ISSUE TITLE
Question: Does this app uses android Keystore?

### ISSUE THREAD

**Issue by technikamateur** [jamie-mh/AuthenticatorPro#666]
Hi,
I used for a long time and otp and loved the android Keystore function. No need to remember any password.
Does your app uses the android Keystore? I couldn't find any information in the FAQ.

**Comment by jamie-mh** [comment]
Hi,

The app uses the Keystore for biometric authentication primarily.
If you don't want to remember a password, the solution is to not set one.

**Comment by bam80** [comment]
Can we document it once and for all?
