### ISSUE TITLE
Reduce size of apk / optimize

### ISSUE THREAD

**Issue by garygreen** [jamie-mh/AuthenticatorPro#667]
The APK is currently around 39MB, which is reasonable, though there is room for a lot of optimization here.

Here is a detailed view of the compiled APK:

![image](https://user-images.githubusercontent.com/1702638/220213117-7a295b76-ae60-4993-b8c3-18db0e1e4690.png)

Notice:

* **assemblies** (12MB) - large folder with different platform targets. This can be optimized to possibly use [App Bundles](https://developer.android.com/guide/app-bundle) to target specific platforms. Also there is [Bundle Assemblies into Native Code](https://learn.microsoft.com/en-us/xamarin/android/deploy-test/release-prep/?tabs=windows#bundle-assemblies-into-native-code) maybe that is applicable?
* **classes.dex** (8MB) - this resource could help: https://medium.com/@kevalpatel2106/how-you-can-decrease-application-size-by-60-in-only-5-minutes-47eff3e7874e
* **res** (9MB) - all the light blue contains the 4,000+ thousands png icons. [Only support specific densities](https://developer.android.com/topic/performance/reduce-apk-size#support-densities) could be considered. Also these icons could be downloaded from github on demand and cached, rather than packaging them? Possibly could help: https://github.com/jamie-mh/AuthenticatorPro/issues/212
* **lib** (12MB) - not sure what this folder is, seems to target armeabi-v7a only

The res folder with the 4,000+ png icons, is it possible they are all being loaded into memory and causing performance degradation and battery drain? [This comment](https://stackoverflow.com/a/65816671) on Stackoverflow seems to suggest all the res files are automatically loaded into memory. Possibly related: https://github.com/jamie-mh/AuthenticatorPro/issues/360

**Comment by jamie-mh** [comment]
Somewhat discussed in #576

The app is currently distributed as an AAB on the Google Play Store, so devices already receive the appropriately sized resources and optimised libs. This does reduce the size significantly:
![image](https://user-images.githubusercontent.com/7887162/221400676-2f8af5a3-3716-4ffe-932b-037857cf1f15.png)

So for a given device there is about ~12Mb of AOT libraries ("lib" directory) and at most ~4Mb of resource files (icons and such).

Before the migration from Xamarin to .NET Android, there were some optimisation properties set that reduced the app size somewhat. However, I can't get them to work anymore without breaking the app.
I may revisit this later, but it's not a priority at the moment.

Cheers
