### ISSUE TITLE
Desktop Version

### ISSUE THREAD

**Issue by Abragus** [jamie-mh/AuthenticatorPro#68]
Hey, 

The app looks pretty amazing, both in features and design, and I really want to move over from Authy. The thing stopping me though, is the desktop app. I know adding a desktop version would be a lot of work, but I'd like to know if it's something you're planning on at all. A full desktop app, or just a browser extension, it's fine either way. 

Thanks!

**Comment by jamie-mh** [comment]
Hi @Abragus ,

I have considered making a Windows 10 app, but I haven't made any progress on it.
A browser extension would be out the question because I wouldn't be able to reuse any of the existing code. The platform would need to support C# for it to be viable.

**Comment by GintokiHub** [comment]
I get that there are different threat models out there. 
I love this app and intent to use it on a mobile phone which has a secure-os and at best no internet connectivity at all.

If the app will be ported to windows / Linux / bsd. 
I hope it will make sure it wouldn't be an effortless sync like app. 
There is a reason people want to move away from authy. 
Appreciate all the work.

**Comment by SalvatoreNoschese** [comment]
Also a linix release will be very useful. I use author on Android and Linux ATM, and is time to abandon. Yep, I can use bitwarden, but save otp and password in same service I think can be a bad idea.
This app is open source and looks so good.
A desktop client with manual export and import can be a great and secure solution.
