### ISSUE TITLE
Cancel biometric login overlay if authenticator is not in foreground

### ISSUE THREAD

**Issue by jslawler** [jamie-mh/AuthenticatorPro#69]
Apps using the biometric login overlay generally dismiss the overlay if the app is switched/closed.

When switching/closing Authenticator, the biometric login overlay stays in the foreground until the user taps the dead space above the biometric login request.
This makes for an awkward action when cancelling the process in comparison to what apps usually do.

**Comment by jamie-mh** [comment]
In my testing, the overlay is always cancelled when pressing the home button or switching apps.
What device are you using? It might be a bug specific the implementation of Android you are running.

**Comment by jslawler** [comment]
OnePlus 6
LineageOS 17.1 (Android 10)

**Comment by Schokobecher** [comment]
I can replicate that behavior with MIUI 12 (Android 11)
![Screenshot_2020-12-16-00-29-49-407_com android settings](https://user-images.githubusercontent.com/1642634/102250355-0f281100-3f36-11eb-8381-a8d8862fd1a4.jpg)
![Screenshot_2020-12-16-00-29-55-198_com android systemui](https://user-images.githubusercontent.com/1642634/102250362-10f1d480-3f36-11eb-9eb6-e50a222dd487.jpg)
![Screenshot_2020-12-16-00-30-03-798_com mi android globallauncher](https://user-images.githubusercontent.com/1642634/102250365-118a6b00-3f36-11eb-80ae-ea9cf157a090.jpg)

**Comment by jamie-mh** [comment]
I've made a change that may or may not have fixed the issue. Essentially, it should cancel the prompt when the app loses focus.
It will be available in the next release. I going to keep this issue open until I can confirm that it has been fixed.

**Comment by jslawler** [comment]
If you push a test release too me, I'd be happy to confirm prior to the official release.

**Comment by jamie-mh** [comment]
Sure, that would be great. Here's a build from the latest commit:

[me.jmh.authenticatorpro-arm64-v8a.apk.zip](https://github.com/jamie-mh/AuthenticatorPro/files/5703742/me.jmh.authenticatorpro-arm64-v8a.apk.zip)

**Comment by jslawler** [comment]
> Sure, that would be great. Here's a build from the latest commit:
> 
> [me.jmh.authenticatorpro-arm64-v8a.apk.zip](https://github.com/jamie-mh/AuthenticatorPro/files/5703742/me.jmh.authenticatorpro-arm64-v8a.apk.zip)

Appears to work for me.
@Schokobecher, does this fix it for you?

**Comment by Schokobecher** [comment]
Just tried it, sadly it did not work.

- Open the App
- Instead of Unlocking hit _Recents_
![image](https://user-images.githubusercontent.com/1642634/102371985-57f0d000-3ff1-11eb-8f1b-26a827067447.png)
- Instead of Unlocking hit _Home_
![image](https://user-images.githubusercontent.com/1642634/102372028-6212ce80-3ff1-11eb-9038-0f1b334ecfc0.png)

Pressing above the Fingerprint section closes the app with the message` Authentication canceled `
Pressing _Back_ closes the app with the same message

**Comment by jamie-mh** [comment]
Thanks for testing it. This might be a bug in a version of a library used. [Android issue 149770989](https://issuetracker.google.com/issues/149770989). I will look into it further.

**Comment by jslawler** [comment]
If it helps, Magisk Manager is open source on GH, and the auth functions as you'd expect it to.

**Comment by jamie-mh** [comment]
After checking the source of Magisk Manager, it doesn't seem to be doing anything different other than it doesn't allow device credentials (pin). This might have something to do with it as mentioned in the above issue. I will run some tests with the latest version of the biometrics library once it's released.

**Comment by jamie-mh** [comment]
1.14 no longer uses ``setDeviceCredentialAllowed(true)``, so this problem might be solved. If the Android bug report is accurate that is.

**Comment by jslawler** [comment]
Can confirm the issue no longer exists in 1.13.1.

**Comment by Schokobecher** [comment]
Works for me, too. It's a bit awkward as the overlay _lingers_ for half a second or so before disapperaing

**Comment by jamie-mh** [comment]
Thanks, the delay seems like normal Android behaviour, not much I can do about that. Case closed.
