### ISSUE TITLE
LinkedIn support 

### ISSUE THREAD

**Issue by alabotski** [jamie-mh/AuthenticatorPro#690]
Does this app support LinkedIn?

I have errors now

![Screenshot_20230310-212436](https://user-images.githubusercontent.com/439337/224394294-b9babc9d-e365-4480-be3d-cc1e1e550ed2.png)

**Comment by alabotski** [comment]
I found solution
Use sha512

**Comment by IGProd** [comment]
> I found solution Use sha512

Your solution does not work for me i linked the app with no issue but when i try to connect from my mobile browser i got error in code i tried all options 512 256...
![Uploading Screenshot_2023-09-04-19-22-05-91_2c2851f616de21a6da6fb44c83a25e93.jpg…]()
