### ISSUE TITLE
Wrong ordering of the code

### ISSUE THREAD

**Issue by rafael-queiroz-cko** [jamie-mh/AuthenticatorPro#694]
**Describe the bug**
Basically the number displayed in my watch is "123 456" but in the phone it is "456 123". It was working until today lol, I already tried to uninstall from wear OS and from my phone and nothing. The correct one is from my phone btw

**App Version**
Version number of the app, found in Settings -> About.
1.17.3

**Comment by jamie-mh** [comment]
Hi,

Can you provide more details about the issue you are experiencing:
- When it occurred: app update for instance
- Is every code affected?
- Is this reproducible: every time the code is refreshed ?

Cheers

**Comment by rafael-queiroz-cko** [comment]
hey @jamie-mh , thanks for the answer. Here is more context

- I don't think it was an update
- Yes, every code
- Yes, every code in the list and in every refresh

Here is a photo, I tried my best to show 
![Sem título](https://user-images.githubusercontent.com/64465975/226860778-180d8541-4221-49de-a625-56dae0a827d1.jpg)

**Comment by jamie-mh** [comment]
Hi,

This is very strange.
I can reproduce the issue if I enable "Force RTL Layout" in the Developer Options. Do you have something like that enabled ?

Cheers

**Comment by rafael-queiroz-cko** [comment]
Yeah it was enabled for some reason, also all the toggles were opposites. 

That's really weird, maybe for a next version you could add a check for RTL Layout? Thanks for helping me
