### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by Thobov** [jamie-mh/AuthenticatorPro#695]
Hi,
First I wanted to thank you for putting lots of effort in developing the wonderful Authenticator Pro.

I would like to request the following icons. It is okay if these do not get added but it is worth a shot.

**Name of website / service:**
- Avast: https://www.avast.com
- Spigot: https://www.spigotmc.org
- Tweakers: https://www.tweakers.net

Regards, 
Thomas

**Comment by jamie-mh** [comment]
Hi @Thobov ,

I've added both SpigotMC and Tweakers icons. There is already an [Avast icon](https://github.com/jamie-mh/AuthenticatorPro/blob/master/icons/avast.png).

Cheers
