### ISSUE TITLE
Countdown timer bars not displaying

### ISSUE THREAD

**Issue by OnlyBeta** [jamie-mh/AuthenticatorPro#70]
Hi, Since version 1.12.1 the countdown timer bars are not displaying, they are not visible for almost the entire countdown duration. Only flashing up for the last 1 second of the countdown duration.

*I have a Sony Xperia XZ2 Compact with Android 10 (stock).
*I have completely uninstalled the app and reinstalled from fresh.
*I have restarted my phone.

Reverting to previous version (1.12.0), the countdown bars are OK.

**Comment by jamie-mh** [comment]
Hi @OnlyBeta ,

Is your device in battery saver mode or are the animations disabled in the developer options?

**Comment by OnlyBeta** [comment]
Good pickup, I had animations disabled in the developer options. All OK now. :)
