### ISSUE TITLE
Will this APP support HarmonyOS？

### ISSUE THREAD

**Issue by Clive1990** [jamie-mh/AuthenticatorPro#713]
Hello, this APP is very useful and beautiful, but it seems that it does not support new Huawei devices. Probably because the new Huawei devices do not publish with Google Services Framework. Is there any plan to support the Harmony OS? Thanks.

**Comment by jamie-mh** [comment]
Hi,

I'm not too familiar with HarmonyOS. What is the issue, can it not be installed or does something not work?
If Google Play Services is the issue, do the [F-Droid apk releases](https://github.com/jamie-mh/AuthenticatorPro/releases) (.fdroid.apk files) work? They do not depend on Google services.

Thanks

**Comment by Clive1990** [comment]
Hi, Thanks for your reply!
It works well on Honor V20 with Harmony OS 2, but it will get crashed in Huawei Mate 40 Pro with Harmony OS 3. When I click the App, it shows nothing and finished, the OS shows it stopped for many times.
I used the Huawei Share to share the install file from Honor V20 to Mate 40 Pro before, today I use the file on IzzyOnDroid, Very lucky, it works well today :) Maybe there are some problem with the file from Google Play.
Thank you so much.

**Comment by Clive1990** [comment]
It works well on my Huawei Mate 40 Pro now, but only a little bug. It can't scan the QR code by camera, no matter the QR code is big or small, but it can scan the QR code by photo file. Can you offer some suggestion for this? Thank you so much.

**Comment by jamie-mh** [comment]
Hi,

Glad to hear the F-Droid apk works.

The QR code issue sounds like what's being discussed in #286. The F-Droid versions seem to have problems scanning QR codes sometimes. I haven't had time to investigate any potential improvements yet.

Cheers

**Comment by 8MiYile** [comment]
@jamie-mh pls reopen this issue
because HarmonyOS 5.0 not use AOSP
