### ISSUE TITLE
Replying with 2 digits to push on WearOS

### ISSUE THREAD

**Issue by sepodele** [jamie-mh/AuthenticatorPro#714]
**Is your feature request related to a problem? Please describe.**
Logging into Microsoft stuff (like office.com) was previously a breeze if one had Microsoft Authenticator installed. A push would appear on my WearOS watch and I could just accept it there to log in. Then Microsoft started asking for input of 2 digits and I could no longer log in from my watch.

**Describe the solution you'd like**
If possible it would be awesome to receive the push from MS into Authenticator Pro and be able to reply with the 2 digits directly from my WearOS watch.

**Comment by jamie-mh** [comment]
Hi,

Similar to #552, I don't plan on supporting push notifications. It may not even be possible with proprietary services such as Office.

Thanks
