### ISSUE TITLE
Import from FreeOtp+

### ISSUE THREAD

**Issue by fdom-93** [jamie-mh/AuthenticatorPro#715]
**Describe the bug**
I can't import FreeOtp (https://play.google.com/store/apps/details?id=org.fedorahosted.freeotp) token because it's create am .xml backup, but Authenticator Pro require a .json file

**Expected behavior**
I would expect to have the ability to import an .xml file.

**App Version**
1.17.3

**Additional context**
FreeOtp version 2.0.1

**Comment by jamie-mh** [comment]
Hi,

Importing from FreeOtp is not supported at the moment.
FreeOtp Plus is a different app with a different format (https://play.google.com/store/apps/details?id=org.liberty.android.freeotpplus)

Cheers
