### ISSUE TITLE
Ability to export to a qr code

### ISSUE THREAD

**Issue by hexahigh** [jamie-mh/AuthenticatorPro#716]
Hi, i really like your app. There is just one feature that i feel is missing. Exporting to qr codes would be a great feature for creating physical backups.

**Comment by jamie-mh** [comment]
Hi,

You can export to an HTML file with QR codes in the backup menu (2nd option).
It can be printed in from a web browser.

![image](https://user-images.githubusercontent.com/7887162/232316806-06be9fa0-c4de-4a3b-86ca-f327a04320a9.png)
