### ISSUE TITLE
Can I add icons to extraicons? Icon Request

### ISSUE THREAD

**Issue by NebularNerd** [jamie-mh/AuthenticatorPro#721]
Please fill out the fields below where applicable:

**Name of website / service:**
[app.heylink.me](https://app.heylink.me)

I've just started using this site for my purposes, it has no global ranking so I will not make a PR for inclusion in the main `icon` folder. Can we PR the `extraicons` folder for storing icons for possible future use or as a icon source for other users of low/no rank 2FA's?

**Comment by jamie-mh** [comment]
Hi,

The canonical URL has a very high rank. I can be added to the regular icons folder.

![image](https://user-images.githubusercontent.com/7887162/233787273-8c3b70e9-725d-49f8-a535-759aedc15285.png)

Cheers
