### ISSUE TITLE
Persist most/least copied count through update

### ISSUE THREAD

**Issue by realpixelcode** [jamie-mh/AuthenticatorPro#722]
**Describe the bug**
After updating the app, it has forgotten how often you have copied each item, rendering “sort by most/least copied” useless.

**To Reproduce**
1. Copy different items.
2. Update the app.
3. Filter by “most copied”.
4. Items are displayed in alphabetic order.

**Expected behavior**
It should store the copy count.

**App Version**
I noticed this after updating to v1.18.0 via F-Droid.

**Comment by jamie-mh** [comment]
Hi,

Ordering by most copied was added in 1.18.0. What update did you install if you already had the latest version?

Thanks
