### ISSUE TITLE
Bulk-add items to categories

### ISSUE THREAD

**Issue by realpixelcode** [jamie-mh/AuthenticatorPro#723]
**Is your feature request related to a problem? Please describe.**
Adding a single item to a single category requires 4 clicks. Selecting the categories for each of my 50 accounts requires 200+ taps.

**Describe the solution you'd like**
Make it quicker to add items to categories. Ideas:

- multi-select items to bulk-add them to a category
- don't set the category of an item, but set the items of a category, i.e. navigate to a category and select the items to add instead of editing each item one by one

**Comment by jamie-mh** [comment]
Added in version 1.20.0

**Comment by realpixelcode** [comment]
> Added in version 1.20.0

Thank you very much! ❤️
