### ISSUE TITLE
Are the Data Encrypted at Rest? 

### ISSUE THREAD

**Issue by michelangelo136** [jamie-mh/AuthenticatorPro#753]
First of all thanks for supporting wear OS sync, this was a very strong reason to migrate over to Authenticator Pro. 

I was previously using Aegis which encrypts the data while at rest, can you validate that Authenticator Pro does the same?

**Comment by jamie-mh** [comment]
Hi,

Yes. The app uses a [SQLCipher](https://www.zetetic.net/sqlcipher/) database encrypted with the app password set by the user.
When you use biometric unlock, the database password is encrypted using a key stored in the Android KeyStore only released by the system once biometrics are validated.

Cheers
