### ISSUE TITLE
[Suggestion] Addition of AMOLED black theme option

### ISSUE THREAD

**Issue by Gravemind2015** [jamie-mh/AuthenticatorPro#756]
**Is your feature request related to a problem? Please describe.**
With the latest update 1.19.0, material you theme was added. While it helps making Authenticator Pro look consistent on devices like Pixels and other AOSP-like ROMs, it however replaced the previously black/dark theme option which fitted nicely to other android flavours like OneUI by samsung which have black theme, especially noticable on AMOLED devices.

**Describe the solution you'd like**
I realise that adding a ton of options isn't probably the best idea, but in this case, an AMOLED dark/black more can be introduced that restores a black theme. Or maybe a toggle between the old themes and the new material you, whichever produces less burden on maintenance going forward.

**Additional context**
It's completely about aesthetics, without any real technical benefits but since AMOLED dark was already present prior to this version, I made this request. I guess this would be a low priority request. Anyway, thanks a ton for this project, it's really a helpful application.

**Comment by jamie-mh** [comment]
Hi @Gravemind2015 ,

In the next release (1.20.0), there will be a black theme option in addition to the light and dark options: [updated branding](https://raw.githubusercontent.com/jamie-mh/AuthenticatorPro/6992e54bc10fd521d0abfbdf5dbb4e498b7cecae/doc/RebrandingMaterial/compatibility.png)

Cheers
