### ISSUE TITLE
Tiles not working on Samsung Watch 5 Pro

### ISSUE THREAD

**Issue by yakov116** [jamie-mh/AuthenticatorPro#762]
**Describe the bug**
I set a favorite and it still shows "example"

**To Reproduce**
1. Go to item
2. Hold down to select favorite 
3. Go to tile
4. See sample

**Expected behavior**
Tile should show correctly.

**App Version**
1.19

**Additional context**
![20230507_131736.jpg](https://user-images.githubusercontent.com/16872793/236692689-d056cb6d-67c9-46ff-ad29-857e74acbdcd.jpg)

![20230507_132220.jpg](https://user-images.githubusercontent.com/16872793/236692816-d19f73b0-cb41-4fa2-900e-aae882f4935c.jpg)

**Comment by jamie-mh** [comment]
Hi,

It looks like it's crashed for some reason. Does it occur on every item or just the first one?

Thanks

**Comment by yakov116** [comment]
Its weird since I tried to change it to another one, some of them work and some of them don't.

**Comment by yakov116** [comment]
Is there a way for me to help you debug this?

**Comment by jamie-mh** [comment]
Hi, can you try the latest update. It may fix your issue.
Thanks

**Comment by yakov116** [comment]
It's fixed thanks!
