### ISSUE TITLE
Accent color corresponding to screenshot6 is missing in the app. 

### ISSUE THREAD

**Issue by starktower007** [jamie-mh/AuthenticatorPro#765]
The accent colour option for screenshot6 image seems to be missing in the app. Is the screenshot6 accent color a missing option or this is not an available accent color? 

https://github.com/jamie-mh/AuthenticatorPro/blob/master/doc/screenshot6.png
![Screenshot_2023-05-10-03-45-52-92_320a9a695de7cdce83ed5281148d6f19](https://github.com/jamie-mh/AuthenticatorPro/assets/133062134/0122c363-d6be-42d3-b839-3134ce1d354f)

**App Version**

1.19.0

**Comment by jamie-mh** [comment]
Hi,

This is not a selectable accent colour but rather dynamic colour with this wallpaper.

Cheers

![Screenshot_20230510_194555](https://github.com/jamie-mh/AuthenticatorPro/assets/7887162/0331e83b-05f4-471a-961f-9ad822157f4d)
![wallpaper](https://github.com/jamie-mh/AuthenticatorPro/assets/7887162/d15af6a4-68bb-432f-8695-3038f2d0bddf)
