### ISSUE TITLE
Timeout bar thinkness.

### ISSUE THREAD

**Issue by fedonr** [jamie-mh/AuthenticatorPro#767]
Referring to 1.20.0 beta : I'm referring to the timeout bar which shows at the bottom of each account, it works well in light and dark themes as it is visible enough, but as soon as you switch to pure Black Amoled theme, it becomes almost invisible due to contrast and it being very thin. So if that thickness can be a little more not much but just a Lil.

This nothing but a little aesthetic upgrade which would make it much more eye pleasing and usuable with Black theme, hope it can be addressed in final version.

Mentioning it in bugs, as I think not able to see the time out bar properly comes under bugs and not feature request to increase thickness. Sorry if I'm wrong here, as I didn't know better.

**Comment by jamie-mh** [comment]
Hi @fedonr ,

Thanks for your feedback. I agree, with the outline of the card, the progress bar isn't very visible. I've made it slightly thicker in the black mode to compensate (c07d14e).

Cheers

**Comment by fedonr** [comment]
Great! Thanks.
