### ISSUE TITLE
Suggestion to link/start a discord server or something similar in the app About section. And also if we can add a toggle like Aegis to allow/disallow Sceenshots.

### ISSUE THREAD

**Issue by fedonr** [jamie-mh/AuthenticatorPro#769]
Being a Dev, and doing something for Free and making it open source is a great work but equally hectic, so to avoid everyone looking for support being redirected here and raising issues, which you'll need to manage, you can put a simple discord or telegram link in the About section where people can ask community and look for the support rather then opening the issues here.

Plus I also wanted to know how the people opening issues here are talking screenshots as I'm not able to due to the app not allowing it.  So is there a way to take screenshots ? If not can we add the toggle to allow Screenshots ?

**Comment by sunxyw** [comment]
> Plus I also wanted to know how the people opening issues here are talking screenshots as I'm not able to due to the app not allowing it. So is there a way to take screenshots ? If not can we add the toggle to allow Screenshots ?

There is an "allow screenshot" option in the app's settings where you can allow screenshots. (introduced in [1.20.1](https://github.com/jamie-mh/AuthenticatorPro/releases/tag/1.20.1))
