### ISSUE TITLE
No countdown timer bars on some entries in Tile mode

### ISSUE THREAD

**Issue by haukist** [jamie-mh/AuthenticatorPro#781]
**Describe the bug**
Some entries don't have countdown timer bars when view mode is Tile and have multiple entries for the same issuer.

**To Reproduce**
1. Add two entries for the same issuer
2. Add another entry for a different issuer
3. Set view mode Tile
4. See an entry without a countdown timer bar

**Expected behavior**
All entries have countdown timer bars.

**App Version**
1.20.0

**Additional context**
I don't know about the previous version.

**Comment by jamie-mh** [comment]
Hi @haukist ,

I'm not able to reproduce this, the progress bars are always displayed for me.
Does this happen consistently or is this an irregular occurrence?

Thanks

![Screenshot_20230520_084612](https://github.com/jamie-mh/AuthenticatorPro/assets/7887162/6b0deade-6659-4d43-bd35-e959f202ad6c)
