### ISSUE TITLE
Icon Request: Kinguin

### ISSUE THREAD

**Issue by ThunderF0x** [jamie-mh/AuthenticatorPro#790]
Name of website / service: https://www.kinguin.net/

**Comment by jamie-mh** [comment]
Kinguin does not support TOTP only [email verification codes](https://github.com/2factorauth/twofactorauth/blob/master/entries/k/kinguin.net.json).

**Comment by ThunderF0x** [comment]
Here is the proof that Kinguin supports TOTP.
![kinguin](https://github.com/jamie-mh/AuthenticatorPro/assets/122406330/9dadaf55-d867-4324-80f1-5304283ba6ed)

**Comment by jamie-mh** [comment]
It seems there are 2 different settings panels, one with and one without. Added in 41592407bee2b5e69ca92ae4a7b502b6297c0c25.

![kinguin](https://github.com/jamie-mh/AuthenticatorPro/assets/7887162/f21ce69a-bc18-45f9-8210-c408da0d933a)
