### ISSUE TITLE
Icon for autenti.com

### ISSUE THREAD

**Issue by kwiateusz** [jamie-mh/AuthenticatorPro#814]
**Name of website / service:** https://autenti.com/
**Rank:** 131,660 - https://www.similarweb.com/website/autenti.com/#overview

I would like to add this page where you can electronically sign documents. But I've question about icon. They default icon is dark on white backgound. When I remove background it's hard to read. Which should I add? 

Quick example below.

![autenti](https://github.com/jamie-mh/AuthenticatorPro/assets/924979/0b2db8ec-bc87-4aac-8485-69c622599346)
![autenti_trans](https://github.com/jamie-mh/AuthenticatorPro/assets/924979/231c0953-7c3f-44d0-87c2-0ae8b2db2f46)

**Comment by jamie-mh** [comment]
Hi @kwiateusz ,

Is the problem on a dark background? With the following variations, it seems visible enough to me.

Cheers

![image](https://github.com/jamie-mh/AuthenticatorPro/assets/7887162/9c244fe7-1694-4ccb-987f-deba4a79b18b)
![image](https://github.com/jamie-mh/AuthenticatorPro/assets/7887162/8b52ee87-3c7b-43ee-a17a-2f9baf45fb86)

![autenti](https://github.com/jamie-mh/AuthenticatorPro/assets/7887162/d2b50c89-5f8f-4830-a999-09b6ff2eceb1)
![autenti_dark](https://github.com/jamie-mh/AuthenticatorPro/assets/7887162/53bdb161-6011-4e9c-9022-31a4b1edbff2)

**Comment by kwiateusz** [comment]
Yes, I didn't like the contrast ratio after removing the white background. I assumed it must be the original logo and they don't have the bright one. If reversing the colors is not a problem I will put them into pull request. Thanks for your help.
