### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by OmarNazzal150** [jamie-mh/AuthenticatorPro#818]
Backup Code

**Comment by jamie-mh** [comment]
Sorry, I don't quite understand what you mean. Does this refer to storing recovery codes within the app?

**Comment by OmarNazzal150** [comment]
Yes

**Comment by jamie-mh** [comment]
What's the use case for this feature? If you have access to the app, you don't need the recovery codes and if you can't access the app then you'd be locked out of your accounts without them.

**Comment by OmarNazzal150** [comment]
Add A recovery code option to store my recovery codes please
