### ISSUE TITLE
Important

### ISSUE THREAD

**Issue by DoyWebsite** [jamie-mh/AuthenticatorPro#827]
I apologize in advance, but there was no other way to contact you. I have a few questions....if you have time please reply. Thanks

**Comment by jamie-mh** [comment]
What's so important?

**Comment by DoyWebsite** [comment]
how did you guys made lunar client run on azul java instead of just java?

**Comment by DoyWebsite** [comment]
+ can I apply for a job with you guys?

**Comment by jamie-mh** [comment]
> how did you guys made lunar client run on azul java instead of just java?

I don't know what any of those things are. I think you're in the wrong place.
