### ISSUE TITLE
Add a setting to choose the OTP code display time.

### ISSUE THREAD

**Issue by rafaelrandom** [jamie-mh/AuthenticatorPro#828]
When the TAP to Reveal option is active, when touching a code, it is displayed while the time of progress of that code is lasting, if it is missing 2 second for the code to be changed, it is hidden and you will have to play again to see the New code.
So, adding an option to choose the code display time, if you choose for example 10 seconds of display, and upon entering 1 or 2 seconds to be changed for a code changed, the new code will still be displayed for another 8 or 9 Seconds and it will not be necessary to play again to display the new code.
Aegis Authenticator has a similar configuration and is very covenant, the options from 1 to 60 seconds would be enough.

Well, that's it, I hope the developer can understand.

**Comment by jamie-mh** [comment]
Yes, I see what you mean. The code should stay visible even if it expires for a fixed amount of time.
I'll look into it.

**Comment by rafaelrandom** [comment]
@jamie-mh that's right, thanks for your consideration.

**Comment by rafaelrandom** [comment]
Configuration added, many thanks @jamie-mh.
