### ISSUE TITLE
Search does not maintain focus after deleting query

### ISSUE THREAD

**Issue by makkonen** [jamie-mh/AuthenticatorPro#844]
**Describe the bug**
Very minor usability weirdness. If I am using the search bar, and I mistype and then delete my entry, when the search bar becomes empty, the search exits and I'm sent back to the main list. Typical behavior maintains search focus until one manually hits the back button or clicks away from the searchbar.

**To Reproduce**
1. click the magnifying glass
2. type a letter
3. delete the letter

**Expected behavior**
On deleting the final letter in a search query, the search should not exit, but should stay active as if the magnifying glass was just clicked.

**App Version**
1.20.1

**Comment by Kvasenok** [comment]
Hi, @makkonen 
Are you still having this issue on 1.22.0? 
Because in my case the search works exactly how you described it should work.

**Comment by makkonen** [comment]
Nope, this went away about... 4-6 weeks ago? Looks like that's when 1.22.0 was released, so I assume the fix was somewhere in there.
