### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by inoyakaigor** [jamie-mh/AuthenticatorPro#845]
Please fill out the fields below where applicable:

**Name of website / service:**
bitbucket.org

Link to 256x256 icon https://wac-cdn.atlassian.com/assets/img/favicons/bitbucket/android-chrome-256x256.png

**Comment by jamie-mh** [comment]
Hi,

As per the [icon guidelines](https://github.com/jamie-mh/AuthenticatorPro/blob/master/CONTRIBUTING.md#icon-criteria), the [Bitbucket](https://github.com/jamie-mh/AuthenticatorPro/blob/master/extraicons/bitbucket.png) icon was removed as an Atlassian account is used for login.

Cheers
