### ISSUE TITLE
Is it ok to take your icons library for my project?

### ISSUE THREAD

**Issue by panyann** [jamie-mh/AuthenticatorPro#848]
Hello,
As a hobby project (at least for now) I'm working on similar 2FA application to yours, but for Windows desktop. I would like to make them more or less compatible with each other (for example you would be able to import the json backup from Authenticator Pro to my app).

I will not use your code at all, but I would like to borrow your icons folder for the same purpose it's in your app. Of course if I will some day publish my app, I would give a huge credit to your project.
Is that ok?

That's how it looks in current development:
![image](https://github.com/jamie-mh/AuthenticatorPro/assets/22815508/1d82e223-9160-419f-a4f2-10df9239c362)

**Comment by MagicLike** [comment]
> Hello,
> As a hobby project (at least for now) I'm working on similar 2FA application to yours, but for Windows desktop. I would like to make them more or less compatible with each other (for example you would be able to import the json backup from Authenticator Pro to my app).
> 
> I will not use your code at all, but I would like to borrow your icons folder for the same purpose it's in your app. Of course if I will some day publish my app, I would give a huge credit to your project.
> Is that ok? 

The icons are not created by people contributing to the project, but rather taken directly from the apps / services themselves, so I as a contributor don't see a problem.

**Comment by panyann** [comment]
@MagicLike Hey, glad to hear it, thanks for your reply 🙂

**Comment by jamie-mh** [comment]
It's not so simple. The icons are not copied verbatim from their original sources in many cases, they are also transformed, recoloured, adapted when necessary. Many contributors have taken great effort to create, update and curate the icon set under knowledge of the GPL 3 license applied.

As to whether or not the license is applicable in this case, since the brands in question are the primary rights holders. I really have no idea.

Are you planning to release the app under any license in particular? Will the icons be distributed with the app?

**Comment by panyann** [comment]
@jamie-mh I want to publish my program on Microsoft Store as a proprietary software. The icons would be a part of the app. If you think it's problematic and breaks your license I will of course search for other icons package 🙂

**Comment by MagicLike** [comment]
> It's not so simple. The icons are not copied verbatim from their original sources in many cases, they are also transformed, recoloured, adapted when necessary. Many contributors have taken great effort to create, update and curate the icon set under knowledge of the GPL 3 license applied.

Oops, should have known better, as I did exactly that in some of my contributions...

**Comment by panyann** [comment]
Just wanted to say that my app is finally in the Microsoft Store! You can import your TOTP keys to it from your mobile to desktop.
https://apps.microsoft.com/store/detail/2fa-pro/9PLTN0LJGG1G?hl=en-us&en-us=
**I have some free deals to offer for Authenticator Pro users**, just tell me you want it: 2FA-Pro@proton.me

PS: I found a free icon package, so don't worry, no license problem :P

![main-menu](https://github.com/jamie-mh/AuthenticatorPro/assets/22815508/f41c225d-b5ba-4c3f-8b2e-67da9a3b156b)
