### ISSUE TITLE
Face Recognition Unlock Feature

### ISSUE THREAD

**Issue by OmarNazzal150** [jamie-mh/AuthenticatorPro#850]
Is your feature request related to a problem? Please describe.

Hi, so when we unlock authenticatior pro, we will unlock it using face recognition instead of fingerprints or writing the password

Describe the solution you'd like

So I can unlock the app using face recognition,👦 instead of fingerprints or writing the password, please

Thank You 
Jmh

**Comment by jamie-mh** [comment]
The app already supports face recognition with [Class 3 biometrics](https://developer.android.com/reference/android/hardware/biometrics/BiometricManager.Authenticators#BIOMETRIC_STRONG). If you're not able to use face recognition on your device, it means that it's not considered secure enough to be used in this context.
