### ISSUE TITLE
Add Kannada language

### ISSUE THREAD

**Issue by ch3thanhs** [jamie-mh/AuthenticatorPro#878]
**Is your feature request related to a problem? Please describe.**
No, It's related to localization.

**Describe the solution you'd like**
Add Kannada language in Crowdin.

**Additional context**
I would like to translate the app to Kannada.

**Comment by ch3thanhs** [comment]
Hi @jamie-mh, Can you please add it?

**Comment by jamie-mh** [comment]
Hi @ch3thanhs , I've added the language on Crowdin.
