### ISSUE TITLE
Wear OS app shows empty screen until I turn screen off and back on

### ISSUE THREAD

**Issue by marek26340** [jamie-mh/AuthenticatorPro#885]
When I open the app on my watch, at first, only an empty screen with the current time at the top shows up. After turning the screen off using the "cover screen with palm" or "put your hand down" gesture, then waking the watch back up by pressing a button or doing a gesture for turning the screen on, the codes immediately show up. Chance of the watch app doing this to me is about 99% of the time now. The app on the phone is working perfectly.

**To Reproduce**
1. Have some OTP codes set up in the app on the phone and have the Wear OS app installed.
2. Wake up your watch and open the Authenticator Pro app on it.
3. See a blank screen with only the menu for choosing categories show up by scrolling up with the empty screen.
4.a. Turn off the watch screen, either by waiting for the timeout, or doing a gesture for it. Then turn it back on, also either with a button press, or by doing a gesture for it.
4.b. Press the home button to get to the homescreen/watchface, then immediately go back into the app. (do not close the app by swiping it away in the "recent apps" menu, otherwise go back to step 1)
5. See that all codes now show up as they should.

**Expected behavior**
I should be able to see all the choices for OTP codes (pretty much) immediately after opening the app on my watch, without having to close it and reopen it.

**App Version**
Currently on 1.21.0 from Google Play. Version 2.12.0 on my watch. Issue shows up.
Everything worked fine before updating the WearOS app (I think) from 2.11.0 (and likely the phone app too). So it pretty much worked correctly for exactly one update for me.

**Additional context**
Restoring the phone app and the watch app to versions 1.20.1 and 2.11.0 respectively fixed this issue for me.

My phone is a Samsung Galaxy Note 10 (N970F/DS, Android 12, Exynos, OXM, N970FXXS8HWC3, April 2023 patch).
My watch is a Samsung Galaxy Watch 4 (SM-R860, Android 11/WearOS 3.5, Play Services 23.25.16, R860XXU1GWD6, April 2023 patch).

As you apparently use different signatures on the apks published in the Releases on GitHub and on the Play Store, I had to uninstall both old apps and reinstall them from scratch from GPlay. After restoring from backup and opening the freshly installed app on my watch, the same issue immediately showed up again. So I will have to downgrade the apps for the time being.
That being said, if the signatures or architectures or whatever (I don't understand this stuff too much) are different, I unfortunately can't test if upgrading only on the phone or on the watch breaks it. (I'm betting on the watch app tho)

I can share a video of this issue with you, if you'll give me an email address. Thank you for looking into this!

**Comment by sioux1977** [comment]
same issue.

**Comment by jamie-mh** [comment]
It this still an issue on the latest version (2.14.1)? Thanks

**Comment by marek26340** [comment]
Apologies for ghosting this issue. Can't reproduce this issue in the latest versions anymore, so I'll close. Thank you!
