### ISSUE TITLE
Unknown algorithm 

### ISSUE THREAD

**Issue by handyfreak** [jamie-mh/AuthenticatorPro#890]
**Describe the bug**
See additional context below. 

**To Reproduce**
1. Go to '+'
2. Click on 'Scann a QR Code.'
3. Scroll down to 'Take Picture with camera.'
4. See error and Pictures
Unknown Algorithm '3

![Screenshot_20230802_230437_Gallery](https://github.com/jamie-mh/AuthenticatorPro/assets/3752559/3dd9b782-9747-4ebd-9d51-04e93045971e)

![Screenshot_20230802_230340_Gallery](https://github.com/jamie-mh/AuthenticatorPro/assets/3752559/f1dc7648-4858-48ce-b499-8e8d64729f7c)

**Expected behavior**
To add the account to my wallet

**App Version**
1.2.10

**Additional context*
I exported the account from Google authenticator, together with others which has been imported successful. 
After the first error i exported the missing account only, result same error. 

Exporting and importing from one phone to another using Google authenticator works, tested both ways. 

!!! The Account has a non editable, proper name, like "Name GmbH:" followed by a editabable name which i can chose and change. SEE red circle on screenshot. 

![Screenshot_20230802_230246_Photo Editor](https://github.com/jamie-mh/AuthenticatorPro/assets/3752559/912fdebe-fdd8-4e15-9ead-116c27ab9040)

I also tried to change the editable part to a shorter, simple name - no success. 

(The account name on the picture is blacked out for GDPR.)

**Comment by jamie-mh** [comment]
It appears that your account uses the SHA-512 algorithm.
I've added support for SHA-256 and SHA-512 in 6c76b53.
