### ISSUE TITLE
There is a bug that scans for invalid keys and dies.

### ISSUE THREAD

**Issue by crucifyer** [jamie-mh/AuthenticatorPro#9]
Hi~

There is a bug that scans for invalid keys and dies.
ex) ZIG54ATT5THSXFO0000
It continues to die until you use the Data Delete menu.
The only thing that's categorized in Android is this.
Please fix it.

Thank you.

**Comment by jamie-mh** [comment]
Hi, thanks for reporting this issue.
Fixed in 508dce9.
