### ISSUE TITLE
Non-WearOS Compatibility Issues

### ISSUE THREAD

**Issue by Kuriyona** [jamie-mh/AuthenticatorPro#900]
> My English is not good

My watch doesn't run the standard WearOS and itself restricts installing third-party apps. When I use "安卓手表adb实用工具箱" to bypass the restriction, I can't install it.

the "安卓手表adb实用工具箱" display this
```
ADB反馈失败原因：系统缺少某些必需的共享库！
当前设备的系统不支持安装此APP，系统不兼容(部分APP基于WearOS开发，故无法安装在非WearOS系统的设备上）！
```
translated
```
ADB feedback failure reason: The system is missing some required shared libraries!
The current device system does not support the installation of this APP, and the system is not compatible (some APPs are developed based on WearOS, so they cannot be installed on non-WearOS devices)!
```

I want a version that can be installed to my device.

### Device Info
```
Device Name : HUAWEI Watch 3
OS : HarmonyOS 3.0.0366 
```

If it's a hassle, forget it.
Tanks.

**Comment by xrh0905** [comment]
To be honest, the "HarmonyOS" should be just the Android with tiny customize, so it shouldn't be considered as a sepreated platorm.
