### ISSUE TITLE
Cannot import from 2fas

### ISSUE THREAD

**Issue by milindgoel15** [jamie-mh/AuthenticatorPro#901]
**Describe the bug**
When importing the 2fas backup, it fails to import some apps and throws error.

```log
The item reddit failed to import due to the following error: Algorithm not supported
```

It happens with reddit, instagram, google, GitHub, twitter, mega, discord

**To Reproduce**
1. Add a token on 2fas for any of the app mentioned
2. Export backup
3. Import in authenticator pro

**Expected behavior**
All imports are done without issue

**App Version**
1.21.0

**Additional context**
N/a

**Comment by jamie-mh** [comment]
Hi @milindgoel15 ,

Thanks for reporting this.
It seems that an algorithm is not always specified. In that case, it should default to SHA1. Fixed in 45c4449ad4b023fb878123b111e4b15e96eb8d90.
