### ISSUE TITLE
Don't draw the app behind status bar

### ISSUE THREAD

**Issue by milindgoel15** [jamie-mh/AuthenticatorPro#913]
**Is your feature request related to a problem? Please describe.**
So currently the app can draw behind the status bar when we scroll down the home page. Can you make it not draw behind it?

**Describe the solution you'd like**
Make the edge to edge boolean flag to bottom only

**Additional context**
![Screenshot_2023-08-23-20-35-49-278_me.jmh.authenticatorpro~01.jpg](https://github.com/jamie-mh/AuthenticatorPro/assets/45682747/0ec15f38-c223-4f0d-8d70-5bdecce07ade)

**Comment by ch3thanhs** [comment]
Hi @milindgoel15, You can turn it off in settings.

![Screenshot_20230824-224820_Authenticator Pro.png](https://github.com/jamie-mh/AuthenticatorPro/assets/76928501/e644e991-d44d-427f-b18c-f2eac25c3fe5)

**Comment by Kvasenok** [comment]
Hi, @milindgoel15 
You should probably create new issues for your suggestions and close this one as the initial issue has been resolved
