### ISSUE TITLE
Auto Backup 

### ISSUE THREAD

**Issue by m-kaissi** [jamie-mh/AuthenticatorPro#920]
First of all , thank you for this great project and for your hard work to keep it updated.

My issue is I use auto Backup and it works great no doubt about that , but I add tokens regularly, and that folder where it Backup up , there's tons of backup files whenever i edit something it create another backup and and leave the old one.
I want it when it backup the new changes it automatically delete the old backup to keep it organized.

Thank you.

**Comment by jamie-mh** [comment]
Duplicate of #510
