### ISSUE TITLE
Backup file generates different Codes

### ISSUE THREAD

**Issue by Ale268** [jamie-mh/AuthenticatorPro#922]
**Describe the bug**
If I Import the backup file (Authpro, html or text) the generated codes are not the same.
If I look at the key etc the settings are the same but only the original one works / is right.

I installed the Authenticator app on my windows 11 Tablet in Windows Subsystem for Android and imported a backup
from my phone. That worked for about two Months and since some time it is broken and shows different codes.

I installed the newest release and tested all import functions but none worked. 
I don't think this is how a backup should work?
Or am I wrong?

**To Reproduce**
Export from one device and import on another.

**Expected behavior**
The same 2FA codes on the different devices.

**App Version**
1.21

**Additional context**

Device A 
Samsung Galaxy A53 
Imported Backup from Galaxy S9 a year ago

Device B
Surface Pro 8 with WSA and also newest release.

Just ask for further Informations I forgot!

**Comment by jamie-mh** [comment]
If you imported the backup and the keys are the same, then everything worked as intended.
The time on your device is probably out of sync. There is a [wiki page](https://github.com/jamie-mh/AuthenticatorPro/wiki/Codes-not-working) on the subject.

**Comment by Ale268** [comment]
Indeed windows once more f'd up it's time.

THank you for pointing it out!
