### ISSUE TITLE
Question on icon names for sites with same names

### ISSUE THREAD

**Issue by ch3thanhs** [jamie-mh/AuthenticatorPro#926]
Recently [obsidian.md](https://obsidian.md/) added support for 2FA and I wanted to add the icon but an icon already exists for [obsidian.net](https://www.obsidian.net/) with the name "obsidian", wanted to check with what name I can add the new icon.

Can it be named "obsidianmd"?

**Comment by rafaelazvdo** [comment]
It will probably be just that, "obsidianmd".

**Comment by jamie-mh** [comment]
Hi @ch3thanhs ,

Yes, "obsidianmd" is what I would choose.

**Comment by ch3thanhs** [comment]
Added in #932
