### ISSUE TITLE
Show copy count

### ISSUE THREAD

**Issue by PunchEnergyFTW** [jamie-mh/AuthenticatorPro#930]
**Is your feature request related to a problem? Please describe.**
No real issue, just a convenience thing that i am not able to see what codes were copied how many times.

**Describe the solution you'd like**
Add a little counter to the cards which shows how many times the codes have been copied. 

Thanks :)

**Comment by jamie-mh** [comment]
Added in 1.23.0

**Comment by ch3thanhs** [comment]
Hi @jamie-mh, This feature does not seem to work, I am sorting by "Most copied" and I don't see the copy count.

**Comment by PunchEnergyFTW** [comment]
> Hi @jamie-mh, This feature does not seem to work, I am sorting by "Most copied" and I don't see the copy count.

You'll have to press the 3 dots. Then the copy count will appear. 
But yeah, maybe it would be possible/better to see them in under the current code or so. :)
![Screenshot_20231128_140100_Authenticator Pro](https://github.com/jamie-mh/AuthenticatorPro/assets/61878903/fd59b69d-88ec-46c3-a3f4-f9d0456bdeba)
