### ISSUE TITLE
The app should be able to lock itself everytime it loses focus instead of whenever the process is shut down

### ISSUE THREAD

**Issue by sbeve72** [jamie-mh/AuthenticatorPro#94]
I tried app lock today and found out that the app doesn't lock itself whenever I navigate to some other app or go to the home screen. The only time it locks for me is when the process is shut down (either by the system or the user). It seems you're using Xamarin, so I can't even understand most of your code because I have never worked on Xamarin.

**Comment by jamie-mh** [comment]
Hi @sbeve72 ,

There is a 2 minute threshold before locking when the app is closed. Does this work on your end?

**Comment by sbeve72** [comment]
Ah okay. In two minutes my system automatically kills the process anyway if I am using my phone. So i guess the 2 minute threshold does work. It'd be awesome to have an option to set it to lock immediately when ut loses focus.

**Comment by jamie-mh** [comment]
1.14 includes a new lock / password system with a configurable timeout. Locking immediately is also now an option.
