### ISSUE TITLE
App crashes when trying to "rename" some codes

### ISSUE THREAD

**Issue by blockhead48** [jamie-mh/AuthenticatorPro#95]
Recently I downloaded the app and transferred the codes from google authenticator. After doing that I tried to rename the codes and while on some it would work like normal, some would instantly crash the app if I tried to click rename. At first I thought something was corrupted because of the switch from GA so I set one code up again (the one that crashed) but it still crashed the app.  There really is no apparent connection between software these 2FA codes originate from. One was setup on a billing platform, the other one on a forum software so I don't really know what's going on

**Comment by jamie-mh** [comment]
Hi @blockhead48 ,

Thanks for pointing this out. I'm aware of the issue and it has already been fixed. It will be available in the next release soon.
