### ISSUE TITLE
Cannot import bitwarden JSON export

### ISSUE THREAD

**Issue by euinor** [jamie-mh/AuthenticatorPro#97]
Hi, I get an error when trying to import a bitwarden exported JSON file. It just says 'cannot import file' or similar. Is there anything I can provide to add more detail?

**Comment by jamie-mh** [comment]
Hi @euinor ,

I don't really know what the issue could be, but it must be failing on one of the authenticators in the Bitwarden file.
Are you using Steam totp in Bitwarden?

**Comment by jamie-mh** [comment]
Or more likely, do you have any cards, identities or secure notes in your vault (aka everything except logins)?

**Comment by euinor** [comment]
Yes, I have tonnes of notes, cards, identities etc in the vault.
I could manually cleanse the file of all non to information. Would that work?

**Comment by jamie-mh** [comment]
I'm fairly confident that I've fixed the issue. Would you be willing to test a beta version?
It would save you the trouble of removing stuff from your backup file.

**Comment by euinor** [comment]
Sure, happy to test.

**Comment by jamie-mh** [comment]
Thanks, here's the apk.
[me.jmh.authenticatorpro.apk.zip](https://github.com/jamie-mh/AuthenticatorPro/files/5826219/me.jmh.authenticatorpro.apk.zip)

**Comment by euinor** [comment]
Successfully imported my bitwarden codes! I did have to uninstalled Authenticator Pro before I could install your beta version.

While we're discussing this, any chance of an import from Authy?

**Comment by jamie-mh** [comment]
Great! You should be able to create a backup in the beta version and restore that in the Google Play version.
AFAIK, Authy doesn't provide any sort of export, so I don't think it's possible. At least not without root access.

**Comment by euinor** [comment]
Ok, thanks very much.
