### ISSUE TITLE
Icon requests

### ISSUE THREAD

**Issue by flz** [jamie-mh/AuthenticatorPro#99]
Hi jamie-mh,

As suggested in the README, here are a few requests for new icons.

- KuCoin exchange: https://www.kucoin.com/
- Gemini exchange: https://www.gemini.com/
- Bitstamp: https://www.bitstamp.net/
- HomeAssistant: https://www.home-assistant.io/
- USCIS: https://my.uscis.gov/
- Login.gov: https://login.gov/

Thanks!

**Comment by Schokobecher** [comment]
I'm on it :)

**Comment by Schokobecher** [comment]
Should be fixed  in #102 
The USCIS service is technically named _myUSCIS_, hence I've named the icon to match that - though the icon is the generic Homeland Security seal :thinking:

**Comment by flz** [comment]
Thanks @Schokobecher !
