### ISSUE TITLE
Cannot update already installed App with APK from GitHub

### ISSUE THREAD

**Issue by HigH-HawK** [jamie-mh/AuthenticatorPro#997]
**Describe the bug**
I tried updating the app from version 1.22.0 to version 1.23.0 but am getting an error when doing so.

Error: `App not installed as package appears to be invalid.`

Initially, I installed the app from GitHub (version 1.16.1), but future updates came from the Google Play Store. Could this be the reason why I cannot update the app with the downloaded APK from GitHub?

I tried running LogCat but it does not appear to create any entries or errors in there while trying to execute the APK file. I was however able to see a warning message in the App Viewer.

Warning message: `Signature of this package is different from the installed application`

**To Reproduce**
1. Download the app `me.jmh.authenticatorpro.apk` from GitHub
2. Open the app and follow the steps on screen
3. See error

**Expected behavior**
My understanding was that updating the app with the APK from GitHub would simply update the installed app version.

**Versions**
Abdroid: 13
Device: Samsung Galaxy S22 Ultra (SM-S908B/DS)
App: 1.22.0 -> 1.23.0

**Comment by MagicLike** [comment]
This is not really an issue regarding the app, but rather a signature difference between the GitHub apk and the PlayStore apk. Android is not able to use the GitHub apk anymore, because the PlayStore as a system app has overwritten the signature which has to be used.
If you would want to use GitHub as a source again, you will need to reinstall the app entirely.

**Comment by HigH-HawK** [comment]
I thought it would be something like this. Just weird that it works with other apps I manually installed, hence the question.

I did not consider it as a bug as such, was just curious about it.
