### ISSUE TITLE
2FA Tokens sync via Nextcloud

### ISSUE THREAD

**Issue by Uneccessary** [jamie-mh/AuthenticatorPro#998]
**Is your feature request related to a problem? Please describe.**
Is always very annoying to export and import from one device to another when you use multiply mobile devices, like a smartphone and a tablet.  

**Describe the solution you'd like**
A option to sync the 2FA tokens encrypted via Nextcloud across different devices.

**Comment by jamie-mh** [comment]
I don't have plans to add first-party support for cloud providers at the moment : [FAQ](https://github.com/jamie-mh/AuthenticatorPro/wiki/Frequently-Asked-Questions#can-you-add-sync-to-google-drive-onedrive-etc)
